opennars: nars.storage.Memory.ReasonerBatch.updateTimer
long nars.storage.Memory.ReasonerBatch.updateTimer ()
To get the timer value and then to reset it.
Returns
The previous timer value
Definition at line 1041 of file Memory.java.
References nars.storage.Memory.ReasonerBatch.getTimer(), and nars.storage.Memory.ReasonerBatch.initTimer().
Referenced by nars.storage.Memory.report().
{
             long i = getTimer();
             initTimer();
             return i;
         }