opennars: nars.storage.Memory.ReasonerBatch.textInputLine
void nars.storage.Memory.ReasonerBatch.textInputLine (String text)
To process a line of input text.
Parameters
text
Definition at line 1000 of file Memory.java.
References nars.io.Symbols.COMMENT_MARK, nars.storage.Memory.getExportStrings(), nars.storage.Memory.inputTask(), nars.io.StringParser.parseExperience(), nars.storage.Memory.ReasonerBatch.reset(), nars.io.Symbols.RESET_MARK, and nars.storage.Memory.ReasonerBatch.walk().
{
             if (!text.isEmpty()) {
                 char c = text.charAt(0);
                 switch (c) {
                     case Symbols.RESET_MARK:
                         reset();
                         memory.getExportStrings().add(text);
                         break;
                     case Symbols.COMMENT_MARK:
                         return;
                     default:
                         // read NARS language or an integer : TODO duplicated code
                         try {
                             int i = Integer.parseInt(text);
                             walk(i);
                         } catch (NumberFormatException e) {
                             Task task = StringParser.parseExperience(new StringBuffer(text), memory, clock);
                             if (task != null) {
                                 memory.inputTask(task);
                             }
                         }
                         break;
                 }
             }
         }