opennars: nars.storage.Memory.ReasonerBatch.doTick
void nars.storage.Memory.ReasonerBatch.doTick ()
Definition at line 954 of file Memory.java.
References nars.storage.Memory.getExportStrings(), nars.storage.Memory.ReasonerBatch.getTimer(), nars.storage.Memory.ReasonerBatch.tickTimer(), and nars.storage.Memory.workCycle().
Referenced by nars.storage.Memory.ReasonerBatch.tick().
{
             if (DEBUG)
                 if ( running || walkingSteps > 0 || !finishedInputs ) {
                     System.out.println("// doTick: "
                             + "walkingSteps " + walkingSteps
                             + ", clock " + clock
                             + ", getTimer " + getTimer()
                             + "\n//    memory.getExportStrings() " + memory.getExportStrings()
                             );
                     System.out.flush();
                 }
               if (walkingSteps == 0) {
                 boolean reasonerShouldRun = false;
                 for (InputChannel channelIn : inputChannels) {
                     reasonerShouldRun = reasonerShouldRun ||
                             channelIn.nextInput();
                 }
                 finishedInputs = ! reasonerShouldRun;
             }
             // forward to output Channels
             List<String> output = memory.getExportStrings();
             if (!output.isEmpty()) {
                 for (OutputChannel channelOut : outputChannels) {
                     channelOut.nextOutput(output);
                 }
                 output.clear(); // this will trigger display the current value of timer in Memory.report()
             }
             if (running || walkingSteps > 0) {
                 clock++;
                 tickTimer();
                 memory.workCycle(clock);
                 if (walkingSteps > 0) {
                     walkingSteps--;
                 }
             }
         }