opennars: nars.language.Statement.invalid
boolean nars.language.Statement.invalid ()
Check the validity of a potential Statement.
[To be refined]
Minimum requirement: the two terms cannot be the same, or containing each other as component
Returns
Whether The Statement is invalid
Definition at line 221 of file Statement.java.
References nars.language.Statement.getPredicate(), nars.language.Statement.getSubject(), and nars.language.Statement.invalidStatement().
{
         return invalidStatement(getSubject(), getPredicate());
     }