opennars: nars.language.Statement.invalidStatement
static boolean nars.language.Statement.invalidStatement (Term subject, Term predicate) static
Check the validity of a potential Statement.
[To be refined]
Minimum requirement: the two terms cannot be the same, or containing each other as component
Parameters
subject The first component
predicate The second component
Returns
Whether The Statement is invalid
Definition at line 191 of file Statement.java.
References nars.language.CompoundTerm.CompoundTerm(), nars.language.Term.equals(), nars.language.Statement.getPredicate(), nars.language.Statement.getSubject(), and nars.language.Statement.Statement().
Referenced by nars.inference.SyllogisticRules.abdIndCom(), nars.inference.SyllogisticRules.analogy(), nars.inference.SyllogisticRules.dedExe(), nars.language.Statement.invalid(), nars.language.Equivalence.make(), nars.language.Implication.make(), nars.language.Statement.make(), nars.language.Similarity.make(), nars.language.Inheritance.make(), and nars.inference.SyllogisticRules.resemblance().
{
         if (subject.equals(predicate)) {
             return true;
         }
         if ((subject instanceof CompoundTerm) && ((CompoundTerm) subject).containComponent(predicate)) {
             return true;
         }
         if ((predicate instanceof CompoundTerm) && ((CompoundTerm) predicate).containComponent(subject)) {
             return true;
         }
         if ((subject instanceof Statement) && (predicate instanceof Statement)) {
             Statement s1 = (Statement) subject;
             Statement s2 = (Statement) predicate;
             Term t11 = s1.getSubject();
             Term t12 = s1.getPredicate();
             Term t21 = s2.getSubject();
             Term t22 = s2.getPredicate();
             if (t11.equals(t22) && t12.equals(t21)) {
                 return true;
             }
         }
         return false;
     }