opennars: nars.language.Statement.makeSym
static Statement nars.language.Statement.makeSym (Statement statement, Term subj, Term pred, Memory memory) static
Make a symmetric Statement from given components and temporal information, called by the rules.
Parameters
statement A sample asymmetric statement providing the class type
subj The first component
pred The second component
memory Reference to the memeory
Returns
The Statement built
Definition at line 128 of file Statement.java.
References nars.language.Equivalence.make(), and nars.language.Similarity.make().
Referenced by nars.inference.SyllogisticRules.abdIndCom().
{
         if (statement instanceof Inheritance) {
             return Similarity.make(subj, pred, memory);
         }
         if (statement instanceof Implication) {
             return Equivalence.make(subj, pred, memory);
         }
         return null;
     }