opennars: nars.language.Statement.make
static Statement nars.language.Statement.make (String relation, Term subject, Term predicate, Memory memory) static
Make a Statement from String, called by StringParser.
Parameters
relation The relation String
subject The first component
predicate The second component
memory Reference to the memeory
Returns
The Statement built
Definition at line 68 of file Statement.java.
References nars.io.Symbols.EQUIVALENCE_RELATION, nars.io.Symbols.IMPLICATION_RELATION, nars.io.Symbols.INHERITANCE_RELATION, nars.io.Symbols.INSTANCE_PROPERTY_RELATION, nars.io.Symbols.INSTANCE_RELATION, nars.language.Statement.invalidStatement(), nars.language.Instance.make(), nars.language.Property.make(), nars.language.InstanceProperty.make(), nars.language.Implication.make(), nars.language.Equivalence.make(), nars.language.Similarity.make(), nars.language.Inheritance.make(), nars.io.Symbols.PROPERTY_RELATION, and nars.io.Symbols.SIMILARITY_RELATION.
Referenced by nars.inference.SyllogisticRules.abdIndCom(), nars.inference.SyllogisticRules.analogy(), nars.inference.SyllogisticRules.conditionalAbd(), nars.inference.SyllogisticRules.conditionalAna(), nars.inference.SyllogisticRules.conditionalDedInd(), nars.inference.StructuralRules.contraposition(), nars.inference.LocalRules.convertedJudgment(), nars.inference.SyllogisticRules.dedExe(), nars.inference.LocalRules.inferToAsym(), nars.language.Statement.make(), nars.io.StringParser.parseStatement(), nars.inference.CompositionalRules.processComposed(), nars.inference.SyllogisticRules.resemblance(), nars.inference.StructuralRules.structuralCompose2(), and nars.inference.StructuralRules.structuralDecompose2().
{
         if (invalidStatement(subject, predicate)) {
             return null;
         }
         if (relation.equals(Symbols.INHERITANCE_RELATION)) {
             return Inheritance.make(subject, predicate, memory);
         }
         if (relation.equals(Symbols.SIMILARITY_RELATION)) {
             return Similarity.make(subject, predicate, memory);
         }
         if (relation.equals(Symbols.INSTANCE_RELATION)) {
             return Instance.make(subject, predicate, memory);
         }
         if (relation.equals(Symbols.PROPERTY_RELATION)) {
             return Property.make(subject, predicate, memory);
         }
         if (relation.equals(Symbols.INSTANCE_PROPERTY_RELATION)) {
             return InstanceProperty.make(subject, predicate, memory);
         }
         if (relation.equals(Symbols.IMPLICATION_RELATION)) {
             return Implication.make(subject, predicate, memory);
         }
         if (relation.equals(Symbols.EQUIVALENCE_RELATION)) {
             return Equivalence.make(subject, predicate, memory);
         }
         return null;
     }