/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jurls.reinforcementlearning.domains;

import java.awt.Color;
import java.awt.Graphics;

/**
 *
 * @author thorsten
 */
public class PhysicsRenderer extends javax.swing.JPanel {

    public Physics2D physics2D;

    /**
     * Creates new form PhysicsRenderer
     */
    public PhysicsRenderer() {
        initComponents();
    }

    @Override
    protected void paintComponent(Graphics g) {
        g.setColor(Color.black);
        g.fillRect(0, 0, getWidth(), getHeight());

        if (physics2D != null) {
            g.setColor(Color.red);
            g.drawLine(0, (int) physics2D.floor, getWidth(), (int) physics2D.floor);

            g.setColor(Color.white);
            for (Connection c : physics2D.connections) {
                g.drawLine((int) c.p1.x, (int) c.p1.y, (int) c.p2.x, (int) c.p2.y);
            }

            g.setColor(Color.yellow);
            for (Point p : physics2D.points) {
                g.drawArc((int) p.x - 10, (int) p.y - 10, 20, 20, 0, 360);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
