opennars: nars.language.IntersectionInt.clone
Object nars.language.IntersectionInt.clone ()
Clone an object.
Returns
A new object, to be casted into a Conjunction
Definition at line 57 of file IntersectionInt.java.
References nars.language.CompoundTerm.cloneList(), nars.language.CompoundTerm.complexity, nars.language.CompoundTerm.components, nars.language.IntersectionInt.IntersectionInt(), nars.language.CompoundTerm.isConstant(), and nars.language.Term.name.
{
         return new IntersectionInt(name, (ArrayList<Term>) cloneList(components), isConstant(), complexity);
     }