opennars: nars.language.ImageExt.make
static Term nars.language.ImageExt.make (List< Term > argList, Memory memory) static
Try to make a new ImageExt.
Called by StringParser.
Returns
the Term generated from the arguments
Parameters
argList The list of components
memory Reference to the memory
Definition at line 78 of file ImageExt.java.
References nars.io.Symbols.IMAGE_PLACE_HOLDER.
Referenced by nars.language.ImageExt.make(), nars.language.CompoundTerm.make(), nars.inference.StructuralRules.transformProductImage(), and nars.inference.StructuralRules.transformSubjectPI().
{
         if (argList.size() < 2) {
             return null;
         }
         Term relation = argList.get(0);
         ArrayList<Term> argument = new ArrayList<Term>();
         int index = 0;
         for (int j = 1; j < argList.size(); j++) {
             if (argList.get(j).getName().charAt(0) == Symbols.IMAGE_PLACE_HOLDER) {
                 index = j - 1;
                 argument.add(relation);
             } else {
                 argument.add(argList.get(j));
             }
         }
         return make(argument, (short) index, memory);
     }