opennars: nars.language.ImageExt.make
static Term nars.language.ImageExt.make (ArrayList< Term > argument, short index, Memory memory) static
Try to make a new compound from a set of components.
Called by the public make methods.
Parameters
argument The argument list
index The index of the place-holder in the new Image
Returns
the Term generated from the arguments
Definition at line 142 of file ImageExt.java.
References nars.io.Symbols.IMAGE_EXT_OPERATOR, nars.language.ImageExt.ImageExt(), nars.language.CompoundTerm.makeImageName(), nars.language.Term.name, and nars.storage.Memory.nameToListedTerm().
{
         String name = makeImageName(Symbols.IMAGE_EXT_OPERATOR, argument, index);
         Term t = memory.nameToListedTerm(name);
         return (t != null) ? t : new ImageExt(name, argument, index);
     }