opennars: nars.inference.SyllogisticRules.analogy
static void nars.inference.SyllogisticRules.analogy (Term term1, Term term2, Sentence asym, Sentence sym, int figure, Memory memory) static package
{<S ==> P>, <M <=> P>} |- <S ==> P>
Parameters
term1 Subject of the new task
term2 Predicate of the new task
asym The asymmetric premise
sym The symmetric premise
figure Locations of the shared term in premises
memory Reference to the memory
Definition at line 148 of file SyllogisticRules.java.
References nars.inference.TruthFunctions.analogy(), nars.inference.BudgetFunctions.backward(), nars.inference.BudgetFunctions.backwardWeak(), nars.storage.Memory.doublePremiseTask(), nars.inference.BudgetFunctions.forward(), nars.entity.Sentence.getContent(), nars.storage.Memory.getCurrentTask(), nars.entity.Task.getSentence(), nars.entity.Sentence.getTruth(), nars.language.Statement.invalidStatement(), nars.language.CompoundTerm.isCommutative(), nars.entity.Sentence.isQuestion(), and nars.language.Statement.make().
Referenced by nars.inference.RuleTables.asymmetricSymmetric().
{
         if (Statement.invalidStatement(term1, term2)) {
             return;
         }
         Statement asymSt = (Statement) asym.getContent();
         // Statement symSt = (Statement) sym.getContent();
         TruthValue truth = null;
         BudgetValue budget;
         Sentence sentence = memory.getCurrentTask().getSentence();
         CompoundTerm taskTerm = (CompoundTerm) sentence.getContent();
         if (sentence.isQuestion()) {
             if (taskTerm.isCommutative()) {
                 budget = BudgetFunctions.backwardWeak(asym.getTruth(), memory);
             } else {
                 budget = BudgetFunctions.backward(sym.getTruth(), memory);
             }
         } else {
             truth = TruthFunctions.analogy(asym.getTruth(), sym.getTruth());
             budget = BudgetFunctions.forward(truth, memory);
         }
         Term content = Statement.make(asymSt, term1, term2, memory);
         memory.doublePremiseTask(content, truth, budget);
     }