opennars: nars.inference.SyllogisticRules.abdIndCom
static void nars.inference.SyllogisticRules.abdIndCom (Term term1, Term term2, Sentence taskSentence, Sentence belief, int figure, Memory memory) static package
{<M ==> S>, <M ==> P>} |- {<S ==> P>,
<P ==> S>, <S <=> P>}
Parameters
term1 Subject of the first new task
term2 Predicate of the first new task
taskSentence The first premise
belief The second premise
figure Locations of the shared term in premises
memory Reference to the memory
Definition at line 97 of file SyllogisticRules.java.
References nars.inference.TruthFunctions.abduction(), nars.inference.BudgetFunctions.backward(), nars.inference.BudgetFunctions.backwardWeak(), nars.inference.TruthFunctions.comparison(), nars.storage.Memory.doublePremiseTask(), nars.inference.BudgetFunctions.forward(), nars.entity.Sentence.getContent(), nars.entity.Sentence.getTruth(), nars.language.Statement.invalidStatement(), nars.entity.Sentence.isQuestion(), nars.language.Statement.make(), and nars.language.Statement.makeSym().
Referenced by nars.inference.RuleTables.asymmetricAsymmetric().
{
         if (Statement.invalidStatement(term1, term2)) {
             return;
         }
         Statement taskContent = (Statement) taskSentence.getContent();
         TruthValue truth1 = null;
         TruthValue truth2 = null;
         TruthValue truth3 = null;
         BudgetValue budget1, budget2, budget3;
         TruthValue value1 = taskSentence.getTruth();
         TruthValue value2 = belief.getTruth();
         if (taskSentence.isQuestion()) {
             budget1 = BudgetFunctions.backward(value2, memory);
             budget2 = BudgetFunctions.backwardWeak(value2, memory);
             budget3 = BudgetFunctions.backward(value2, memory);
         } else {
             truth1 = TruthFunctions.abduction(value1, value2);
             truth2 = TruthFunctions.abduction(value2, value1);
             truth3 = TruthFunctions.comparison(value1, value2);
             budget1 = BudgetFunctions.forward(truth1, memory);
             budget2 = BudgetFunctions.forward(truth2, memory);
             budget3 = BudgetFunctions.forward(truth3, memory);
         }
         Statement statement1 = Statement
                 .make(taskContent, term1, term2, memory);
         Statement statement2 = Statement
                 .make(taskContent, term2, term1, memory);
         Statement statement3 = Statement.makeSym(taskContent, term1, term2,
                 memory);
         memory.doublePremiseTask(statement1, truth1, budget1);
         memory.doublePremiseTask(statement2, truth2, budget2);
         memory.doublePremiseTask(statement3, truth3, budget3);
     }