opennars: nars.inference.SyllogisticRules.conditionalAbd
static boolean nars.inference.SyllogisticRules.conditionalAbd (Term cond1, Term cond2, Statement st1, Statement st2, Memory memory) static package
{<(&&, S2, S3) ==> P>, <(&&, S1, S3) ==> P>} |- <S1 ==> S2>
Parameters
cond1 The condition of the first premise
cond2 The condition of the second premise
taskContent The first premise
st2 The second premise
memory Reference to the memory
Returns
Whether there are derived tasks
Definition at line 461 of file SyllogisticRules.java.
References nars.inference.TruthFunctions.abduction(), nars.inference.BudgetFunctions.backwardWeak(), nars.storage.Memory.doublePremiseTask(), nars.inference.BudgetFunctions.forward(), nars.storage.Memory.getCurrentBelief(), nars.storage.Memory.getCurrentTask(), nars.entity.Task.getSentence(), nars.entity.Sentence.getTruth(), nars.entity.Sentence.isQuestion(), nars.language.Statement.make(), and nars.language.CompoundTerm.reduceComponents().
{
         if (!(st1 instanceof Implication) || !(st2 instanceof Implication)) {
             return false;
         }
         if (!(cond1 instanceof Conjunction) && !(cond2 instanceof Conjunction)) {
             return false;
         }
         Term term1 = null;
         Term term2 = null;
         if (cond1 instanceof Conjunction) {
             term1 = CompoundTerm.reduceComponents((Conjunction) cond1, cond2,
                     memory);
         }
         if (cond2 instanceof Conjunction) {
             term2 = CompoundTerm.reduceComponents((Conjunction) cond2, cond1,
                     memory);
         }
         if ((term1 == null) && (term2 == null)) {
             return false;
         }
         Task task = memory.getCurrentTask();
         Sentence sentence = task.getSentence();
         Sentence belief = memory.getCurrentBelief();
         TruthValue value1 = sentence.getTruth();
         TruthValue value2 = belief.getTruth();
         Term content;
         TruthValue truth = null;
         BudgetValue budget;
         if (term1 != null) {
             if (term2 != null) {
                 content = Statement.make(st2, term2, term1, memory);
             } else {
                 content = term1;
             }
             if (sentence.isQuestion()) {
                 budget = BudgetFunctions.backwardWeak(value2, memory);
             } else {
                 truth = TruthFunctions.abduction(value2, value1);
                 budget = BudgetFunctions.forward(truth, memory);
             }
             memory.doublePremiseTask(content, truth, budget);
         }
         if (term2 != null) {
             if (term1 != null) {
                 content = Statement.make(st1, term1, term2, memory);
             } else {
                 content = term2;
             }
             if (sentence.isQuestion()) {
                 budget = BudgetFunctions.backwardWeak(value2, memory);
             } else {
                 truth = TruthFunctions.abduction(value1, value2);
                 budget = BudgetFunctions.forward(truth, memory);
             }
             memory.doublePremiseTask(content, truth, budget);
         }
         return true;
     }