opennars: nars.inference.SyllogisticRules.conditionalDedInd
static void nars.inference.SyllogisticRules.conditionalDedInd (Implication premise1, short index, Term premise2, int side, Memory memory) static package
{<(&&, S1, S2, S3) ==> P>, S1} |- <(&&, S2, S3) ==> P> {<(&&, S2, S3) ==> P>, <S1 ==> S2>} |- <(&&, S1, S3) ==> P> {<(&&, S1, S3) ==> P>, <S1 ==> S2>} |- <(&&, S2, S3) ==> P>
Parameters
premise1 The conditional premise
index The location of the shared term in the condition of premise1
premise2 The premise which, or part of which, appears in the condition of premise1
side The location of the shared term in premise2: 0 for subject, 1 for predicate, -1 for the whole term
memory Reference to the memory
Definition at line 291 of file SyllogisticRules.java.
References nars.inference.BudgetFunctions.backwardWeak(), nars.language.CompoundTerm.componentAt(), nars.inference.TruthFunctions.deduction(), nars.storage.Memory.doublePremiseTask(), nars.language.Term.equals(), nars.inference.BudgetFunctions.forward(), nars.language.CompoundTerm.getComponents(), nars.entity.Sentence.getContent(), nars.storage.Memory.getCurrentBelief(), nars.storage.Memory.getCurrentTask(), nars.language.Statement.getPredicate(), nars.entity.Task.getSentence(), nars.language.Statement.getSubject(), nars.entity.Sentence.getTruth(), nars.language.Variable.hasSubstitute(), nars.inference.TruthFunctions.induction(), nars.entity.Sentence.isQuestion(), nars.language.Statement.make(), nars.language.CompoundTerm.setComponent(), nars.language.Variable.unify(), and nars.io.Symbols.VAR_INDEPENDENT.
Referenced by nars.inference.RuleTables.conditionalDedIndWithVar(), and nars.inference.RuleTables.reason().
{
         Task task = memory.getCurrentTask();
         Sentence taskSentence = task.getSentence();
         Sentence belief = memory.getCurrentBelief();
         boolean deduction = (side != 0);
         boolean conditionalTask = Variable.hasSubstitute(
                 Symbols.VAR_INDEPENDENT, premise2, belief.getContent());
         Term commonComponent;
         Term newComponent = null;
         if (side == 0) {
             commonComponent = ((Statement) premise2).getSubject();
             newComponent = ((Statement) premise2).getPredicate();
         } else if (side == 1) {
             commonComponent = ((Statement) premise2).getPredicate();
             newComponent = ((Statement) premise2).getSubject();
         } else {
             commonComponent = premise2;
         }
         Conjunction oldCondition = (Conjunction) premise1.getSubject();
         int index2 = oldCondition.getComponents().indexOf(commonComponent);
         if (index2 >= 0) {
             index = (short) index2;
         } else {
             boolean match = Variable.unify(Symbols.VAR_INDEPENDENT,
                     oldCondition.componentAt(index), commonComponent, premise1,
                     premise2);
             if (!match
                     && (commonComponent.getClass() == oldCondition.getClass())) {
                 match = Variable.unify(Symbols.VAR_INDEPENDENT,
                         oldCondition.componentAt(index),
                         ((CompoundTerm) commonComponent).componentAt(index),
                         premise1, premise2);
             }
             if (!match) {
                 return;
             }
         }
         Term newCondition;
         if (oldCondition.equals(commonComponent)) {
             newCondition = null;
         } else {
             newCondition = CompoundTerm.setComponent(oldCondition, index,
                     newComponent, memory);
         }
         Term content;
         if (newCondition != null) {
             content = Statement.make(premise1, newCondition,
                     premise1.getPredicate(), memory);
         } else {
             content = premise1.getPredicate();
         }
         if (content == null) {
             return;
         }
         TruthValue truth1 = taskSentence.getTruth();
         TruthValue truth2 = belief.getTruth();
         TruthValue truth = null;
         BudgetValue budget;
         if (taskSentence.isQuestion()) {
             budget = BudgetFunctions.backwardWeak(truth2, memory);
         } else {
             if (deduction) {
                 truth = TruthFunctions.deduction(truth1, truth2);
             } else if (conditionalTask) {
                 truth = TruthFunctions.induction(truth2, truth1);
             } else {
                 truth = TruthFunctions.induction(truth1, truth2);
             }
             budget = BudgetFunctions.forward(truth, memory);
         }
         memory.doublePremiseTask(content, truth, budget);
     }