opennars: nars.inference.SyllogisticRules.resemblance
static void nars.inference.SyllogisticRules.resemblance (Term term1, Term term2, Sentence belief, Sentence sentence, int figure, Memory memory) static package
{<S <=> M>, <M <=> P>} |- <S <=> P>
Parameters
term1 Subject of the new task
term2 Predicate of the new task
belief The first premise
sentence The second premise
figure Locations of the shared term in premises
memory Reference to the memory
Definition at line 189 of file SyllogisticRules.java.
References nars.inference.BudgetFunctions.backward(), nars.storage.Memory.doublePremiseTask(), nars.inference.BudgetFunctions.forward(), nars.entity.Sentence.getContent(), nars.entity.Sentence.getTruth(), nars.language.Statement.invalidStatement(), nars.entity.Sentence.isQuestion(), nars.language.Statement.make(), and nars.inference.TruthFunctions.resemblance().
Referenced by nars.inference.RuleTables.symmetricSymmetric().
{
         if (Statement.invalidStatement(term1, term2)) {
             return;
         }
         Statement st1 = (Statement) belief.getContent();
         // Statement st2 = (Statement) sentence.getContent();
         TruthValue truth = null;
         BudgetValue budget;
         if (sentence.isQuestion()) {
             budget = BudgetFunctions.backward(belief.getTruth(), memory);
         } else {
             truth = TruthFunctions.resemblance(belief.getTruth(),
                     sentence.getTruth());
             budget = BudgetFunctions.forward(truth, memory);
         }
         Term statement = Statement.make(st1, term1, term2, memory);
         memory.doublePremiseTask(statement, truth, budget);
     }