opennars: nars.inference.SyllogisticRules.conditionalAna
static void nars.inference.SyllogisticRules.conditionalAna (Equivalence premise1, short index, Term premise2, int side, Memory memory) static package
{<(&&, S1, S2) <=> P>, (&&, S1, S2)} |- P
Parameters
premise1 The equivalence premise
index The location of the shared term in the condition of premise1
premise2 The premise which, or part of which, appears in the condition of premise1
side The location of the shared term in premise2: 0 for subject, 1 for predicate, -1 for the whole term
memory Reference to the memory
Definition at line 381 of file SyllogisticRules.java.
References nars.inference.TruthFunctions.analogy(), nars.inference.BudgetFunctions.backwardWeak(), nars.inference.TruthFunctions.comparison(), nars.language.CompoundTerm.componentAt(), nars.storage.Memory.doublePremiseTask(), nars.language.Term.equals(), nars.inference.BudgetFunctions.forward(), nars.entity.Sentence.getContent(), nars.storage.Memory.getCurrentBelief(), nars.storage.Memory.getCurrentTask(), nars.entity.Task.getSentence(), nars.language.Statement.getSubject(), nars.entity.Sentence.getTruth(), nars.language.Variable.hasSubstitute(), nars.entity.Sentence.isQuestion(), nars.language.Statement.make(), nars.language.CompoundTerm.setComponent(), nars.language.Variable.unify(), nars.io.Symbols.VAR_DEPENDENT, and nars.io.Symbols.VAR_INDEPENDENT.
Referenced by nars.inference.RuleTables.reason().
{
         Task task = memory.getCurrentTask();
         Sentence taskSentence = task.getSentence();
         Sentence belief = memory.getCurrentBelief();
         boolean conditionalTask = Variable.hasSubstitute(
                 Symbols.VAR_INDEPENDENT, premise2, belief.getContent());
         Term commonComponent;
         Term newComponent = null;
         if (side == 0) {
             commonComponent = ((Statement) premise2).getSubject();
             newComponent = ((Statement) premise2).getPredicate();
         } else if (side == 1) {
             commonComponent = ((Statement) premise2).getPredicate();
             newComponent = ((Statement) premise2).getSubject();
         } else {
             commonComponent = premise2;
         }
         Conjunction oldCondition = (Conjunction) premise1.getSubject();
         boolean match = Variable.unify(Symbols.VAR_DEPENDENT,
                 oldCondition.componentAt(index), commonComponent, premise1,
                 premise2);
         if (!match && (commonComponent.getClass() == oldCondition.getClass())) {
             match = Variable.unify(Symbols.VAR_DEPENDENT,
                     oldCondition.componentAt(index),
                     ((CompoundTerm) commonComponent).componentAt(index),
                     premise1, premise2);
         }
         if (!match) {
             return;
         }
         Term newCondition;
         if (oldCondition.equals(commonComponent)) {
             newCondition = null;
         } else {
             newCondition = CompoundTerm.setComponent(oldCondition, index,
                     newComponent, memory);
         }
         Term content;
         if (newCondition != null) {
             content = Statement.make(premise1, newCondition,
                     premise1.getPredicate(), memory);
         } else {
             content = premise1.getPredicate();
         }
         if (content == null) {
             return;
         }
         TruthValue truth1 = taskSentence.getTruth();
         TruthValue truth2 = belief.getTruth();
         TruthValue truth = null;
         BudgetValue budget;
         if (taskSentence.isQuestion()) {
             budget = BudgetFunctions.backwardWeak(truth2, memory);
         } else {
             if (conditionalTask) {
                 truth = TruthFunctions.comparison(truth1, truth2);
             } else {
                 truth = TruthFunctions.analogy(truth1, truth2);
             }
             budget = BudgetFunctions.forward(truth, memory);
         }
         memory.doublePremiseTask(content, truth, budget);
     }