opennars: nars.inference.SyllogisticRules.dedExe
static void nars.inference.SyllogisticRules.dedExe (Term term1, Term term2, Sentence sentence, Sentence belief, Memory memory) static package
{<S ==> M>, <M ==> P>} |- {<S ==> P>, <P ==> S>}
Parameters
term1 Subject of the first new task
term2 Predicate of the first new task
sentence The first premise
belief The second premise
memory Reference to the memory
Definition at line 53 of file SyllogisticRules.java.
References nars.inference.BudgetFunctions.backwardWeak(), nars.inference.TruthFunctions.deduction(), nars.storage.Memory.doublePremiseTask(), nars.inference.TruthFunctions.exemplification(), nars.inference.BudgetFunctions.forward(), nars.entity.Sentence.getContent(), nars.entity.Sentence.getTruth(), nars.language.Statement.invalidStatement(), nars.entity.Sentence.isQuestion(), and nars.language.Statement.make().
Referenced by nars.inference.RuleTables.asymmetricAsymmetric().
{
         if (Statement.invalidStatement(term1, term2)) {
             return;
         }
         TruthValue value1 = sentence.getTruth();
         TruthValue value2 = belief.getTruth();
         TruthValue truth1 = null;
         TruthValue truth2 = null;
         BudgetValue budget1, budget2;
         if (sentence.isQuestion()) {
             budget1 = BudgetFunctions.backwardWeak(value2, memory);
             budget2 = BudgetFunctions.backwardWeak(value2, memory);
         } else {
             truth1 = TruthFunctions.deduction(value1, value2);
             truth2 = TruthFunctions.exemplification(value1, value2);
             budget1 = BudgetFunctions.forward(truth1, memory);
             budget2 = BudgetFunctions.forward(truth2, memory);
         }
         Statement content = (Statement) sentence.getContent();
         Statement content1 = Statement.make(content, term1, term2, memory);
         Statement content2 = Statement.make(content, term2, term1, memory);
         memory.doublePremiseTask(content1, truth1, budget1);
         memory.doublePremiseTask(content2, truth2, budget2);
     }