opennars: nars.inference.SyllogisticRules.detachment
static void nars.inference.SyllogisticRules.detachment (Sentence mainSentence, Sentence subSentence, int side, Memory memory) static package
{<<M --> S> ==> <M --> P>>, <M --> S>} |- <M --> P> {<<M --> S> ==> <M –> P>>, <M --> P>} |- <M --> S> {<<M --> S> <=> <M --> P>>, <M --> S>} |- <M --> P> {<<M --> S> <=> <M --> P>>, <M --> P>} |- <M --> S>
Parameters
mainSentence The implication/equivalence premise
subSentence The premise on part of s1
side The location of s2 in s1
memory Reference to the memory
Definition at line 224 of file SyllogisticRules.java.
References nars.inference.TruthFunctions.abduction(), nars.inference.TruthFunctions.analogy(), nars.inference.BudgetFunctions.backward(), nars.inference.BudgetFunctions.backwardWeak(), nars.inference.TruthFunctions.deduction(), nars.storage.Memory.doublePremiseTask(), nars.language.Term.equals(), nars.inference.BudgetFunctions.forward(), nars.entity.Sentence.getContent(), nars.storage.Memory.getCurrentBelief(), nars.storage.Memory.getCurrentTask(), nars.language.Statement.getPredicate(), nars.entity.Task.getSentence(), nars.language.Statement.getSubject(), nars.entity.Sentence.getTruth(), and nars.entity.Sentence.isQuestion().
Referenced by nars.inference.RuleTables.detachmentWithVar(), and nars.inference.RuleTables.reason().
{
         Statement statement = (Statement) mainSentence.getContent();
         if (!(statement instanceof Implication)
                 && !(statement instanceof Equivalence)) {
             return;
         }
         Term subject = statement.getSubject();
         Term predicate = statement.getPredicate();
         Term content;
         Term term = subSentence.getContent();
         if ((side == 0) && term.equals(subject)) {
             content = predicate;
         } else if ((side == 1) && term.equals(predicate)) {
             content = subject;
         } else {
             return;
         }
         if ((content instanceof Statement) && ((Statement) content).invalid()) {
             return;
         }
         Sentence taskSentence = memory.getCurrentTask().getSentence();
         Sentence beliefSentence = memory.getCurrentBelief();
         TruthValue beliefTruth = beliefSentence.getTruth();
         TruthValue truth1 = mainSentence.getTruth();
         TruthValue truth2 = subSentence.getTruth();
         TruthValue truth = null;
         BudgetValue budget;
         if (taskSentence.isQuestion()) {
             if (statement instanceof Equivalence) {
                 budget = BudgetFunctions.backward(beliefTruth, memory);
             } else if (side == 0) {
                 budget = BudgetFunctions.backwardWeak(beliefTruth, memory);
             } else {
                 budget = BudgetFunctions.backward(beliefTruth, memory);
             }
         } else {
             if (statement instanceof Equivalence) {
                 truth = TruthFunctions.analogy(truth2, truth1);
             } else if (side == 0) {
                 truth = TruthFunctions.deduction(truth1, truth2);
             } else {
                 truth = TruthFunctions.abduction(truth2, truth1);
             }
             budget = BudgetFunctions.forward(truth, memory);
         }
         memory.doublePremiseTask(content, truth, budget);
     }