///*
// * Copyright (C) 2014 tc
// *
// * This program is free software: you can redistribute it and/or modify
// * it under the terms of the GNU General Public License as published by
// * the Free Software Foundation, either version 3 of the License, or
// * (at your option) any later version.
// *
// * This program is distributed in the hope that it will be useful,
// * but WITHOUT ANY WARRANTY; without even the implied warranty of
// * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// * GNU General Public License for more details.
// *
// * You should have received a copy of the GNU General Public License
// * along with this program.  If not, see <http://www.gnu.org/licenses/>.
// */
//
//package nars.launcher;
//
//import nars.NAR;
//import nars.Video;
//import nars.gui.NARSwing;
//import nars.nar.Default;
//import nars.nario.NARio;
//import nars.rover.run.SomeRovers;
//import nars.web.NARServer;
//
//import javax.imageio.ImageIO;
//import javax.swing.*;
//import java.awt.*;
//import java.awt.image.BufferedImage;
//import java.io.File;
//import java.io.IOException;
//import java.net.URI;
//import java.util.logging.Level;
//import java.util.logging.Logger;
//
///**
// *
// * @author tc
// */
//public class Launcher extends javax.swing.JFrame {
//
//    public static File resource(String path) {
//        return new File("./nars_lab/nars/launcher/" + path);
//    }
//
//    /**
//     * Creates new form Launcher
//     */
//    public Launcher() {
//        initComponents();
//
//        jLabel1.setIcon(new ImageIcon("./doc/opennars_logo2.png"));
//
//        this.setTitle("OpenNARS Launcher");
//
//        try {
//            BufferedImage myPicture = ImageIO.read(resource("mario.png"));
//            jLabel8.setIcon(new ImageIcon(myPicture));
//
//        } catch (IOException ex) {
//            Logger.getLogger(Launcher.class.getName()).log(Level.SEVERE, null, ex);
//        }
//
//        try {
//            BufferedImage myPicture = ImageIO.read(resource("testchamber.png"));
//            jLabel6.setIcon(new ImageIcon(myPicture));
//
//        } catch (IOException ex) {
//            Logger.getLogger(Launcher.class.getName()).log(Level.SEVERE, null, ex);
//        }
//
//        try {
//            BufferedImage myPicture = ImageIO.read(resource("rover.png"));
//            jLabel7.setIcon(new ImageIcon(myPicture));
//
//        } catch (IOException ex) {
//            Logger.getLogger(Launcher.class.getName()).log(Level.SEVERE, null, ex);
//        }
//
//        try {
//            BufferedImage myPicture = ImageIO.read(resource("nartactoe.png"));
//            jLabel2.setIcon(new ImageIcon(myPicture));
//
//        } catch (IOException ex) {
//            Logger.getLogger(Launcher.class.getName()).log(Level.SEVERE, null, ex);
//        }
//
//        try {
//            BufferedImage myPicture = ImageIO.read(resource("predict.png"));
//            jLabel5.setIcon(new ImageIcon(myPicture));
//
//        } catch (IOException ex) {
//            Logger.getLogger(Launcher.class.getName()).log(Level.SEVERE, null, ex);
//        }
//    }
//
//    /**
//     * This method is called from within the constructor to initialize the form.
//     * WARNING: Do NOT modify this code. The content of this method is always
//     * regenerated by the Form Editor.
//     */
//    @SuppressWarnings("unchecked")
//    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
//    private void initComponents() {
//
//        jPanel2 = new javax.swing.JPanel();
//        jPanel1 = new javax.swing.JPanel();
//        jLabel1 = new javax.swing.JLabel();
//        jButton1 = new javax.swing.JButton();
//        jLabel2 = new javax.swing.JLabel();
//        jLabel3 = new javax.swing.JLabel();
//        jButton2 = new javax.swing.JButton();
//        jLabel6 = new javax.swing.JLabel();
//        jLabel7 = new javax.swing.JLabel();
//        jButton5 = new javax.swing.JButton();
//        jLabel5 = new javax.swing.JLabel();
//        jLabel8 = new javax.swing.JLabel();
//        jButton3 = new javax.swing.JButton();
//
//        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
//
//        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
//
//        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
//
//        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
//        jPanel1.setLayout(jPanel1Layout);
//        jPanel1Layout.setHorizontalGroup(
//            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(jPanel1Layout.createSequentialGroup()
//                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
//                .addGap(0, 0, Short.MAX_VALUE))
//        );
//        jPanel1Layout.setVerticalGroup(
//            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
//        );
//
//        jButton1.setForeground(new java.awt.Color(255, 255, 254));
//        jButton1.setText(" Run NARS GUI");
//        jButton1.setActionCommand("jButton1");
//        jButton1.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                jButton1ActionPerformed(evt);
//            }
//        });
//
//        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
//        jLabel2.setForeground(new java.awt.Color(254, 255, 255));
//        jLabel2.setText("Tic Tac Toe");
//        jLabel2.setToolTipText("");
//        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
//            public void mouseClicked(java.awt.event.MouseEvent evt) {
//                jLabel2MouseClicked(evt);
//            }
//            public void mouseEntered(java.awt.event.MouseEvent evt) {
//                jLabel2MouseEntered(evt);
//            }
//        });
//
//        jLabel3.setForeground(new java.awt.Color(254, 255, 255));
//        jLabel3.setText("Run Application Examples:");
//
//        jButton2.setForeground(new java.awt.Color(254, 255, 255));
//        jButton2.setText("Website");
//        jButton2.setActionCommand("jButton1");
//        jButton2.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                jButton2ActionPerformed(evt);
//            }
//        });
//
//        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
//        jLabel6.setForeground(new java.awt.Color(254, 255, 255));
//        jLabel6.setText("Test Chamber");
//        jLabel6.setToolTipText("");
//        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
//            public void mouseClicked(java.awt.event.MouseEvent evt) {
//                jLabel6MouseClicked(evt);
//            }
//        });
//
//        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
//        jLabel7.setForeground(new java.awt.Color(254, 255, 255));
//        jLabel7.setText("Rover");
//        jLabel7.setToolTipText("");
//        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
//            public void mouseClicked(java.awt.event.MouseEvent evt) {
//                jLabel7MouseClicked(evt);
//            }
//            public void mouseEntered(java.awt.event.MouseEvent evt) {
//                jLabel7MouseEntered(evt);
//            }
//        });
//
//        jButton5.setForeground(new java.awt.Color(254, 255, 255));
//        jButton5.setText("IRC");
//        jButton5.setActionCommand("jButton1");
//        jButton5.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                jButton5ActionPerformed(evt);
//            }
//        });
//
//        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
//        jLabel5.setForeground(new java.awt.Color(254, 255, 255));
//        jLabel5.setText("NAR Pred");
//        jLabel5.setToolTipText("");
//        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
//            public void mouseClicked(java.awt.event.MouseEvent evt) {
//                jLabel5MouseClicked(evt);
//            }
//            public void mouseEntered(java.awt.event.MouseEvent evt) {
//                jLabel5MouseEntered(evt);
//            }
//        });
//
//        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
//        jLabel8.setForeground(new java.awt.Color(254, 255, 255));
//        jLabel8.setText("Nario");
//        jLabel8.setToolTipText("");
//        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
//            public void mouseClicked(java.awt.event.MouseEvent evt) {
//                jLabel8MouseClicked(evt);
//            }
//            public void mouseEntered(java.awt.event.MouseEvent evt) {
//                jLabel8MouseEntered(evt);
//            }
//        });
//
//        jButton3.setForeground(new java.awt.Color(255, 255, 254));
//        jButton3.setText("Run Web GUI");
//        jButton3.setActionCommand("jButton1");
//        jButton3.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                jButton3ActionPerformed(evt);
//            }
//        });
//
//        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
//        jPanel2.setLayout(jPanel2Layout);
//        jPanel2Layout.setHorizontalGroup(
//            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(jPanel2Layout.createSequentialGroup()
//                .addGap(12, 12, 12)
//                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                    .addGroup(jPanel2Layout.createSequentialGroup()
//                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                            .addGroup(jPanel2Layout.createSequentialGroup()
//                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                .addGap(0, 0, Short.MAX_VALUE))
//                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
//                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
//                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
//                            .addGroup(jPanel2Layout.createSequentialGroup()
//                                .addComponent(jButton2)
//                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                .addGap(8, 8, 8)))
//                        .addGap(65, 65, 65))
//                    .addGroup(jPanel2Layout.createSequentialGroup()
//                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
//                            .addComponent(jLabel3)
//                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                            .addGroup(jPanel2Layout.createSequentialGroup()
//                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                                .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
//                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
//        );
//        jPanel2Layout.setVerticalGroup(
//            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(jPanel2Layout.createSequentialGroup()
//                .addContainerGap()
//                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                .addGap(18, 18, 18)
//                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                    .addComponent(jButton1)
//                    .addComponent(jButton3))
//                .addGap(18, 18, 18)
//                .addComponent(jLabel3)
//                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
//                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
//                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
//                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
//                .addGap(1, 1, 1)
//                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
//                    .addComponent(jButton5)
//                    .addComponent(jButton2))
//                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
//        );
//
//        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
//        getContentPane().setLayout(layout);
//        layout.setHorizontalGroup(
//            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 326, Short.MAX_VALUE)
//        );
//        layout.setVerticalGroup(
//            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE)
//        );
//
//        pack();
//    }// </editor-fold>//GEN-END:initComponents
//
//    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
//        NARSwing sw=new NARSwing(new NAR(new Default()));
//        this.dispose();
//
//    }//GEN-LAST:event_jButton1ActionPerformed
//
//    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
//        nars.tictactoe.TicTacToe.main(new String[]{});
//        this.dispose();
//    }//GEN-LAST:event_jLabel2MouseClicked
//
//    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
//        try{
//        Desktop.getDesktop().browse(new URI("http://code.google.com/p/open-nars/"));
//        }catch(Exception ex){}
//    }//GEN-LAST:event_jButton2ActionPerformed
//
//    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
//        nars.testchamber.TestChamber.main(new String[]{});
//        //this.setVisible(false);
//        this.dispose();
//    }//GEN-LAST:event_jLabel6MouseClicked
//
//    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
//        // TODO add your handling code here:
//    }//GEN-LAST:event_jLabel2MouseEntered
//
//    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
//        SomeRovers.main(new String[]{});
//        this.dispose();
//    }//GEN-LAST:event_jLabel7MouseClicked
//
//    private void jLabel7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseEntered
//        // TODO add your handling code here:
//    }//GEN-LAST:event_jLabel7MouseEntered
//
//    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
//         try{
//        Desktop.getDesktop().browse(new URI("http://webchat.freenode.net/?channels=nars"));
//        }catch(Exception ex){}
//    }//GEN-LAST:event_jButton5ActionPerformed
//
//    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
//
//            new Thread(new Runnable() { @Override public void run() {
////                try {
////                    nars.predict.Predict_NARS_Core.main(new String[]{});
////                } catch (Narsese.InvalidInputException ex) {
////                    Logger.getLogger(Launcher.class.getName()).log(Level.SEVERE, null, ex);
////                } catch (InterruptedException ex) {
////                    Logger.getLogger(Launcher.class.getName()).log(Level.SEVERE, null, ex);
////                }
//            }
//            }).start();
//            this.dispose();
//    }//GEN-LAST:event_jLabel5MouseClicked
//
//    private void jLabel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseEntered
//        // TODO add your handling code here:
//    }//GEN-LAST:event_jLabel5MouseEntered
//
//    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
//        NARio.main(null);
//    }//GEN-LAST:event_jLabel8MouseClicked
//
//    private void jLabel8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseEntered
//        // TODO add your handling code here:
//    }//GEN-LAST:event_jLabel8MouseEntered
//
//    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
//        try {
//            NARServer.main(new String[]{"9999","localhost","1000"});
//            Desktop.getDesktop().browse(new URI("http://127.0.0.1:9999"));
//        }catch(Exception ex){}
//    }//GEN-LAST:event_jButton3ActionPerformed
//
//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
//         */
//
////        try {
////            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
////                if ("Nimbus".equals(info.getName())) {
////                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
////                    break;
////                }
////            }
////        } catch (ClassNotFoundException ex) {
////            java.other.logging.Logger.getLogger(Launcher.class.getName()).log(java.other.logging.Level.SEVERE, null, ex);
////        } catch (InstantiationException ex) {
////            java.other.logging.Logger.getLogger(Launcher.class.getName()).log(java.other.logging.Level.SEVERE, null, ex);
////        } catch (IllegalAccessException ex) {
////            java.other.logging.Logger.getLogger(Launcher.class.getName()).log(java.other.logging.Level.SEVERE, null, ex);
////        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
////            java.other.logging.Logger.getLogger(Launcher.class.getName()).log(java.other.logging.Level.SEVERE, null, ex);
////        }
//        //</editor-fold>
//
//        Video.themeInvert();
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Launcher().setVisible(true);
//            }
//        });
//    }
//
//    // Variables declaration - do not modify//GEN-BEGIN:variables
//    private javax.swing.JButton jButton1;
//    private javax.swing.JButton jButton2;
//    private javax.swing.JButton jButton3;
//    private javax.swing.JButton jButton5;
//    private javax.swing.JLabel jLabel1;
//    private javax.swing.JLabel jLabel2;
//    private javax.swing.JLabel jLabel3;
//    private javax.swing.JLabel jLabel5;
//    private javax.swing.JLabel jLabel6;
//    private javax.swing.JLabel jLabel7;
//    private javax.swing.JLabel jLabel8;
//    private javax.swing.JPanel jPanel1;
//    private javax.swing.JPanel jPanel2;
//    // End of variables declaration//GEN-END:variables
// }
