opennars: nars.entity.Task.getSentence
Sentence nars.entity.Task.getSentence ()
Get the sentence.
Returns
The sentence
Definition at line 99 of file Task.java.
References nars.entity.Task.sentence.
Referenced by nars.storage.Memory.activatedTask(), nars.inference.SyllogisticRules.analogy(), nars.inference.CompositionalRules.composeCompound(), nars.inference.RuleTables.compoundAndStatement(), nars.inference.SyllogisticRules.conditionalAbd(), nars.inference.SyllogisticRules.conditionalAna(), nars.inference.SyllogisticRules.conditionalDedInd(), nars.inference.StructuralRules.contraposition(), nars.inference.CompositionalRules.decomposeCompound(), nars.inference.CompositionalRules.decomposeStatement(), nars.storage.Memory.derivedTask(), nars.inference.SyllogisticRules.detachment(), nars.inference.RuleTables.detachmentWithVar(), nars.entity.Concept.directProcess(), nars.storage.Memory.doublePremiseTask(), nars.inference.SyllogisticRules.elimiVarDep(), nars.entity.Concept.getBelief(), nars.storage.Memory.inputTask(), nars.inference.CompositionalRules.introVarInner(), nars.inference.CompositionalRules.introVarOuter(), nars.inference.LocalRules.match(), nars.inference.LocalRules.matchAsymSym(), nars.inference.LocalRules.matchReverse(), nars.entity.TaskLink.novel(), nars.entity.Concept.processJudgment(), nars.storage.Memory.processNewTask(), nars.entity.Concept.processQuestion(), nars.inference.RuleTables.reason(), nars.storage.Memory.singlePremiseTask(), nars.inference.BudgetFunctions.solutionEval(), nars.inference.StructuralRules.structuralCompose1(), nars.inference.StructuralRules.structuralCompose2(), nars.inference.StructuralRules.structuralCompound(), nars.inference.StructuralRules.structuralDecompose1(), nars.inference.StructuralRules.structuralDecompose2(), nars.inference.RuleTables.syllogisms(), nars.entity.TaskLink.toString(), nars.entity.Task.toString(), nars.inference.StructuralRules.transformNegation(), nars.inference.StructuralRules.transformPredicatePI(), nars.inference.StructuralRules.transformProductImage(), nars.inference.StructuralRules.transformSetRelation(), nars.inference.StructuralRules.transformSubjectPI(), nars.inference.LocalRules.trySolution(), and nars.inference.BudgetFunctions.update().
{
         return sentence;
     }