opennars: nars.entity.Task.toString
String nars.entity.Task.toString ()
Get a String representation of the Task.
Returns
The Task as a String
Definition at line 186 of file Task.java.
References nars.entity.Task.getSentence(), nars.entity.Item.toStringBrief(), and nars.entity.Sentence.toStringBrief().
Referenced by nars.storage.Memory.activatedTask().
{
         StringBuffer s = new StringBuffer();
         s.append(super.toString() + " ");
         s.append(getSentence().getStamp());
         if (parentTask != null) {
             s.append("  \n from task: " + parentTask.toStringBrief());
             if (parentBelief != null) {
                 s.append("  \n from belief: " + parentBelief.toStringBrief());
             }
         }
         if (bestSolution != null) {
             s.append("  \n solution: " + bestSolution.toStringBrief());
         }
 //        s.append("\n>>>> end of Task");
         return s.toString();
     }