opennars: nars.entity.Task.merge
void nars.entity.Task.merge (Item that)
Merge one Task into another.
Parameters
that The other Task
Definition at line 145 of file Task.java.
References nars.entity.Task.getCreationTime(), and nars.entity.Task.merge().
Referenced by nars.entity.Task.merge().
{
         if (getCreationTime() >= ((Task) that).getCreationTime()) {
             super.merge(that);
         } else {
             that.merge(this);
         }
     }