opennars: nars.inference.RuleTables.compoundAndCompound
static void nars.inference.RuleTables.compoundAndCompound (CompoundTerm taskTerm, CompoundTerm beliefTerm, Memory memory) static private
Inference between two compound terms.
Parameters
taskTerm The compound from the task
beliefTerm The compound from the belief
memory Reference to the memory
Definition at line 602 of file RuleTables.java.
References nars.inference.RuleTables.compoundAndSelf(), and nars.language.CompoundTerm.size().
Referenced by nars.inference.RuleTables.reason().
{
         if (taskTerm.getClass() == beliefTerm.getClass()) {
             if (taskTerm.size() > beliefTerm.size()) {
                 compoundAndSelf(taskTerm, beliefTerm, true, memory);
             } else if (taskTerm.size() < beliefTerm.size()) {
                 compoundAndSelf(beliefTerm, taskTerm, false, memory);
             }
         }
     }