opennars: nars.inference.RuleTables.syllogisms
static void nars.inference.RuleTables.syllogisms (TaskLink tLink, TermLink bLink, Term taskTerm, Term beliefTerm, Memory memory) static private
Meta-table of syllogistic rules, indexed by the content classes of the taskSentence and the belief.
Parameters
tLink The link to task
bLink The link to belief
taskTerm The content of task
beliefTerm The content of belief
memory Reference to the memory
Definition at line 197 of file RuleTables.java.
References nars.inference.RuleTables.asymmetricAsymmetric(), nars.inference.RuleTables.asymmetricSymmetric(), nars.inference.RuleTables.detachmentWithVar(), nars.storage.Memory.getCurrentBelief(), nars.storage.Memory.getCurrentTask(), nars.entity.TermLink.getIndex(), nars.entity.Task.getSentence(), nars.inference.RuleTables.indexToFigure(), and nars.inference.RuleTables.symmetricSymmetric().
Referenced by nars.inference.RuleTables.reason().
{
         Sentence taskSentence = memory.getCurrentTask().getSentence();
         Sentence belief = memory.getCurrentBelief();
         int figure;
         if (taskTerm instanceof Inheritance) {
             if (beliefTerm instanceof Inheritance) {
                 figure = indexToFigure(tLink, bLink);
                 asymmetricAsymmetric(taskSentence, belief, figure, memory);
             } else if (beliefTerm instanceof Similarity) {
                 figure = indexToFigure(tLink, bLink);
                 asymmetricSymmetric(taskSentence, belief, figure, memory);
             } else {
                 detachmentWithVar(belief, taskSentence, bLink.getIndex(0),
                         memory);
             }
         } else if (taskTerm instanceof Similarity) {
             if (beliefTerm instanceof Inheritance) {
                 figure = indexToFigure(bLink, tLink);
                 asymmetricSymmetric(belief, taskSentence, figure, memory);
             } else if (beliefTerm instanceof Similarity) {
                 figure = indexToFigure(bLink, tLink);
                 symmetricSymmetric(belief, taskSentence, figure, memory);
             }
         } else if (taskTerm instanceof Implication) {
             if (beliefTerm instanceof Implication) {
                 figure = indexToFigure(tLink, bLink);
                 asymmetricAsymmetric(taskSentence, belief, figure, memory);
             } else if (beliefTerm instanceof Equivalence) {
                 figure = indexToFigure(tLink, bLink);
                 asymmetricSymmetric(taskSentence, belief, figure, memory);
             } else if (beliefTerm instanceof Inheritance) {
                 detachmentWithVar(taskSentence, belief, tLink.getIndex(0),
                         memory);
             }
         } else if (taskTerm instanceof Equivalence) {
             if (beliefTerm instanceof Implication) {
                 figure = indexToFigure(bLink, tLink);
                 asymmetricSymmetric(belief, taskSentence, figure, memory);
             } else if (beliefTerm instanceof Equivalence) {
                 figure = indexToFigure(bLink, tLink);
                 symmetricSymmetric(belief, taskSentence, figure, memory);
             } else if (beliefTerm instanceof Inheritance) {
                 detachmentWithVar(taskSentence, belief, tLink.getIndex(0),
                         memory);
             }
         }
     }