opennars: nars.inference.RuleTables.asymmetricSymmetric
static void nars.inference.RuleTables.asymmetricSymmetric (Sentence asym, Sentence sym, int figure, Memory memory) static private
Syllogistic rules whose first premise is on an asymmetric relation, and the second on a symmetric relation.
Parameters
asym The asymmetric premise
sym The symmetric premise
figure The location of the shared term
memory Reference to the memory
Definition at line 362 of file RuleTables.java.
References nars.inference.SyllogisticRules.analogy(), nars.entity.Sentence.cloneContent(), nars.language.Statement.getPredicate(), nars.language.Statement.getSubject(), nars.inference.LocalRules.matchAsymSym(), nars.language.Variable.unify(), nars.io.Symbols.VAR_INDEPENDENT, and nars.io.Symbols.VAR_QUERY.
Referenced by nars.inference.RuleTables.syllogisms().
{
         Statement asymSt = (Statement) asym.cloneContent();
         Statement symSt = (Statement) sym.cloneContent();
         Term t1, t2;
         switch (figure) {
             case 11 :
                 if (Variable.unify(Symbols.VAR_INDEPENDENT,
                         asymSt.getSubject(), symSt.getSubject(), asymSt, symSt)) {
                     t1 = asymSt.getPredicate();
                     t2 = symSt.getPredicate();
                     if (Variable
                             .unify(Symbols.VAR_QUERY, t1, t2, asymSt, symSt)) {
                         LocalRules.matchAsymSym(asym, sym, figure, memory);
                     } else {
                         SyllogisticRules.analogy(t2, t1, asym, sym, figure,
                                 memory);
                     }
                 }
                 break;
             case 12 :
                 if (Variable.unify(Symbols.VAR_INDEPENDENT,
                         asymSt.getSubject(), symSt.getPredicate(), asymSt,
                         symSt)) {
                     t1 = asymSt.getPredicate();
                     t2 = symSt.getSubject();
                     if (Variable
                             .unify(Symbols.VAR_QUERY, t1, t2, asymSt, symSt)) {
                         LocalRules.matchAsymSym(asym, sym, figure, memory);
                     } else {
                         SyllogisticRules.analogy(t2, t1, asym, sym, figure,
                                 memory);
                     }
                 }
                 break;
             case 21 :
                 if (Variable.unify(Symbols.VAR_INDEPENDENT,
                         asymSt.getPredicate(), symSt.getSubject(), asymSt,
                         symSt)) {
                     t1 = asymSt.getSubject();
                     t2 = symSt.getPredicate();
                     if (Variable
                             .unify(Symbols.VAR_QUERY, t1, t2, asymSt, symSt)) {
                         LocalRules.matchAsymSym(asym, sym, figure, memory);
                     } else {
                         SyllogisticRules.analogy(t1, t2, asym, sym, figure,
                                 memory);
                     }
                 }
                 break;
             case 22 :
                 if (Variable.unify(Symbols.VAR_INDEPENDENT,
                         asymSt.getPredicate(), symSt.getPredicate(), asymSt,
                         symSt)) {
                     t1 = asymSt.getSubject();
                     t2 = symSt.getSubject();
                     if (Variable
                             .unify(Symbols.VAR_QUERY, t1, t2, asymSt, symSt)) {
                         LocalRules.matchAsymSym(asym, sym, figure, memory);
                     } else {
                         SyllogisticRules.analogy(t1, t2, asym, sym, figure,
                                 memory);
                     }
                 }
                 break;
         }
     }