opennars: nars.inference.RuleTables.componentAndStatement
static void nars.inference.RuleTables.componentAndStatement (CompoundTerm compound, short index, Statement statement, short side, Memory memory) static private
Inference between a component term (of the current term) and a statement.
Parameters
compound The compound term
index The location of the current term in the compound
statement The statement
side The location of the current term in the statement
memory Reference to the memory
Definition at line 683 of file RuleTables.java.
References nars.inference.StructuralRules.contraposition(), nars.storage.Memory.getCurrentTask(), nars.entity.Task.isStructural(), nars.inference.StructuralRules.structuralDecompose1(), nars.inference.StructuralRules.structuralDecompose2(), and nars.inference.StructuralRules.transformSetRelation().
Referenced by nars.inference.RuleTables.reason().
{
         if (!memory.getCurrentTask().isStructural()) {
             if (statement instanceof Inheritance) {
                 StructuralRules.structuralDecompose1(compound, index,
                         statement, memory);
                 if (!(compound instanceof SetExt)
                         && !(compound instanceof SetInt)) {
                     StructuralRules.structuralDecompose2(statement, memory); // {(C-B)
                                                                                 // -->
                                                                                 // (C-A),
                                                                                 // A
                                                                                 // @
                                                                                 // (C-A)}
                                                                                 // |-
                                                                                 // A
                                                                                 // -->
                                                                                 // B
                 } else {
                     StructuralRules.transformSetRelation(compound, statement,
                             side, memory);
                 }
             } else if (statement instanceof Similarity) {
                 StructuralRules.structuralDecompose2(statement, memory); // {(C-B)
                                                                             // -->
                                                                             // (C-A),
                                                                             // A
                                                                             // @
                                                                             // (C-A)}
                                                                             // |-
                                                                             // A
                                                                             // -->
                                                                             // B
                 if ((compound instanceof SetExt)
                         || (compound instanceof SetInt)) {
                     StructuralRules.transformSetRelation(compound, statement,
                             side, memory);
                 }
             } else if ((statement instanceof Implication)
                     && (compound instanceof Negation)) {
                 StructuralRules.contraposition(statement, memory);
             }
         }
     }