opennars: nars.inference.RuleTables.compoundAndSelf
static void nars.inference.RuleTables.compoundAndSelf (CompoundTerm compound, Term component, boolean compoundTask, Memory memory) static private
Inference between a compound term and a component of it.
Parameters
compound The compound term
component The component term
compoundTask Whether the compound comes from the task
memory Reference to the memory
Definition at line 570 of file RuleTables.java.
References nars.language.CompoundTerm.containComponent(), nars.inference.CompositionalRules.decomposeStatement(), nars.storage.Memory.getCurrentBelief(), nars.storage.Memory.getCurrentTask(), nars.entity.Task.isStructural(), nars.inference.StructuralRules.structuralCompound(), and nars.inference.StructuralRules.transformNegation().
Referenced by nars.inference.RuleTables.compoundAndCompound(), and nars.inference.RuleTables.reason().
{
         if ((compound instanceof Conjunction)
                 || (compound instanceof Disjunction)) {
             if (memory.getCurrentBelief() != null) {
                 CompositionalRules.decomposeStatement(compound, component,
                         compoundTask, memory);
             } else if (compound.containComponent(component)) {
                 StructuralRules.structuralCompound(compound, component,
                         compoundTask, memory);
             }
         } else if ((compound instanceof Negation)
                 && !memory.getCurrentTask().isStructural()) {
             if (compoundTask) {
                 StructuralRules.transformNegation(
                         ((Negation) compound).componentAt(0), memory);
             } else {
                 StructuralRules.transformNegation(compound, memory);
             }
         }
     }