opennars: nars.inference.RuleTables.conditionalDedIndWithVar
static void nars.inference.RuleTables.conditionalDedIndWithVar (Implication conditional, short index, Statement statement, short side, Memory memory) static private
Conditional deduction or induction, with variable unification.
Parameters
conditional The premise that is an Implication with a Conjunction as condition
index The location of the shared term in the condition
statement The second premise that is a statement
side The location of the shared term in the statement
memory Reference to the memory
Definition at line 538 of file RuleTables.java.
References nars.language.CompoundTerm.componentAt(), nars.inference.SyllogisticRules.conditionalDedInd(), nars.language.Statement.getSubject(), nars.language.Variable.unify(), and nars.io.Symbols.VAR_INDEPENDENT.
Referenced by nars.inference.RuleTables.reason().
{
         CompoundTerm condition = (CompoundTerm) conditional.getSubject();
         Term component = condition.componentAt(index);
         Term component2 = null;
         if (statement instanceof Inheritance) {
             component2 = statement;
             side = -1;
         } else if (statement instanceof Implication) {
             component2 = statement.componentAt(side);
         }
         if ((component2 != null)
                 && Variable.unify(Symbols.VAR_INDEPENDENT, component,
                         component2, conditional, statement)) {
             SyllogisticRules.conditionalDedInd(conditional, index, statement,
                     side, memory);
         }
     }