opennars: nars.inference.RuleTables.transformTask
static void nars.inference.RuleTables.transformTask (TaskLink tLink, Memory memory) static
The TaskLink is of type TRANSFORM, and the conclusion is an equivalent transformation.
Parameters
tLink The task link
memory Reference to the memory
Definition at line 738 of file RuleTables.java.
References nars.language.Term.clone(), nars.language.CompoundTerm.componentAt(), nars.entity.Task.getContent(), nars.storage.Memory.getCurrentTask(), nars.entity.TermLink.getIndices(), and nars.inference.StructuralRules.transformProductImage().
Referenced by nars.entity.Concept.fire().
{
         CompoundTerm content = (CompoundTerm) memory.getCurrentTask()
                 .getContent().clone();
         short[] indices = tLink.getIndices();
         Term inh = null;
         if ((indices.length == 2) || (content instanceof Inheritance)) { // <(*,
                                                                             // term,
                                                                             // #)
                                                                             // -->
                                                                             // #>
             inh = content;
         } else if (indices.length == 3) { // <<(*, term, #) --> #> ==> #>
             inh = content.componentAt(indices[0]);
         } else if (indices.length == 4) { // <(&&, <(*, term, #) --> #>, #) ==>
                                             // #>
             Term component = content.componentAt(indices[0]);
             if ((component instanceof Conjunction)
                     && (((content instanceof Implication) && (indices[0] == 0)) || (content instanceof Equivalence))) {
                 inh = ((CompoundTerm) component).componentAt(indices[1]);
             } else {
                 return;
             }
         }
         if (inh instanceof Inheritance) {
             StructuralRules.transformProductImage((Inheritance) inh, content,
                     indices, memory);
         }
     }