opennars: nars.inference.RuleTables.reason
static void nars.inference.RuleTables.reason (TaskLink tLink, TermLink bLink, Memory memory) static
Entry point of the inference engine.
Parameters
tLink The selected TaskLink, which will provide a task
bLink The selected TermLink, which may provide a belief
memory Reference to the memory
Definition at line 45 of file RuleTables.java.
References nars.language.Term.clone(), nars.entity.TermLink.COMPONENT, nars.entity.TermLink.COMPONENT_CONDITION, nars.entity.TermLink.COMPONENT_STATEMENT, nars.inference.RuleTables.componentAndStatement(), nars.entity.TermLink.COMPOUND, nars.entity.TermLink.COMPOUND_CONDITION, nars.entity.TermLink.COMPOUND_STATEMENT, nars.inference.RuleTables.compoundAndCompound(), nars.inference.RuleTables.compoundAndSelf(), nars.inference.RuleTables.compoundAndStatement(), nars.inference.SyllogisticRules.conditionalAna(), nars.inference.SyllogisticRules.conditionalDedInd(), nars.inference.RuleTables.conditionalDedIndWithVar(), nars.inference.SyllogisticRules.detachment(), nars.entity.Concept.getBelief(), nars.entity.Sentence.getContent(), nars.storage.Memory.getCurrentTask(), nars.storage.Memory.getCurrentTerm(), nars.entity.TermLink.getIndex(), nars.entity.Task.getSentence(), nars.entity.TermLink.getTarget(), nars.entity.TermLink.getType(), nars.inference.LocalRules.match(), nars.storage.Memory.noResult(), nars.entity.TermLink.SELF, nars.storage.Memory.setCurrentBelief(), nars.inference.RuleTables.syllogisms(), and nars.storage.Memory.termToConcept().
Referenced by nars.entity.Concept.fire().
{
         Task task = memory.getCurrentTask();
         Sentence taskSentence = task.getSentence();
         Term taskTerm = (Term) taskSentence.getContent().clone(); // cloning for
                                                                     // substitution
         Term beliefTerm = (Term) bLink.getTarget().clone(); // cloning for
                                                             // substitution
         Concept beliefConcept = memory.termToConcept(beliefTerm);
         Sentence belief = null;
         if (beliefConcept != null) {
             belief = beliefConcept.getBelief(task);
         }
         memory.setCurrentBelief(belief); // may be null
         if (belief != null) {
             LocalRules.match(task, belief, memory);
         }
         if (!memory.noResult()) {
             return;
         }
         short tIndex = tLink.getIndex(0);
         short bIndex = bLink.getIndex(0);
         switch (tLink.getType()) { // dispatch first by TaskLink type
             case TermLink.SELF :
                 switch (bLink.getType()) {
                     case TermLink.COMPONENT :
                         compoundAndSelf((CompoundTerm) taskTerm, beliefTerm,
                                 true, memory);
                         break;
                     case TermLink.COMPOUND :
                         compoundAndSelf((CompoundTerm) beliefTerm, taskTerm,
                                 false, memory);
                         break;
                     case TermLink.COMPONENT_STATEMENT :
                         if (belief != null) {
                             SyllogisticRules.detachment(task.getSentence(),
                                     belief, bIndex, memory);
                         }
                         break;
                     case TermLink.COMPOUND_STATEMENT :
                         if (belief != null) {
                             SyllogisticRules.detachment(belief,
                                     task.getSentence(), bIndex, memory);
                         }
                         break;
                     case TermLink.COMPONENT_CONDITION :
                         if (belief != null) {
                             bIndex = bLink.getIndex(1);
                             SyllogisticRules.conditionalDedInd(
                                     (Implication) taskTerm, bIndex, beliefTerm,
                                     tIndex, memory);
                         }
                         break;
                     case TermLink.COMPOUND_CONDITION :
                         if (belief != null) {
                             bIndex = bLink.getIndex(1);
                             SyllogisticRules.conditionalDedInd(
                                     (Implication) beliefTerm, bIndex, taskTerm,
                                     tIndex, memory);
                         }
                         break;
                 }
                 break;
             case TermLink.COMPOUND :
                 switch (bLink.getType()) {
                     case TermLink.COMPOUND :
                         compoundAndCompound((CompoundTerm) taskTerm,
                                 (CompoundTerm) beliefTerm, memory);
                         break;
                     case TermLink.COMPOUND_STATEMENT :
                         compoundAndStatement((CompoundTerm) taskTerm, tIndex,
                                 (Statement) beliefTerm, bIndex, beliefTerm,
                                 memory);
                         break;
                     case TermLink.COMPOUND_CONDITION :
                         if (belief != null) {
                             if (beliefTerm instanceof Implication) {
                                 SyllogisticRules.conditionalDedInd(
                                         (Implication) beliefTerm, bIndex,
                                         taskTerm, -1, memory);
                             } else if (beliefTerm instanceof Equivalence) {
                                 SyllogisticRules.conditionalAna(
                                         (Equivalence) beliefTerm, bIndex,
                                         taskTerm, -1, memory);
                             }
                         }
                         break;
                 }
                 break;
             case TermLink.COMPOUND_STATEMENT :
                 switch (bLink.getType()) {
                     case TermLink.COMPONENT :
                         componentAndStatement(
                                 (CompoundTerm) memory.getCurrentTerm(), bIndex,
                                 (Statement) taskTerm, tIndex, memory);
                         break;
                     case TermLink.COMPOUND :
                         compoundAndStatement((CompoundTerm) beliefTerm, bIndex,
                                 (Statement) taskTerm, tIndex, beliefTerm,
                                 memory);
                         break;
                     case TermLink.COMPOUND_STATEMENT :
                         if (belief != null) {
                             // bIndex = bLink.getIndex(1);
                             syllogisms(tLink, bLink, taskTerm, beliefTerm,
                                     memory);
                         }
                         break;
                     case TermLink.COMPOUND_CONDITION :
                         if (belief != null) {
                             bIndex = bLink.getIndex(1);
                             if (beliefTerm instanceof Implication) {
                                 conditionalDedIndWithVar(
                                         (Implication) beliefTerm, bIndex,
                                         (Statement) taskTerm, tIndex, memory);
                             }
                         }
                         break;
                 }
                 break;
             case TermLink.COMPOUND_CONDITION :
                 switch (bLink.getType()) {
                     case TermLink.COMPOUND_STATEMENT :
                         if (belief != null) {
                             if (taskTerm instanceof Implication)
                                 // TODO maybe put instanceof test within
                                 // conditionalDedIndWithVar()
                                 conditionalDedIndWithVar(
                                         (Implication) taskTerm, tIndex,
                                         (Statement) beliefTerm, bIndex, memory);
                         }
                         break;
                 }
                 break;
         }
     }