opennars: nars.inference.RuleTables.compoundAndStatement
static void nars.inference.RuleTables.compoundAndStatement (CompoundTerm compound, short index, Statement statement, short side, Term beliefTerm, Memory memory) static private
Inference between a compound term and a statement.
Parameters
compound The compound term
index The location of the current term in the compound
statement The statement
side The location of the current term in the statement
beliefTerm The content of the belief
memory Reference to the memory
Definition at line 629 of file RuleTables.java.
References nars.language.CompoundTerm.componentAt(), nars.inference.SyllogisticRules.elimiVarDep(), nars.language.Term.equals(), nars.storage.Memory.getCurrentBelief(), nars.storage.Memory.getCurrentTask(), nars.entity.Task.getSentence(), nars.inference.CompositionalRules.introVarInner(), nars.entity.Sentence.isJudgment(), nars.entity.Task.isStructural(), nars.inference.StructuralRules.structuralCompose1(), nars.inference.StructuralRules.structuralCompose2(), nars.language.Variable.unify(), and nars.io.Symbols.VAR_DEPENDENT.
Referenced by nars.inference.RuleTables.reason().
{
         Term component = compound.componentAt(index);
         Task task = memory.getCurrentTask();
         if (component.getClass() == statement.getClass()) {
             if ((compound instanceof Conjunction)
                     && (memory.getCurrentBelief() != null)) {
                 if (Variable.unify(Symbols.VAR_DEPENDENT, component, statement,
                         compound, statement)) {
                     SyllogisticRules.elimiVarDep(compound, component,
                             statement.equals(beliefTerm), memory);
                 } else if (task.getSentence().isJudgment()) { // &&
                                                                 // !compound.containComponent(component))
                                                                 // {
                     CompositionalRules.introVarInner(statement,
                             (Statement) component, compound, memory);
                 }
             }
         } else {
             if (!task.isStructural() && task.getSentence().isJudgment()) {
                 if (statement instanceof Inheritance) {
                     StructuralRules.structuralCompose1(compound, index,
                             statement, memory);
                     // if (!(compound instanceof SetExt) && !(compound
                     // instanceof SetInt)) {
                     if (!(compound instanceof SetExt
                             || compound instanceof SetInt || compound instanceof Negation)) {
                         StructuralRules.structuralCompose2(compound, index,
                                 statement, side, memory);
                     } // {A --> B, A @ (A&C)} |- (A&C) --> (B&C)
                 } else if ((statement instanceof Similarity)
                         && !(compound instanceof Conjunction)) {
                     StructuralRules.structuralCompose2(compound, index,
                             statement, side, memory);
                 } // {A <-> B, A @ (A&C)} |- (A&C) <-> (B&C)
             }
         }
     }