opennars: nars.inference.RuleTables.detachmentWithVar
static void nars.inference.RuleTables.detachmentWithVar (Sentence originalMainSentence, Sentence subSentence, int index, Memory memory) static private
The detachment rule, with variable unification.
Parameters
originalMainSentence The premise that is an Implication or Equivalence
subSentence The premise that is the subject or predicate of the first one
index The location of the second premise in the first
memory Reference to the memory
Definition at line 495 of file RuleTables.java.
References nars.entity.Sentence.clone(), nars.language.CompoundTerm.componentAt(), nars.inference.SyllogisticRules.detachment(), nars.language.Term.equals(), nars.entity.Sentence.getContent(), nars.storage.Memory.getCurrentBelief(), nars.storage.Memory.getCurrentTask(), nars.language.Statement.getPredicate(), nars.entity.Task.getSentence(), nars.language.Statement.getSubject(), nars.inference.CompositionalRules.introVarInner(), nars.language.Term.isConstant(), nars.entity.Sentence.isJudgment(), nars.language.Variable.unify(), and nars.io.Symbols.VAR_INDEPENDENT.
Referenced by nars.inference.RuleTables.syllogisms().
{
         Sentence mainSentence = (Sentence) originalMainSentence.clone(); // for
                                                                             // substitution
         Statement statement = (Statement) mainSentence.getContent();
         Term component = statement.componentAt(index);
         Term content = subSentence.getContent();
         if ((component instanceof Inheritance)
                 && (memory.getCurrentBelief() != null)) {
             if (component.isConstant()) {
                 SyllogisticRules.detachment(mainSentence, subSentence, index,
                         memory);
             } else if (Variable.unify(Symbols.VAR_INDEPENDENT, component,
                     content, statement, content)) {
                 SyllogisticRules.detachment(mainSentence, subSentence, index,
                         memory);
             } else if ((statement instanceof Implication)
                     && (statement.getPredicate() instanceof Statement)
                     && (memory.getCurrentTask().getSentence().isJudgment())) {
                 Statement s2 = (Statement) statement.getPredicate();
                 if (s2.getSubject().equals(((Statement) content).getSubject())) {
                     CompositionalRules.introVarInner((Statement) content, s2,
                             statement, memory);
                 }
             }
         }
     }