opennars: nars.inference.RuleTables.symmetricSymmetric
static void nars.inference.RuleTables.symmetricSymmetric (Sentence belief, Sentence taskSentence, int figure, Memory memory) static private
Syllogistic rules whose both premises are on the same symmetric relation.
Parameters
belief The premise that comes from a belief
taskSentence The premise that comes from a task
figure The location of the shared term
memory Reference to the memory
Definition at line 442 of file RuleTables.java.
References nars.entity.Sentence.cloneContent(), nars.language.Statement.getPredicate(), nars.language.Statement.getSubject(), nars.inference.SyllogisticRules.resemblance(), nars.language.Variable.unify(), and nars.io.Symbols.VAR_INDEPENDENT.
Referenced by nars.inference.RuleTables.syllogisms().
{
         Statement s1 = (Statement) belief.cloneContent();
         Statement s2 = (Statement) taskSentence.cloneContent();
         switch (figure) {
             case 11 :
                 if (Variable.unify(Symbols.VAR_INDEPENDENT, s1.getSubject(),
                         s2.getSubject(), s1, s2)) {
                     SyllogisticRules.resemblance(s1.getPredicate(),
                             s2.getPredicate(), belief, taskSentence, figure,
                             memory);
                 }
                 break;
             case 12 :
                 if (Variable.unify(Symbols.VAR_INDEPENDENT, s1.getSubject(),
                         s2.getPredicate(), s1, s2)) {
                     SyllogisticRules.resemblance(s1.getPredicate(),
                             s2.getSubject(), belief, taskSentence, figure,
                             memory);
                 }
                 break;
             case 21 :
                 if (Variable.unify(Symbols.VAR_INDEPENDENT, s1.getPredicate(),
                         s2.getSubject(), s1, s2)) {
                     SyllogisticRules.resemblance(s1.getSubject(),
                             s2.getPredicate(), belief, taskSentence, figure,
                             memory);
                 }
                 break;
             case 22 :
                 if (Variable.unify(Symbols.VAR_INDEPENDENT, s1.getPredicate(),
                         s2.getPredicate(), s1, s2)) {
                     SyllogisticRules.resemblance(s1.getSubject(),
                             s2.getSubject(), belief, taskSentence, figure,
                             memory);
                 }
                 break;
         }
     }