/*
The contents of this file are subject to the Mozilla Public License Version 1.1
(the "License"); you may not use this file except in compliance with the License.
You may obtain a copy of the License at http://www.mozilla.org/MPL/

Software distributed under the License is distributed on an "AS IS" basis, WITHOUT
WARRANTY OF ANY KIND, either express or implied. See the License for the specific
language governing rights and limitations under the License.

The Original Code is "SkeletalMuscle.java". Description:
"A model of a skeletal muscle or muscle group.

  @author Bryan Tripp"

The Initial Developer of the Original Code is Bryan Tripp & Centre for Theoretical Neuroscience, University of Waterloo. Copyright (C) 2006-2008. All Rights Reserved.

Alternatively, the contents of this file may be used under the terms of the GNU
Public License license (the GPL License), in which case the provisions of GPL
License are applicable  instead of those above. If you wish to allow use of your
version of this file only under the terms of the GPL License and not to allow
others to use your version of this file under the MPL, indicate your decision
by deleting the provisions above and replace  them with the notice and other
provisions required by the GPL License.  If you do not delete the provisions above,
a recipient may use your version of this file under either the MPL or the GPL License.
*/

/*
 * Created on 30-Nov-2006
 */
package ca.nengo.model.muscle;

import ca.nengo.model.Node;
import ca.nengo.model.Probeable;

/**
 * <p>A model of a skeletal muscle or muscle group.</p>
 *
 * @author Bryan Tripp
 */
public interface SkeletalMuscle extends Node, Probeable {

	/**
	 * GolgiTendonOrgan.ORIGIN_NAME
	 */
	public static final String GTO_ORIGIN = GolgiTendonOrgan.ORIGIN_NAME;

	/**
	 * MuscleSpindle.DYNAMIC_ORIGIN_NAME
	 */
	public static final String DYNAMIC_SPINDLE_ORIGIN = MuscleSpindle.DYNAMIC_ORIGIN_NAME;

	/**
	 * MuscleSpindle.STATIC_ORIGIN_NAME
	 */
	public static final String STATIC_SPINDLE_ORIGIN = MuscleSpindle.STATIC_ORIGIN_NAME;

	/**
	 * excitation
	 */
	public static final String EXCITATION_TERMINATION = "excitation";

	/**
	 * activation
	 */
	public static final String ACTIVATION = "activation";

	/**
	 * force
	 */
	public static final String FORCE = "force";

	/**
	 * length
	 */
	public static final String LENGTH = "length";

	/**
	 * @param length length of the muscle
	 */
	public void setLength(float length);

	/**
	 * @return force generated by the muscle
	 */
	public float getForce();
}
