opennars: nars.storage.Memory.NARSBatch.runInference
void nars.storage.Memory.NARSBatch.runInference (String args[])
non-static equivalent to main(String[]) : run to completion from an input file
Definition at line 761 of file Memory.java.
References nars.storage.Memory.NARSBatch.init(), and nars.storage.Memory.NARSBatch.run().
Referenced by nars.storage.Memory.NARSBatch.main().
{
             init(args);
             run();
         }