opennars: nars.storage.Memory.NARSBatch.run
void nars.storage.Memory.NARSBatch.run ()
Run to completion: repeatedly execute NARS working cycle, until Inputs are Finished, or 1000 steps.
This method is called when the Runnable's thread is started.
Definition at line 806 of file Memory.java.
References nars.storage.Memory.ReasonerBatch.getTime(), nars.storage.Memory.ReasonerBatch.isFinishedInputs(), nars.storage.Memory.NARSBatch.log(), and nars.storage.Memory.ReasonerBatch.tick().
Referenced by nars.storage.Memory.NARSBatch.runInference().
{
             while (true) {
                 log("NARSBatch.run():" + " step " + reasoner.getTime() + " "
                         + reasoner.isFinishedInputs());
                 reasoner.tick();
                 log("NARSBatch.run(): after tick" + " step " + reasoner.getTime()
                         + " " + reasoner.isFinishedInputs());
                 if (reasoner.isFinishedInputs() || reasoner.getTime() == 1000)
                     break;
             }
         }