opennars: nars.entity.Stamp.equals
boolean nars.entity.Stamp.equals (Object that)
Check if two stamps contains the same content.
Parameters
that The Stamp to be compared
Returns
Whether the two have contain the same elements
Definition at line 193 of file Stamp.java.
References nars.entity.Stamp.Stamp(), and nars.entity.Stamp.toSet().
Referenced by nars.entity.Sentence.equals(), nars.entity.Sentence.equivalentTo(), and nars.entity.Concept.processJudgment().
{
         if (!(that instanceof Stamp)) {
             return false;
         }
         Collection<Long> set1 = toSet();
         Collection<Long> set2 = ((Stamp) that).toSet();
         return (set1.containsAll(set2) && set2.containsAll(set1));
     }