opennars: nars.language.Term.getName
String nars.language.Term.getName ()
Reporting the name of the current Term.
Returns
The name of the term as a String
Definition at line 68 of file Term.java.
References nars.language.Term.name.
Referenced by nars.language.Term.compareTo(), nars.entity.Concept.Concept(), nars.entity.Sentence.containQueryVar(), nars.inference.LocalRules.convertedJudgment(), nars.language.Term.equals(), nars.storage.Memory.getConcept(), nars.io.StringParser.parseTask(), nars.language.CompoundTerm.renameVariables(), and nars.entity.TermLink.TermLink().
{
         return name;
     }