opennars: nars.language.Term.equals
boolean nars.language.Term.equals (Object that)
Equal terms have identical name, though not necessarily the same reference.
Parameters
that The Term to be compared with the current Term
Returns
Whether the two Terms are equal
Definition at line 94 of file Term.java.
References nars.language.Term.getName().
Referenced by nars.inference.RuleTables.asymmetricAsymmetric(), nars.inference.RuleTables.compoundAndStatement(), nars.inference.SyllogisticRules.conditionalAna(), nars.inference.SyllogisticRules.conditionalDedInd(), nars.language.Term.containTerm(), nars.inference.LocalRules.convertedJudgment(), nars.inference.CompositionalRules.decomposeCompound(), nars.inference.SyllogisticRules.detachment(), nars.inference.RuleTables.detachmentWithVar(), nars.entity.Sentence.equals(), nars.entity.Sentence.equivalentTo(), nars.language.Variable.findSubstitute(), nars.inference.CompositionalRules.introVarInner(), nars.language.Statement.invalidStatement(), nars.language.DifferenceExt.make(), nars.language.DifferenceInt.make(), nars.language.ImageExt.make(), nars.language.ImageInt.make(), nars.entity.TaskLink.novel(), nars.inference.CompositionalRules.processComposed(), nars.entity.Concept.processQuestion(), nars.language.CompoundTerm.renameVariables(), nars.inference.LocalRules.revisible(), nars.inference.StructuralRules.structuralCompose1(), nars.inference.StructuralRules.structuralCompose2(), nars.inference.StructuralRules.structuralDecompose1(), nars.inference.StructuralRules.structuralDecompose2(), and nars.inference.StructuralRules.transformProductImage().
{
         return (that instanceof Term) && name.equals(((Term) that).getName());
     }