opennars: nars.language.Term.compareTo
final int nars.language.Term.compareTo (Term that)
Check the relative order of two Terms.
Parameters
that The Term to be compared with the current Term
Returns
The same as compareTo as defined on Strings
Definition at line 138 of file Term.java.
References nars.language.Term.getName().
Referenced by nars.language.Equivalence.make(), and nars.language.Similarity.make().
{
         return name.compareTo(that.getName());
     }