/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jurls.core.utils;

import jurls.core.utils.Physics2D;
import java.awt.Color;
import java.awt.Graphics;
import jurls.examples.reinforcementlearning.Connection;
import jurls.examples.reinforcementlearning.Point;

/**
 *
 * @author thorsten
 */
public class PhysicsRenderer extends javax.swing.JPanel {

    public Physics2D physics2D;
    private final float scale;

    public PhysicsRenderer() {
        this(1f);
    }
    
    /**
     * Creates new form PhysicsRenderer
     */
    public PhysicsRenderer(float scale) {
        this.scale = scale;
        initComponents();
    }

    int px(double x) {
        return (int)(scale*x);
    }
    
    int py(double y) {
        return (int)(scale*y);
    }
    
    @Override
    protected void paintComponent(Graphics g) {
        
        g.setColor(Color.black);
        g.fillRect(0, 0, getWidth(), getHeight());

        if (physics2D != null) {
            g.setColor(Color.red);
            g.drawLine(0, py(physics2D.floor), getWidth(), py(physics2D.floor));

            g.setColor(Color.white);
            for (Connection c : physics2D.connections) {
                g.drawLine(px(c.p1.x), py(c.p1.y), px(c.p2.x), px(c.p2.y));
            }

            g.setColor(Color.yellow);
            for (Point p : physics2D.points) {
                g.drawArc( px(p.x)-10, py(p.y)-10, (int)(20), (int)(20), 0, 360);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
