opennars: nars.storage.TermLinkBag.takeOut
TermLink nars.storage.TermLinkBag.takeOut (TaskLink taskLink, long time)
Replace default to prevent repeated inference, by checking TaskLink.
Parameters
taskLink The selected TaskLink
time The current time
Returns
The selected TermLink
Definition at line 59 of file TermLinkBag.java.
References nars.storage.Memory.Parameters.MAX_MATCHED_TERM_LINK, nars.entity.TaskLink.novel(), nars.storage.Bag< TermLink >.putBack(), and nars.storage.Bag< TermLink >.takeOut().
Referenced by nars.entity.Concept.fire().
{
         for (int i = 0; i < Memory.Parameters.MAX_MATCHED_TERM_LINK; i++) {
             TermLink termLink = takeOut();
             if (termLink == null) {
                 return null;
             }
             if (taskLink.novel(termLink, time)) {
                 return termLink;
             }
             putBack(termLink);
         }
         return null;
     }