opennars: nars.inference.TruthFunctions.analogy
static TruthValue nars.inference.TruthFunctions.analogy (TruthValue v1, TruthValue v2) static package
{<S ==> M>, <M <=> P>} |- <S ==> P>
Parameters
v1 Truth value of the first premise
v2 Truth value of the second premise
Returns
Truth value of the conclusion
Definition at line 143 of file TruthFunctions.java.
References nars.inference.UtilityFunctions.and(), nars.entity.TruthValue.getConfidence(), and nars.entity.TruthValue.getFrequency().
Referenced by nars.inference.SyllogisticRules.analogy(), nars.inference.TruthFunctions.anonymousAnalogy(), nars.inference.SyllogisticRules.conditionalAna(), and nars.inference.SyllogisticRules.detachment().
{
         float f1 = v1.getFrequency();
         float f2 = v2.getFrequency();
         float c1 = v1.getConfidence();
         float c2 = v2.getConfidence();
         float f = and(f1, f2);
         float c = and(c1, c2, f2);
         return new TruthValue(f, c);
     }