opennars: nars.inference.TruthFunctions.negation
static TruthValue nars.inference.TruthFunctions.negation (TruthValue v1) static package
{A} |- (–A)
Parameters
v1 Truth value of the premise
Returns
Truth value of the conclusion
Definition at line 54 of file TruthFunctions.java.
References nars.entity.TruthValue.getConfidence(), and nars.entity.TruthValue.getFrequency().
Referenced by nars.inference.CompositionalRules.composeCompound(), nars.inference.TruthFunctions.reduceConjunction(), nars.inference.TruthFunctions.reduceConjunctionNeg(), nars.inference.TruthFunctions.reduceDisjunction(), nars.inference.StructuralRules.structuralCompose1(), nars.inference.StructuralRules.structuralDecompose1(), and nars.inference.StructuralRules.transformNegation().
{
         float f = 1 - v1.getFrequency();
         float c = v1.getConfidence();
         return new TruthValue(f, c);
     }