opennars: nars.inference.LocalRules.convertRelation
static void nars.inference.LocalRules.convertRelation (Memory memory) static private
{<S --> P>} |- <S <-> P> {<S <-> P>} |- <S --> P> Switch between Inheritance/Implication and Similarity/Equivalence
Parameters
memory Reference to the memory
Definition at line 283 of file LocalRules.java.
References nars.inference.TruthFunctions.abduction(), nars.inference.LocalRules.convertedJudgment(), nars.inference.TruthFunctions.deduction(), nars.inference.BudgetFunctions.forward(), nars.entity.Task.getContent(), nars.storage.Memory.getCurrentBelief(), nars.storage.Memory.getCurrentTask(), and nars.entity.Sentence.getTruth().
Referenced by nars.inference.LocalRules.matchAsymSym().
{
         TruthValue truth = memory.getCurrentBelief().getTruth();
         if (((Statement) memory.getCurrentTask().getContent()).isCommutative()) {
             truth = TruthFunctions.abduction(truth, 1.0f);
         } else {
             truth = TruthFunctions.deduction(truth, 1.0f);
         }
         BudgetValue budget = BudgetFunctions.forward(truth, memory);
         convertedJudgment(truth, budget, memory);
     }