opennars: nars.inference.LocalRules.match
static void nars.inference.LocalRules.match (Task task, Sentence belief, Memory memory) static
The task and belief have the same content.
called in RuleTables.reason
Parameters
task The task
belief The belief
memory Reference to the memory
Definition at line 53 of file LocalRules.java.
References nars.language.Term.clone(), nars.entity.Sentence.clone(), nars.entity.Sentence.getContent(), nars.entity.Task.getSentence(), nars.entity.Sentence.isJudgment(), nars.inference.LocalRules.revisible(), nars.inference.LocalRules.revision(), nars.inference.LocalRules.trySolution(), nars.language.Variable.unify(), and nars.io.Symbols.VAR_QUERY.
Referenced by nars.inference.RuleTables.reason().
{
         Sentence sentence = (Sentence) task.getSentence().clone();
         if (sentence.isJudgment()) {
             if (revisible(sentence, belief)) {
                 revision(sentence, belief, true, memory);
             }
         } else if (Variable.unify(Symbols.VAR_QUERY, sentence.getContent(),
                 (Term) belief.getContent().clone())) {
             // trySolution(sentence, belief, task, memory);
             trySolution(belief, task, memory);
         }
     }