opennars: nars.inference.LocalRules.trySolution
static void nars.inference.LocalRules.trySolution (Sentence belief, Task task, Memory memory) static
Check if a Sentence provide a better answer to a Question or Goal.
Parameters
problem The Goal or Question to be answered
belief The proposed answer
task The task to be processed
memory Reference to the memory
Definition at line 118 of file LocalRules.java.
References nars.entity.BudgetValue.aboveThreshold(), nars.storage.Memory.activatedTask(), nars.entity.Task.getBestSolution(), nars.entity.Task.getParentBelief(), nars.entity.Task.getSentence(), nars.entity.Task.isInput(), nars.storage.Memory.report(), nars.entity.Task.setBestSolution(), nars.inference.BudgetFunctions.solutionEval(), and nars.inference.LocalRules.solutionQuality().
Referenced by nars.inference.LocalRules.match(), nars.entity.Concept.processJudgment(), and nars.entity.Concept.processQuestion().
{
         Sentence problem = task.getSentence();
         Sentence oldBest = task.getBestSolution();
         float newQ = solutionQuality(problem, belief);
         if (oldBest != null) {
             float oldQ = solutionQuality(problem, oldBest);
             if (oldQ >= newQ) {
                 return;
             }
         }
         task.setBestSolution(belief);
         if (task.isInput()) { // moved from Sentence
             memory.report(belief, false);
         }
         BudgetValue budget = BudgetFunctions.solutionEval(problem, belief,
                 task, memory);
         if ((budget != null) && budget.aboveThreshold()) {
             memory.activatedTask(budget, belief, task.getParentBelief());
         }
     }