opennars: nars.inference.LocalRules.matchReverse
static void nars.inference.LocalRules.matchReverse (Memory memory) static
The task and belief match reversely.
Parameters
memory Reference to the memory
Definition at line 171 of file LocalRules.java.
References nars.inference.LocalRules.conversion(), nars.storage.Memory.getCurrentBelief(), nars.storage.Memory.getCurrentTask(), nars.entity.Task.getSentence(), nars.inference.LocalRules.inferToSym(), and nars.entity.Sentence.isJudgment().
Referenced by nars.inference.RuleTables.asymmetricAsymmetric().
{
         Task task = memory.getCurrentTask();
         Sentence belief = memory.getCurrentBelief();
         Sentence sentence = task.getSentence();
         if (sentence.isJudgment()) {
             inferToSym((Sentence) sentence, belief, memory);
         } else {
             conversion(memory);
         }
     }