opennars: nars.inference.LocalRules.solutionQuality
static float nars.inference.LocalRules.solutionQuality (Sentence problem, Sentence solution) static
Evaluate the quality of the judgment as a solution to a problem.
Parameters
problem A goal or question
solution The solution to be evaluated
Returns
The quality of the judgment as the solution
Definition at line 148 of file LocalRules.java.
References nars.entity.Sentence.containQueryVar(), nars.language.Term.getComplexity(), nars.entity.TruthValue.getConfidence(), nars.entity.Sentence.getContent(), nars.entity.TruthValue.getExpectation(), and nars.entity.Sentence.getTruth().
Referenced by nars.entity.Concept.evaluation(), nars.inference.BudgetFunctions.solutionEval(), and nars.inference.LocalRules.trySolution().
{
         if (problem == null) {
             return solution.getTruth().getExpectation();
         }
         TruthValue truth = solution.getTruth();
         if (problem.containQueryVar()) { // "yes/no" question
             return truth.getExpectation()
                     / solution.getContent().getComplexity();
         } else { // "what" question or goal
             return truth.getConfidence();
         }
     }