opennars: nars.inference.LocalRules.revisible
static boolean nars.inference.LocalRules.revisible (Sentence s1, Sentence s2) static
Check whether two sentences can be used in revision.
Parameters
s1 The first sentence
s2 The second sentence
Returns
If revision is possible between the two sentences
Definition at line 75 of file LocalRules.java.
References nars.language.Term.equals(), nars.entity.Sentence.getContent(), and nars.entity.Sentence.getRevisible().
Referenced by nars.inference.LocalRules.match(), and nars.entity.Concept.processJudgment().
{
         return (s1.getContent().equals(s2.getContent()) && s1.getRevisible());
     }