opennars: nars.inference.LocalRules.convertedJudgment
static void nars.inference.LocalRules.convertedJudgment (TruthValue newTruth, BudgetValue newBudget, Memory memory) static private
Convert jusgment into different relation.
called in MatchingRules
Parameters
budget The budget value of the new task
truth The truth value of the new task
memory Reference to the memory
Definition at line 306 of file LocalRules.java.
References nars.language.Variable.containVarQuery(), nars.language.Term.equals(), nars.entity.Task.getContent(), nars.entity.Sentence.getContent(), nars.storage.Memory.getCurrentBelief(), nars.storage.Memory.getCurrentTask(), nars.language.Term.getName(), nars.language.Statement.getPredicate(), nars.language.Statement.getSubject(), nars.io.Symbols.JUDGMENT_MARK, nars.language.Statement.make(), and nars.storage.Memory.singlePremiseTask().
Referenced by nars.inference.LocalRules.conversion(), and nars.inference.LocalRules.convertRelation().
{
         Statement content = (Statement) memory.getCurrentTask().getContent();
         Statement beliefContent = (Statement) memory.getCurrentBelief()
                 .getContent();
         Term subjT = content.getSubject();
         Term predT = content.getPredicate();
         Term subjB = beliefContent.getSubject();
         Term predB = beliefContent.getPredicate();
         Term otherTerm;
         if (Variable.containVarQuery(subjT.getName())) {
             otherTerm = (predT.equals(subjB)) ? predB : subjB;
             content = Statement.make(content, otherTerm, predT, memory);
         }
         if (Variable.containVarQuery(predT.getName())) {
             otherTerm = (subjT.equals(subjB)) ? predB : subjB;
             content = Statement.make(content, subjT, otherTerm, memory);
         }
         memory.singlePremiseTask(content, Symbols.JUDGMENT_MARK, newTruth,
                 newBudget);
     }