opennars: nars.inference.LocalRules.inferToSym
static void nars.inference.LocalRules.inferToSym (Sentence judgment1, Sentence judgment2, Memory memory) static private
{<S --> P>,
<P --> S} |- <S <-> p> Produce Similarity/Equivalence from a pair of reversed Inheritance/Implication
Parameters
judgment1 The first premise
judgment2 The second premise
memory Reference to the memory
Definition at line 217 of file LocalRules.java.
References nars.storage.Memory.doublePremiseTask(), nars.inference.BudgetFunctions.forward(), nars.entity.Sentence.getContent(), nars.language.Statement.getPredicate(), nars.language.Statement.getSubject(), nars.entity.Sentence.getTruth(), nars.inference.TruthFunctions.intersection(), nars.language.Equivalence.make(), and nars.language.Similarity.make().
Referenced by nars.inference.LocalRules.matchReverse().
{
         Statement s1 = (Statement) judgment1.getContent();
         Term t1 = s1.getSubject();
         Term t2 = s1.getPredicate();
         Term content;
         if (s1 instanceof Inheritance) {
             content = Similarity.make(t1, t2, memory);
         } else {
             content = Equivalence.make(t1, t2, memory);
         }
         TruthValue value1 = judgment1.getTruth();
         TruthValue value2 = judgment2.getTruth();
         TruthValue truth = TruthFunctions.intersection(value1, value2);
         BudgetValue budget = BudgetFunctions.forward(truth, memory);
         memory.doublePremiseTask(content, truth, budget);
     }