opennars: nars.language.IntersectionExt.make
static Term nars.language.IntersectionExt.make (Term term1, Term term2, Memory memory) static
Try to make a new compound from two components.
Called by the inference rules.
Parameters
term1 The first compoment
term2 The first compoment
memory Reference to the memory
Returns
A compound generated or a term it reduced to
Definition at line 68 of file IntersectionExt.java.
References nars.language.Term.clone(), nars.language.CompoundTerm.cloneComponents(), and nars.language.CompoundTerm.CompoundTerm().
Referenced by nars.inference.CompositionalRules.composeCompound(), nars.language.IntersectionExt.make(), and nars.language.CompoundTerm.make().
{
         TreeSet<Term> set;
         if ((term1 instanceof SetInt) && (term2 instanceof SetInt)) {
             set = new TreeSet<Term>(((CompoundTerm) term1).cloneComponents());
             set.addAll(((CompoundTerm) term2).cloneComponents());        // set union
             return SetInt.make(set, memory);
         }
         if ((term1 instanceof SetExt) && (term2 instanceof SetExt)) {
             set = new TreeSet<Term>(((CompoundTerm) term1).cloneComponents());
             set.retainAll(((CompoundTerm) term2).cloneComponents());     // set intersection
             return SetExt.make(set, memory);
         }
         if (term1 instanceof IntersectionExt) {
             set = new TreeSet<Term>(((CompoundTerm) term1).cloneComponents());
             if (term2 instanceof IntersectionExt) {
                 set.addAll(((CompoundTerm) term2).cloneComponents());
             }               // (&,(&,P,Q),(&,R,S)) = (&,P,Q,R,S)
             else {
                 set.add((Term) term2.clone());
             }               // (&,(&,P,Q),R) = (&,P,Q,R)
         } else if (term2 instanceof IntersectionExt) {
             set = new TreeSet<Term>(((CompoundTerm) term2).cloneComponents());
             set.add((Term) term1.clone());    // (&,R,(&,P,Q)) = (&,P,Q,R)
         } else {
             set = new TreeSet<Term>();
             set.add((Term) term1.clone());
             set.add((Term) term2.clone());
         }
         return make(set, memory);
     }