package com.googlecode.opennars.parser.loan.Loan.Absyn; // Java Package generated by the BNF Converter.

public class BudgetPD extends Budget {
  public final Double double_1, double_2;

  public BudgetPD(Double p1, Double p2) { double_1 = p1; double_2 = p2; }

  public <R,A> R accept(com.googlecode.opennars.parser.loan.Loan.Absyn.Budget.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.googlecode.opennars.parser.loan.Loan.Absyn.BudgetPD) {
      com.googlecode.opennars.parser.loan.Loan.Absyn.BudgetPD x = (com.googlecode.opennars.parser.loan.Loan.Absyn.BudgetPD)o;
      return this.double_1.equals(x.double_1) && this.double_2.equals(x.double_2);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.double_1.hashCode())+this.double_2.hashCode();
  }


}
