package com.googlecode.opennars.parser.loan.Loan.Absyn; // Java Package generated by the BNF Converter.

public class Doc extends Document {
  public final ListSentence listsentence_;

  public Doc(ListSentence p1) { listsentence_ = p1; }

  public <R,A> R accept(com.googlecode.opennars.parser.loan.Loan.Absyn.Document.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.googlecode.opennars.parser.loan.Loan.Absyn.Doc) {
      com.googlecode.opennars.parser.loan.Loan.Absyn.Doc x = (com.googlecode.opennars.parser.loan.Loan.Absyn.Doc)o;
      return this.listsentence_.equals(x.listsentence_);
    }
    return false;
  }

  public int hashCode() {
    return this.listsentence_.hashCode();
  }


}
