package com.googlecode.opennars.parser.loan.Loan.Absyn; // Java Package generated by the BNF Converter.

public class LitURI extends Literal {
  public final URIRef uriref_;

  public LitURI(URIRef p1) { uriref_ = p1; }

  public <R,A> R accept(com.googlecode.opennars.parser.loan.Loan.Absyn.Literal.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.googlecode.opennars.parser.loan.Loan.Absyn.LitURI) {
      com.googlecode.opennars.parser.loan.Loan.Absyn.LitURI x = (com.googlecode.opennars.parser.loan.Loan.Absyn.LitURI)o;
      return this.uriref_.equals(x.uriref_);
    }
    return false;
  }

  public int hashCode() {
    return this.uriref_.hashCode();
  }


}
