package com.googlecode.opennars.parser.loan.Loan.Absyn; // Java Package generated by the BNF Converter.

public abstract class Sentence implements java.io.Serializable {
  public abstract <R,A> R accept(Sentence.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(com.googlecode.opennars.parser.loan.Loan.Absyn.SentPrefix p, A arg);
    public R visit(com.googlecode.opennars.parser.loan.Loan.Absyn.SentImport p, A arg);
    public R visit(com.googlecode.opennars.parser.loan.Loan.Absyn.SentDelay p, A arg);
    public R visit(com.googlecode.opennars.parser.loan.Loan.Absyn.SentOp p, A arg);
    public R visit(com.googlecode.opennars.parser.loan.Loan.Absyn.SentJudge p, A arg);
    public R visit(com.googlecode.opennars.parser.loan.Loan.Absyn.SentQuest p, A arg);
    public R visit(com.googlecode.opennars.parser.loan.Loan.Absyn.SentGoal p, A arg);

  }

}
