package com.googlecode.opennars.parser.loan.Loan.Absyn; // Java Package generated by the BNF Converter.

public class SentPrefix extends Sentence {
  public final NSPrefix nsprefix_;
  public final String urilit_;

  public SentPrefix(NSPrefix p1, String p2) { nsprefix_ = p1; urilit_ = p2; }

  public <R,A> R accept(com.googlecode.opennars.parser.loan.Loan.Absyn.Sentence.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.googlecode.opennars.parser.loan.Loan.Absyn.SentPrefix) {
      com.googlecode.opennars.parser.loan.Loan.Absyn.SentPrefix x = (com.googlecode.opennars.parser.loan.Loan.Absyn.SentPrefix)o;
      return this.nsprefix_.equals(x.nsprefix_) && this.urilit_.equals(x.urilit_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.nsprefix_.hashCode())+this.urilit_.hashCode();
  }


}
