opennars: nars.storage.Memory.workCycle
void nars.storage.Memory.workCycle (long clock)
An atomic working workCycle of the system: process new Tasks, then fire a concept.
Called from Reasoner.tick only
Parameters
clock The current time to be displayed
Definition at line 346 of file Memory.java.
References nars.io.IInferenceRecorder.append(), nars.storage.Memory.getNovelTasks(), nars.storage.Memory.getRecorder(), nars.storage.Memory.noResult(), nars.storage.Memory.processConcept(), nars.storage.Memory.processNewTask(), nars.storage.Memory.processNovelTask(), and nars.storage.Bag< Type extends Item >.refresh().
Referenced by nars.storage.Memory.ReasonerBatch.doTick().
{
         getRecorder().append(" --- " + clock + " ---\n");
         processNewTask();
         if (noResult()) {       // necessary?
             processNovelTask();
         }
         if (noResult()) {       // necessary?
             processConcept();
         }
         getNovelTasks().refresh();
     }