opennars: nars.storage.Memory.activatedTask
void nars.storage.Memory.activatedTask (BudgetValue budget, Sentence sentence, Sentence candidateBelief)
Activated task called in MatchingRules.trySolution and Concept.processGoal.
Parameters
budget The budget value of the new Task
sentence The content of the new Task
candidateBelief The belief to be used in future inference, for forward/backward correspondence
Definition at line 237 of file Memory.java.
References nars.io.IInferenceRecorder.append(), nars.entity.Item.getBudget(), nars.storage.Memory.getCurrentTask(), nars.storage.Memory.getNewTasks(), nars.storage.Memory.getReasoner(), nars.storage.Memory.getRecorder(), nars.entity.Task.getSentence(), nars.storage.Memory.ReasonerBatch.getSilenceValue(), nars.entity.Sentence.isQuestion(), nars.storage.Memory.report(), nars.entity.BudgetValue.summary(), and nars.entity.Task.toString().
Referenced by nars.inference.LocalRules.trySolution().
{
         Task task = new Task(sentence, budget, getCurrentTask(), sentence, candidateBelief);
         getRecorder().append("!!! Activated: " + task.toString() + "\n");
         if (sentence.isQuestion()) {
             float s = task.getBudget().summary();
 //            float minSilent = reasoner.getMainWindow().silentW.value() / 100.0f;
             float minSilent = getReasoner().getSilenceValue().get() / 100.0f;
             if (s > minSilent) {  // only report significant derived Tasks
                 report(task.getSentence(), false);
             }
         }
         getNewTasks().add(task);
     }