opennars: nars.storage.Memory.derivedTask
void nars.storage.Memory.derivedTask (Task task) private
Derived task comes from the inference rules.
Parameters
task the derived task
Definition at line 256 of file Memory.java.
References nars.entity.BudgetValue.aboveThreshold(), nars.io.IInferenceRecorder.append(), nars.entity.Item.getBudget(), nars.storage.Memory.getNewTasks(), nars.storage.Memory.getReasoner(), nars.storage.Memory.getRecorder(), nars.entity.Task.getSentence(), nars.storage.Memory.ReasonerBatch.getSilenceValue(), nars.storage.Memory.report(), and nars.entity.BudgetValue.summary().
Referenced by nars.storage.Memory.doublePremiseTask(), and nars.storage.Memory.singlePremiseTask().
{
         if (task.getBudget().aboveThreshold()) {
             getRecorder().append("!!! Derived: " + task + "\n");
             float budget = task.getBudget().summary();
 //            float minSilent = reasoner.getMainWindow().silentW.value() / 100.0f;
             float minSilent = getReasoner().getSilenceValue().get() / 100.0f;
             if (budget > minSilent) {  // only report significant derived Tasks
                 report(task.getSentence(), false);
             }
             getNewTasks().add(task);
         } else {
             getRecorder().append("!!! Ignored: " + task + "\n");
         }
     }