opennars: nars.storage.Memory.getRecorder
IInferenceRecorder nars.storage.Memory.getRecorder ()
Inference record text to be written into a log file.
Definition at line 111 of file Memory.java.
References nars.storage.Memory.recorder.
Referenced by nars.storage.Memory.activatedTask(), nars.storage.Memory.derivedTask(), nars.entity.Concept.fire(), nars.entity.Concept.getBelief(), nars.storage.Memory.immediateProcess(), nars.storage.Memory.init(), nars.storage.Memory.inputTask(), nars.storage.Memory.processConcept(), nars.storage.Memory.processNewTask(), and nars.storage.Memory.workCycle().
{
         return recorder;
     }