opennars: nars.storage.Memory.Memory
nars.storage.Memory.Memory (ReasonerBatch reasoner)
Create a new memory.
Called in Reasoner.reset only
Parameters
reasoner
Definition at line 82 of file Memory.java.
References nars.storage.Memory.setConcepts(), nars.storage.Memory.setExportStrings(), nars.storage.Memory.setNewTasks(), nars.storage.Memory.setNovelTasks(), nars.storage.Memory.setReasoner(), and nars.storage.Memory.setRecorder().
Referenced by nars.storage.Memory.ReasonerBatch.ReasonerBatch().
{
         this.setReasoner(reasoner);
         setRecorder(new NullInferenceRecorder());
         setConcepts(new ConceptBag(this));
         setNovelTasks(new NovelTaskBag(this));
         setNewTasks(new ArrayList<Task>());
         setExportStrings(new ArrayList<String>());
     }