opennars: nars.storage.Memory.activateConcept
void nars.storage.Memory.activateConcept (Concept c, BudgetStruct b)
Adjust the activation level of a Concept.
called in Concept.insertTaskLink only
Parameters
c the concept to be adjusted
b the new BudgetValue
Definition at line 200 of file Memory.java.
References nars.inference.BudgetFunctions.activate(), nars.storage.Memory.getConcepts(), nars.entity.Item.getKey(), nars.storage.Bag< Type extends Item >.pickOut(), and nars.storage.Bag< Type extends Item >.putBack().
Referenced by nars.entity.Concept.insertTaskLink().
{
         getConcepts().pickOut(c.getKey());
         BudgetFunctions.activate(c, b);
         getConcepts().putBack(c);
     }