opennars: nars.storage.Memory.doublePremiseTask
void nars.storage.Memory.doublePremiseTask (Term newContent, TruthValue newTruth, BudgetValue newBudget, boolean revisible)
Shared final operations by all double-premise rules, called from the rules except StructuralRules.
Parameters
newContent The content of the sentence in task
newTruth The truth value of the sentence in task
newBudget The budget value in task
revisible Whether the sentence is revisible
Definition at line 297 of file Memory.java.
References nars.storage.Memory.derivedTask(), nars.storage.Memory.getCurrentBelief(), nars.storage.Memory.getCurrentTask(), nars.storage.Memory.getNewStamp(), nars.entity.Sentence.getPunctuation(), and nars.entity.Task.getSentence().
{
         if (newContent != null) {
             Sentence taskSentence = getCurrentTask().getSentence();
             Sentence newSentence = new Sentence(newContent, taskSentence.getPunctuation(), newTruth, getNewStamp(), revisible);
             Task newTask = new Task(newSentence, newBudget, getCurrentTask(), getCurrentBelief());
             derivedTask(newTask);
         }
     }