opennars: nars.storage.Memory.getConcept
Concept nars.storage.Memory.getConcept (Term term)
Get the Concept associated to a Term, or create it.
Parameters
term indicating the concept
Returns
an existing Concept, or a new one, or null (TODO bad smell)
Definition at line 176 of file Memory.java.
References nars.storage.Bag< Type extends Item >.get(), nars.storage.Memory.getConcepts(), nars.language.Term.getName(), nars.language.Term.isConstant(), and nars.storage.Bag< Type extends Item >.putIn().
Referenced by nars.entity.Concept.buildTermLinks(), nars.storage.Memory.immediateProcess(), and nars.entity.Concept.linkToTask().
{
         if (!term.isConstant()) {
             return null;
         }
         String n = term.getName();
         Concept concept = getConcepts().get(n);
         if (concept == null) {
             concept = new Concept(term, this); // the only place to make a new Concept
             boolean created = getConcepts().putIn(concept);
             if (!created) {
                 return null;
             }
         }
         return concept;
     }