opennars: nars.storage.Memory.nameToListedTerm
Term nars.storage.Memory.nameToListedTerm (String name)
Get a Term for a given name of a Concept or Operator.
called in StringParser and the make methods of compound terms.
Parameters
name the name of a concept or operator
Returns
a Term or null (if no Concept/Operator has this name)
Definition at line 152 of file Memory.java.
References nars.storage.Bag< Type extends Item >.get(), nars.storage.Memory.getConcepts(), and nars.entity.Concept.getTerm().
Referenced by nars.language.DifferenceExt.make(), nars.language.DifferenceInt.make(), nars.language.Equivalence.make(), nars.language.Implication.make(), nars.language.Similarity.make(), nars.language.Inheritance.make(), nars.language.Product.make(), nars.language.Negation.make(), nars.language.SetInt.make(), nars.language.SetExt.make(), nars.language.Conjunction.make(), nars.language.Disjunction.make(), nars.language.IntersectionInt.make(), nars.language.IntersectionExt.make(), nars.language.ImageExt.make(), nars.language.ImageInt.make(), and nars.io.StringParser.parseTerm().
{
         Concept concept = getConcepts().get(name);
         if (concept != null) {
             return concept.getTerm();
         }
         return null;
     }