opennars: nars.storage.Memory.init
void nars.storage.Memory.init ()
Definition at line 91 of file Memory.java.
References nars.io.IInferenceRecorder.append(), nars.storage.Memory.getConcepts(), nars.storage.Memory.getExportStrings(), nars.storage.Memory.getNewTasks(), nars.storage.Memory.getNovelTasks(), nars.storage.Memory.getReasoner(), nars.storage.Memory.getRecorder(), nars.storage.Bag< Type extends Item >.init(), and nars.storage.Memory.ReasonerBatch.initTimer().
Referenced by nars.storage.Memory.ReasonerBatch.reset().
{
         getConcepts().init();
         getNovelTasks().init();
         getNewTasks().clear();
         getExportStrings().clear();
 //      reasoner.getMainWindow().initTimer();
         getReasoner().initTimer();
         getRecorder().append("\n-----RESET-----\n");
     }