opennars: nars.storage.Memory.inputTask
void nars.storage.Memory.inputTask (Task task)
Input task processing.
Invoked by the outside or inside environment. Outside: StringParser (input); Inside: Operator (feedback). Input tasks with low priority are ignored, and the others are put into task buffer.
Parameters
task The input task
Definition at line 218 of file Memory.java.
References nars.entity.BudgetValue.aboveThreshold(), nars.io.IInferenceRecorder.append(), nars.entity.Item.getBudget(), nars.storage.Memory.getNewTasks(), nars.storage.Memory.getRecorder(), nars.entity.Task.getSentence(), and nars.storage.Memory.report().
Referenced by nars.storage.Memory.ReasonerBatch.textInputLine().
{
         if (task.getBudget().aboveThreshold()) {
             getRecorder().append("!!! Perceived: " + task + "\n");
             report(task.getSentence(), true);    // report input
             getNewTasks().add(task);       // wait to be processed in the next workCycle
         } else {
             getRecorder().append("!!! Neglected: " + task + "\n");
         }
     }