opennars: nars.storage.Memory.taskBuffersStartPlay
void nars.storage.Memory.taskBuffersStartPlay (BagObserver bagObserver, String s)
Display new tasks, called from MainWindow.
see conceptsStartPlay(BagObserver, String)
Parameters
bagObserver
s the window title
Definition at line 449 of file Memory.java.
References nars.storage.Bag< Type extends Item >.addBagObserver(), nars.storage.Memory.getNovelTasks(), and nars.storage.BagObserver.setBag().
{
         bagObserver.setBag(getNovelTasks());
         getNovelTasks().addBagObserver(bagObserver, s);
     }