opennars: nars.storage.Memory.toString
String nars.storage.Memory.toString ()
Definition at line 492 of file Memory.java.
References nars.storage.Memory.getConcepts(), nars.storage.Memory.getCurrentBelief(), nars.storage.Memory.getCurrentBeliefLink(), nars.storage.Memory.getCurrentTask(), nars.storage.Memory.getNewTasks(), nars.storage.Memory.getNovelTasks(), nars.storage.Memory.toStringIfNotNull(), and nars.storage.Memory.toStringLongIfNotNull().
Referenced by nars.storage.Memory.ReasonerBatch.toString().
{
         return toStringLongIfNotNull(getConcepts(), "concepts")
                 + toStringLongIfNotNull(getNovelTasks(), "novelTasks")
                 + toStringIfNotNull(getNewTasks(), "newTasks")
                 + toStringLongIfNotNull(getCurrentTask(), "currentTask")
                 + toStringLongIfNotNull(getCurrentBeliefLink(), "currentBeliefLink")
                 + toStringIfNotNull(getCurrentBelief(), "currentBelief");
     }