opennars: nars.storage.Memory.doublePremiseTask
void nars.storage.Memory.doublePremiseTask (Term newContent, TruthValue newTruth, BudgetValue newBudget)
Shared final operations by all double-premise rules, called from the rules except StructuralRules.
Parameters
newContent The content of the sentence in task
newTruth The truth value of the sentence in task
newBudget The budget value in task
Definition at line 280 of file Memory.java.
References nars.storage.Memory.derivedTask(), nars.storage.Memory.getCurrentBelief(), nars.storage.Memory.getCurrentTask(), and nars.storage.Memory.getNewStamp().
Referenced by nars.inference.SyllogisticRules.abdIndCom(), nars.inference.SyllogisticRules.analogy(), nars.inference.SyllogisticRules.conditionalAbd(), nars.inference.SyllogisticRules.conditionalAna(), nars.inference.SyllogisticRules.conditionalDedInd(), nars.inference.CompositionalRules.decomposeCompound(), nars.inference.CompositionalRules.decomposeStatement(), nars.inference.SyllogisticRules.dedExe(), nars.inference.SyllogisticRules.detachment(), nars.inference.SyllogisticRules.elimiVarDep(), nars.inference.LocalRules.inferToAsym(), nars.inference.LocalRules.inferToSym(), nars.inference.CompositionalRules.introVarInner(), nars.inference.CompositionalRules.introVarOuter(), nars.inference.CompositionalRules.processComposed(), nars.inference.SyllogisticRules.resemblance(), and nars.inference.LocalRules.revision().
{
         if (newContent != null) {
             Sentence newSentence = new Sentence(newContent, getCurrentTask().getSentence().getPunctuation(), newTruth, getNewStamp());
             Task newTask = new Task(newSentence, newBudget, getCurrentTask(), getCurrentBelief());
             derivedTask(newTask);
         }
     }