opennars: nars.storage.Memory.processNovelTask
void nars.storage.Memory.processNovelTask () private
Select a novel task to process.
Definition at line 387 of file Memory.java.
References nars.storage.Memory.getNovelTasks(), nars.storage.Memory.immediateProcess(), and nars.storage.Bag< Type extends Item >.takeOut().
Referenced by nars.storage.Memory.workCycle().
{
         Task task = getNovelTasks().takeOut();       // select a task from novelTasks
         if (task != null) {
             immediateProcess(task);
         }
     }