opennars: nars.storage.Memory.report
void nars.storage.Memory.report (Sentence sentence, boolean input)
Display input/output sentence in the output channels.
The only place to add Objects into exportStrings. Currently only Strings are added, though in the future there can be outgoing Tasks; also if exportStrings is empty display the current value of timer (exportStrings is emptied in ReasonerBatch#doTick() - TODO fragile mechanism)
Parameters
sentence the sentence to be displayed
input whether the task is input
Definition at line 464 of file Memory.java.
References nars.storage.Memory.ReasonerBatch.DEBUG, nars.storage.Memory.getExportStrings(), nars.storage.Memory.getReasoner(), nars.storage.Memory.getTime(), nars.entity.Sentence.toStringBrief(), and nars.storage.Memory.ReasonerBatch.updateTimer().
Referenced by nars.storage.Memory.activatedTask(), nars.storage.Memory.derivedTask(), nars.storage.Memory.inputTask(), and nars.inference.LocalRules.trySolution().
{
         if (ReasonerBatch.DEBUG) {
             System.out.println("// report( clock " + getReasoner().getTime()
                     + ", input " + input
                     + ", timer " + getReasoner().getTimer()
                     + ", Sentence " + sentence
                     + ", exportStrings " + getExportStrings());
             System.out.flush();
         }
         if (getExportStrings().isEmpty()) {
 //          long timer = reasoner.getMainWindow().updateTimer();
             long timer = getReasoner().updateTimer();
             if (timer > 0) {
                 getExportStrings().add(String.valueOf(timer));
             }
         }
         String s;
         if (input) {
             s = "  IN: ";
         } else {
             s = " OUT: ";
         }
         s += sentence.toStringBrief();
         getExportStrings().add(s);
     }