opennars: nars.storage.Memory.immediateProcess
void nars.storage.Memory.immediateProcess (Task task) private
Immediate processing of a new task, in constant time Local processing, in one concept only.
Parameters
task the task to be accepted
Definition at line 414 of file Memory.java.
References nars.io.IInferenceRecorder.append(), nars.entity.Concept.directProcess(), nars.storage.Memory.getConcept(), nars.entity.Task.getContent(), nars.storage.Memory.getCurrentConcept(), nars.storage.Memory.getCurrentTerm(), nars.storage.Memory.getRecorder(), nars.storage.Memory.setCurrentConcept(), nars.storage.Memory.setCurrentTask(), and nars.storage.Memory.setCurrentTerm().
Referenced by nars.storage.Memory.processNewTask(), and nars.storage.Memory.processNovelTask().
{
         setCurrentTask(task); // one of the two places where this variable is set
         getRecorder().append("!!! Insert: " + task + "\n");
         setCurrentTerm(task.getContent());
         setCurrentConcept(getConcept(getCurrentTerm()));
         if (getCurrentConcept() != null) {
             getCurrentConcept().directProcess(task);
         }
     }