opennars: nars.storage.Memory.getNovelTasks
NovelTaskBag nars.storage.Memory.getNovelTasks ()
New tasks with novel composed terms, for delayed and selective processing.
Definition at line 553 of file Memory.java.
References nars.storage.Memory.novelTasks.
Referenced by nars.storage.Memory.init(), nars.storage.Memory.processNewTask(), nars.storage.Memory.processNovelTask(), nars.storage.Memory.taskBuffersStartPlay(), nars.storage.Memory.toString(), and nars.storage.Memory.workCycle().
{
         return novelTasks;
     }