opennars: nars.storage.Memory.processConcept
void nars.storage.Memory.processConcept () private
Select a concept to fire.
Definition at line 397 of file Memory.java.
References nars.io.IInferenceRecorder.append(), nars.entity.Concept.fire(), nars.storage.Memory.getConcepts(), nars.storage.Memory.getCurrentConcept(), nars.storage.Memory.getCurrentTerm(), nars.storage.Memory.getRecorder(), nars.storage.Bag< Type extends Item >.putBack(), nars.storage.Memory.setCurrentConcept(), and nars.storage.Memory.setCurrentTerm().
Referenced by nars.storage.Memory.workCycle().
{
         setCurrentConcept(getConcepts().takeOut());
         if (getCurrentConcept() != null) {
             setCurrentTerm(getCurrentConcept().getTerm());
             getRecorder().append(" * Selected Concept: " + getCurrentTerm() + "\n");
             getConcepts().putBack(getCurrentConcept());   // current Concept remains in the bag all the time
             getCurrentConcept().fire();              // a working workCycle
         }
     }