opennars: nars.storage.Memory.processNewTask
void nars.storage.Memory.processNewTask () private
Process the newTasks accumulated in the previous workCycle, accept input ones and those that corresponding to existing concepts, plus one from the buffer.
Definition at line 363 of file Memory.java.
References nars.io.IInferenceRecorder.append(), nars.storage.Memory.Parameters.DEFAULT_CREATION_EXPECTATION, nars.entity.Task.getContent(), nars.entity.TruthValue.getExpectation(), nars.storage.Memory.getNewTasks(), nars.storage.Memory.getNovelTasks(), nars.storage.Memory.getRecorder(), nars.entity.Task.getSentence(), nars.entity.Sentence.getTruth(), nars.storage.Memory.immediateProcess(), nars.entity.Task.isInput(), nars.entity.Sentence.isJudgment(), nars.storage.Bag< Type extends Item >.putIn(), and nars.storage.Memory.termToConcept().
Referenced by nars.storage.Memory.workCycle().
{
         Task task;
         int counter = getNewTasks().size();  // don't include new tasks produced in the current workCycle
         while (counter-- > 0) {
             task = getNewTasks().remove(0);
             if (task.isInput() || (termToConcept(task.getContent()) != null)) { // new input or existing concept
                 immediateProcess(task);
             } else {
                 Sentence s = task.getSentence();
                 if (s.isJudgment()) {
                     double d = s.getTruth().getExpectation();
                     if (d > Parameters.DEFAULT_CREATION_EXPECTATION) {
                         getNovelTasks().putIn(task);    // new concept formation
                     } else {
                         getRecorder().append("!!! Neglected: " + task + "\n");
                     }
                 }
             }
         }
     }