opennars: nars.language.ImageInt.make
static Term nars.language.ImageInt.make (ImageInt oldImage, Term component, short index, Memory memory) static
Try to make an Image from an existing Image and a component.
Called by the inference rules.
Parameters
oldImage The existing Image
component The component to be added into the component list
index The index of the place-holder in the new Image
memory Reference to the memory
Returns
A compound generated or a term it reduced to
Definition at line 129 of file ImageInt.java.
References nars.language.CompoundTerm.cloneComponents(), nars.language.ImageInt.getRelationIndex(), and nars.language.ImageInt.make().
{
         ArrayList<Term> argList = oldImage.cloneComponents();
         int oldIndex = oldImage.getRelationIndex();
         Term relation = argList.get(oldIndex);
         argList.set(oldIndex, component);
         argList.set(index, relation);
         return make(argList, index, memory);
     }