opennars: nars.language.ImageInt.make
static Term nars.language.ImageInt.make (Product product, Term relation, short index, Memory memory) static
Try to make an Image from a Product and a relation.
Called by the inference rules.
Parameters
product The product
relation The relation
index The index of the place-holder
memory Reference to the memory
Returns
A compound generated or a term it reduced to
Definition at line 104 of file ImageInt.java.
References nars.language.CompoundTerm.cloneComponents(), nars.language.CompoundTerm.componentAt(), nars.language.Term.equals(), nars.language.ImageInt.make(), and nars.language.CompoundTerm.size().
{
         if (relation instanceof Product) {
             Product p2 = (Product) relation;
             if ((product.size() == 2) && (p2.size() == 2)) {
                 if ((index == 0) && product.componentAt(1).equals(p2.componentAt(1))) {// (\,_,(*,a,b),b) is reduced to a
                     return p2.componentAt(0);
                 }
                 if ((index == 1) && product.componentAt(0).equals(p2.componentAt(0))) {// (\,(*,a,b),a,_) is reduced to b
                     return p2.componentAt(1);
                 }
             }
         }
         ArrayList<Term> argument = product.cloneComponents();
         argument.set(index, relation);
         return make(argument, index, memory);
     }