opennars: nars.io.StringParser.parseCompoundTerm
static Term nars.io.StringParser.parseCompoundTerm (String s0, Memory memory) throws InvalidInputException static private
Parse a String to create a CompoundTerm.
Returns
the Term generated from the String
Parameters
s0 The String to be parsed
Exceptions
nars.io.StringParser.InvalidInputException the String cannot be parsed into a Term
Definition at line 347 of file StringParser.java.
References nars.io.Symbols.ARGUMENT_SEPARATOR, nars.language.CompoundTerm.isOperator(), nars.language.CompoundTerm.make(), and nars.io.StringParser.parseArguments().
Referenced by nars.io.StringParser.parseTerm().
{
         String s = s0.trim();
         int firstSeparator = s.indexOf(ARGUMENT_SEPARATOR);
         String op = s.substring(0, firstSeparator).trim();
         if (!CompoundTerm.isOperator(op)) {
             throw new InvalidInputException("unknown operator: " + op);
         }
         ArrayList<Term> arg = parseArguments(s.substring(firstSeparator + 1) + ARGUMENT_SEPARATOR, memory);
         Term t = CompoundTerm.make(op, arg, memory);
         if (t == null) {
             throw new InvalidInputException("invalid compound term");
         }
         return t;
     }