opennars: nars.io.StringParser.isCloser
static boolean nars.io.StringParser.isCloser (String s, int i) static private
Check CompoundTerm closer symbol.
Returns
if the given String is a closer symbol
Parameters
s The String to be checked
i The starting index
Definition at line 461 of file StringParser.java.
References nars.io.Symbols.COMPOUND_TERM_CLOSER, nars.language.Statement.isRelation(), nars.io.Symbols.SET_EXT_CLOSER, nars.io.Symbols.SET_INT_CLOSER, and nars.io.Symbols.STATEMENT_CLOSER.
Referenced by nars.io.StringParser.nextSeparator(), and nars.io.StringParser.topRelation().
{
         char c = s.charAt(i);
         boolean b = (c == COMPOUND_TERM_CLOSER) ||
                 (c == SET_EXT_CLOSER) ||
                 (c == SET_INT_CLOSER) ||
                 (c == STATEMENT_CLOSER);
         if (!b) {
             return false;
         }
         if (i >= 2 && Statement.isRelation(s.substring(i - 2, i + 1))) {
             return false;
         }
         return true;
     }