opennars: nars.io.StringParser.parseTerm
static Term nars.io.StringParser.parseTerm (String s0, Memory memory) static
Top-level method that parse a Term in general, which may recursively call itself.
There are 5 valid cases:
(Op, A1, ..., An) is a CompoundTerm if Op is a built-in operator
{A1, ..., An} is an SetExt;
[A1, ..., An] is an SetInt;
<T1 re="" t2>=""> is a Statement (including higher-order Statement);
otherwise it is a simple term.
Parameters
s0 the String to be parsed
memory Reference to the memory
Returns
the Term generated from the String
Definition at line 241 of file StringParser.java.
References nars.io.Symbols.ARGUMENT_SEPARATOR, nars.io.Symbols.COMPOUND_TERM_CLOSER, nars.io.Symbols.COMPOUND_TERM_OPENER, nars.language.SetInt.make(), nars.language.SetExt.make(), nars.storage.Memory.nameToListedTerm(), nars.io.StringParser.parseArguments(), nars.io.StringParser.parseAtomicTerm(), nars.io.StringParser.parseCompoundTerm(), nars.io.StringParser.parseStatement(), nars.io.Symbols.SET_EXT_CLOSER, nars.io.Symbols.SET_EXT_OPENER, nars.io.Symbols.SET_INT_CLOSER, nars.io.Symbols.SET_INT_OPENER, nars.io.StringParser.showWarning(), nars.io.Symbols.STATEMENT_CLOSER, and nars.io.Symbols.STATEMENT_OPENER.
Referenced by nars.io.StringParser.parseArguments(), nars.io.StringParser.parseStatement(), and nars.io.StringParser.parseTask().
{
         String s = s0.trim();
         try {
             if (s.length() == 0) {
                 throw new InvalidInputException("missing content");
             }
             Term t = memory.nameToListedTerm(s);    // existing constant or operator
             if (t != null) {
                 return t;
             }                           // existing Term
             int index = s.length() - 1;
             char first = s.charAt(0);
             char last = s.charAt(index);
             switch (first) {
                 case COMPOUND_TERM_OPENER:
                     if (last == COMPOUND_TERM_CLOSER) {
                         return parseCompoundTerm(s.substring(1, index), memory);
                     } else {
                         throw new InvalidInputException("missing CompoundTerm closer");
                     }
                 case SET_EXT_OPENER:
                     if (last == SET_EXT_CLOSER) {
                         return SetExt.make(parseArguments(s.substring(1, index) + ARGUMENT_SEPARATOR, memory), memory);
                     } else {
                         throw new InvalidInputException("missing ExtensionSet closer");
                     }
                 case SET_INT_OPENER:
                     if (last == SET_INT_CLOSER) {
                         return SetInt.make(parseArguments(s.substring(1, index) + ARGUMENT_SEPARATOR, memory), memory);
                     } else {
                         throw new InvalidInputException("missing IntensionSet closer");
                     }
                 case STATEMENT_OPENER:
                     if (last == STATEMENT_CLOSER) {
                         return parseStatement(s.substring(1, index), memory);
                     } else {
                         throw new InvalidInputException("missing Statement closer");
                     }
                 default:
                     return parseAtomicTerm(s);
             }
         } catch (InvalidInputException e) {
             String message = " !!! INVALID INPUT: parseTerm: " + s + " --- " + e.getMessage();
             System.out.println(message);
             showWarning(message);
         }
         return null;
     }