opennars: nars.io.StringParser.topRelation
static int nars.io.StringParser.topRelation (String s) static private
locate the top-level relation in a statement
Returns
the index of the top-level relation
Parameters
s The String to be parsed
Definition at line 416 of file StringParser.java.
References nars.io.StringParser.isCloser(), nars.io.StringParser.isOpener(), and nars.language.Statement.isRelation().
Referenced by nars.io.StringParser.parseStatement().
                                              {      // need efficiency improvement
         int levelCounter = 0;
         int i = 0;
         while (i < s.length() - 3) {    // don't need to check the last 3 characters
             if ((levelCounter == 0) && (Statement.isRelation(s.substring(i, i + 3)))) {
                 return i;
             }
             if (isOpener(s, i)) {
                 levelCounter++;
             } else if (isCloser(s, i)) {
                 levelCounter--;
             }
             i++;
         }
         return -1;
     }