opennars: nars.io.StringParser.parseArguments
static ArrayList<Term> nars.io.StringParser.parseArguments (String s0, Memory memory) throws InvalidInputException static private
Parse a String into the argument get of a CompoundTerm.
Returns
the arguments in an ArrayList
Parameters
s0 The String to be parsed
Exceptions
nars.io.StringParser.InvalidInputException the String cannot be parsed into an argument get
Definition at line 368 of file StringParser.java.
References nars.io.StringParser.nextSeparator(), and nars.io.StringParser.parseTerm().
Referenced by nars.io.StringParser.parseCompoundTerm(), and nars.io.StringParser.parseTerm().
{
         String s = s0.trim();
         ArrayList<Term> list = new ArrayList<Term>();
         int start = 0;
         int end = 0;
         Term t;
         while (end < s.length() - 1) {
             end = nextSeparator(s, start);
             t = parseTerm(s.substring(start, end), memory);     // recursive call
             list.add(t);
             start = end + 1;
         }
         if (list.isEmpty()) {
             throw new InvalidInputException("null argument");
         }
         return list;
     }