opennars: nars.io.StringParser.parseTask
static Task nars.io.StringParser.parseTask (String s, Memory memory, long time) static
Enter a new Task in String into the memory, called from InputWindow or locally.
Parameters
s the single-line input String
memory Reference to the memory
time The current time
Returns
An experienced task
Definition at line 86 of file StringParser.java.
References nars.language.Variable.containVarDep(), nars.io.StringParser.getBudgetString(), nars.language.Term.getName(), nars.io.StringParser.getTruthString(), nars.io.StringParser.parseBudget(), nars.io.StringParser.parseTerm(), nars.io.StringParser.parseTruth(), and nars.io.StringParser.showWarning().
Referenced by nars.io.StringParser.parseExperience().
{
         StringBuffer buffer = new StringBuffer(s);
         Task task = null;
         try {
             String budgetString = getBudgetString(buffer);
             String truthString = getTruthString(buffer);
             String str = buffer.toString().trim();
             int last = str.length() - 1;
             char punc = str.charAt(last);
             Stamp stamp = new Stamp(time);
             TruthValue truth = parseTruth(truthString, punc);
             Term content = parseTerm(str.substring(0, last), memory);
 //            if (content instanceof CompoundTerm) { // all top-level compound terms are assumed to be constant
 //                ((CompoundTerm) content).setConstant(true);
 //            }
 //            Sentence sentence = Sentence.make(content, punc, truth, stamp);
             Sentence sentence = new Sentence(content, punc, truth, stamp);
             if ((content instanceof Conjunction) && Variable.containVarDep(content.getName())) {
                 sentence.setRevisible(false);
             }
 //            if (sentence == null) {
 //                throw new InvalidInputException("invalid sentence");
 //            }
 //            sentence.setInput();
             BudgetValue budget = parseBudget(budgetString, punc, truth);
             task = new Task(sentence, budget);
         } catch (InvalidInputException e) {
             String message = " !!! INVALID INPUT: parseTask: " + buffer + " --- " + e.getMessage();
             System.out.println(message);
             showWarning(message);
         }
         return task;
     }