opennars: nars.io.StringParser.isOpener
static boolean nars.io.StringParser.isOpener (String s, int i) static private
Check CompoundTerm opener symbol.
Returns
if the given String is an opener symbol
Parameters
s The String to be checked
i The starting index
Definition at line 440 of file StringParser.java.
References nars.io.Symbols.COMPOUND_TERM_OPENER, nars.language.Statement.isRelation(), nars.io.Symbols.SET_EXT_OPENER, nars.io.Symbols.SET_INT_OPENER, and nars.io.Symbols.STATEMENT_OPENER.
Referenced by nars.io.StringParser.nextSeparator(), and nars.io.StringParser.topRelation().
{
         char c = s.charAt(i);
         boolean b = (c == COMPOUND_TERM_OPENER) ||
                 (c == SET_EXT_OPENER) ||
                 (c == SET_INT_OPENER) ||
                 (c == STATEMENT_OPENER);
         if (!b) {
             return false;
         }
         if (i + 3 <= s.length() && Statement.isRelation(s.substring(i, i + 3))) {
             return false;
         }
         return true;
     }