opennars: nars.io.StringParser.parseStatement
static Statement nars.io.StringParser.parseStatement (String s0, Memory memory) throws InvalidInputException static private
Parse a String to create a Statement.
Returns
the Statement generated from the String
Parameters
s0 The input String to be parsed
Exceptions
nars.io.StringParser.InvalidInputException the String cannot be parsed into a Term
Definition at line 325 of file StringParser.java.
References nars.language.Statement.make(), nars.io.StringParser.parseTerm(), and nars.io.StringParser.topRelation().
Referenced by nars.io.StringParser.parseTerm().
{
         String s = s0.trim();
         int i = topRelation(s);
         if (i < 0) {
             throw new InvalidInputException("invalid statement");
         }
         String relation = s.substring(i, i + 3);
         Term subject = parseTerm(s.substring(0, i), memory);
         Term predicate = parseTerm(s.substring(i + 3), memory);
         Statement t = Statement.make(relation, subject, predicate, memory);
         if (t == null) {
             throw new InvalidInputException("invalid statement");
         }
         return t;
     }