opennars: nars.entity.Concept.insertTaskLink
void nars.entity.Concept.insertTaskLink (TaskLink taskLink)
Insert a TaskLink into the TaskLink bag.
called only from Memory.continuedProcess
Parameters
taskLink The termLink to be inserted
Definition at line 269 of file Concept.java.
References nars.storage.Memory.activateConcept(), nars.entity.Item.getBudget(), and nars.storage.Bag< Type extends Item >.putIn().
Referenced by nars.entity.Concept.linkToTask().
{
         BudgetValue taskBudget = taskLink.getBudget();
         taskLinks.putIn(taskLink);
         memory.activateConcept(this, taskBudget);
     }