opennars: nars.entity.Concept.fire
void nars.entity.Concept.fire ()
An atomic step in a concept, only called in Memory# processConcept.
Definition at line 404 of file Concept.java.
References nars.storage.Memory.getRecorder(), nars.entity.TaskLink.getTargetTask(), nars.storage.Memory.getTime(), nars.entity.TermLink.getType(), nars.storage.Memory.Parameters.MAX_REASONED_TERM_LINK, nars.storage.Memory.noResult(), nars.storage.Bag< Type extends Item >.putBack(), nars.inference.RuleTables.reason(), nars.storage.Memory.setCurrentBeliefLink(), nars.storage.Memory.setCurrentTask(), nars.storage.Memory.setCurrentTaskLink(), nars.storage.TermLinkBag.takeOut(), nars.storage.Bag< Type extends Item >.takeOut(), nars.entity.TermLink.TRANSFORM, and nars.inference.RuleTables.transformTask().
Referenced by nars.storage.Memory.processConcept().
{
         TaskLink currentTaskLink = taskLinks.takeOut();
         if (currentTaskLink == null) {
             return;
         }
         memory.setCurrentTaskLink(currentTaskLink);
         memory.setCurrentBeliefLink(null);
         memory.getRecorder().append(" * Selected TaskLink: " + currentTaskLink + "\n");
         Task task = currentTaskLink.getTargetTask();
         memory.setCurrentTask(task);  // one of the two places where this variable is set
         if (currentTaskLink.getType() == TermLink.TRANSFORM) {
             RuleTables.transformTask(currentTaskLink, memory);  // to turn this into structural inference as below?
         }
         int termLinkCount = Memory.Parameters.MAX_REASONED_TERM_LINK;
         while (memory.noResult() && (termLinkCount > 0)) {
             TermLink termLink = termLinks.takeOut(currentTaskLink, memory.getTime());
             if (termLink != null) {
                 memory.getRecorder().append(" * Selected TermLink: " + termLink + "\n");
                 memory.setCurrentBeliefLink(termLink);
                 RuleTables.reason(currentTaskLink, termLink, memory);
                 termLinks.putBack(termLink);
                 termLinkCount--;
             } else {
                 termLinkCount = 0;
             }
         }
         taskLinks.putBack(currentTaskLink);
     }