opennars: nars.entity.Concept.processQuestion
float nars.entity.Concept.processQuestion (Task task)
To answer a question by existing beliefs.
Parameters
task The task to be processed
Returns
Whether to continue the processing of the task
Definition at line 144 of file Concept.java.
References nars.language.Term.equals(), nars.entity.Concept.evaluation(), nars.entity.Sentence.getContent(), nars.entity.TruthValue.getExpectation(), nars.entity.Task.getSentence(), nars.entity.Sentence.getTruth(), nars.storage.Memory.Parameters.MAXIMUM_QUESTIONS_LENGTH, and nars.inference.LocalRules.trySolution().
Referenced by nars.entity.Concept.directProcess().
{
         Sentence ques = task.getSentence();
         boolean newQuestion = true;
         if (questions != null) {
             for (Task t : questions) {
                 Sentence q = t.getSentence();
                 if (q.getContent().equals(ques.getContent())) {
                     ques = q;
                     newQuestion = false;
                     break;
                 }
             }
         }
         if (newQuestion) {
             questions.add(task);
         }
         if (questions.size() > Memory.Parameters.MAXIMUM_QUESTIONS_LENGTH) {
             questions.remove(0);    // FIFO
         }
         Sentence newAnswer = evaluation(ques, beliefs);
         if (newAnswer != null) {
 //            LocalRules.trySolution(ques, newAnswer, task, memory);
             LocalRules.trySolution(newAnswer, task, memory);
             return newAnswer.getTruth().getExpectation();
         } else {
             return 0.5f;
         }
     }