opennars: nars.entity.Concept.processJudgment
void nars.entity.Concept.processJudgment (Task task) private
To accept a new judgment as isBelief, and check for revisions and solutions.
Parameters
judg The judgment to be accepted
task The task to be processed
Returns
Whether to continue the processing of the task
Definition at line 114 of file Concept.java.
References nars.entity.BudgetValue.aboveThreshold(), nars.entity.Concept.addToTable(), nars.entity.BudgetValue.decPriority(), nars.entity.Stamp.equals(), nars.entity.Concept.evaluation(), nars.entity.Item.getBudget(), nars.storage.Memory.getNewStamp(), nars.entity.Task.getSentence(), nars.entity.Sentence.getStamp(), nars.storage.Memory.getTime(), nars.entity.Stamp.make(), nars.storage.Memory.Parameters.MAXIMUM_BELIEF_LENGTH, nars.inference.LocalRules.revisible(), nars.inference.LocalRules.revision(), nars.storage.Memory.setCurrentBelief(), nars.storage.Memory.setNewStamp(), and nars.inference.LocalRules.trySolution().
Referenced by nars.entity.Concept.directProcess().
{
         Sentence judg = task.getSentence();
         Sentence oldBelief = evaluation(judg, beliefs);
         if (oldBelief != null) {
             Stamp newStamp = judg.getStamp(), oldStamp = oldBelief.getStamp();
             if (newStamp.equals(oldStamp)) {
                 task.getBudget().decPriority(0);    // duplicated task
                 return;
             } else if (LocalRules.revisible(judg, oldBelief)) {
                 memory.setNewStamp(Stamp.make(newStamp, oldStamp, memory.getTime()));
                 if (memory.getNewStamp() != null) {
                     memory.setCurrentBelief(oldBelief);
                     LocalRules.revision(judg, oldBelief, false, memory);
                 }
             }
         }
         if (task.getBudget().aboveThreshold()) {
             for (Task ques : questions) {
 //                LocalRules.trySolution(ques.getSentence(), judg, ques, memory);
                 LocalRules.trySolution(judg, ques, memory);
             }
             addToTable(judg, beliefs, Memory.Parameters.MAXIMUM_BELIEF_LENGTH);
         }
     }