opennars: nars.entity.Concept.addToTable
void nars.entity.Concept.addToTable (Sentence newSentence, ArrayList< Sentence > table, int capacity) private
Add a new belief (or goal) into the table Sort the beliefs/goals by rank, and remove redundant or low rank one.
Parameters
newSentence The judgment to be processed
table The table to be revised
capacity The capacity of the table
Definition at line 214 of file Concept.java.
References nars.entity.Sentence.equivalentTo(), and nars.inference.BudgetFunctions.rankBelief().
Referenced by nars.entity.Concept.processJudgment().
{
         float rank1 = BudgetFunctions.rankBelief(newSentence);    // for the new isBelief
         Sentence judgment2;
         float rank2;
         int i;
         for (i = 0; i < table.size(); i++) {
             judgment2 = (Sentence) table.get(i);
             rank2 = BudgetFunctions.rankBelief(judgment2);
             if (rank1 >= rank2) {
                 if (newSentence.equivalentTo(judgment2)) {
                     return;
                 }
                 table.add(i, newSentence);
                 break;
             }
         }
         if (table.size() >= capacity) {
             while (table.size() > capacity) {
                 table.remove(table.size() - 1);
             }
         } else if (i == table.size()) {
             table.add(newSentence);
         }
     }