opennars: nars.entity.Concept.getQuality
float nars.entity.Concept.getQuality ()
Recalculate the quality of the concept [to be refined to show extension/intension balance].
Returns
The quality value
Definition at line 362 of file Concept.java.
References nars.storage.Bag< Type extends Item >.averagePriority(), nars.language.Term.getComplexity(), and nars.inference.UtilityFunctions.or().
Referenced by nars.inference.BudgetFunctions.activate().
{
         float linkPriority = termLinks.averagePriority();
         float termComplexityFactor = 1.0f / term.getComplexity();
         return UtilityFunctions.or(linkPriority, termComplexityFactor);
     }