opennars: nars.entity.Concept.directProcess
void nars.entity.Concept.directProcess (Task task)
Directly process a new task.
Called exactly once on each task. Using local information and finishing in a constant time. Provide feedback in the taskBudget value of the task.
called in Memory.immediateProcess only
Parameters
task The task to be processed
Definition at line 96 of file Concept.java.
References nars.entity.BudgetValue.aboveThreshold(), nars.entity.Concept.displayContent(), nars.entity.Item.getBudget(), nars.entity.Task.getSentence(), nars.entity.Sentence.isJudgment(), nars.entity.Concept.linkToTask(), nars.entity.Concept.processJudgment(), nars.entity.Concept.processQuestion(), and nars.entity.EntityObserver.refresh().
Referenced by nars.storage.Memory.immediateProcess().
{
         if (task.getSentence().isJudgment()) {
             processJudgment(task);
         } else {
             processQuestion(task);
         }
         if (task.getBudget().aboveThreshold()) {    // still need to be processed
             linkToTask(task);
         }
         entityObserver.refresh(displayContent());
     }