opennars: nars.entity.Concept.displayContent
String nars.entity.Concept.displayContent ()
Collect direct isBelief, questions, and goals for display.
Returns
String representation of direct content
Definition at line 471 of file Concept.java.
Referenced by nars.entity.Concept.directProcess(), nars.entity.Concept.play(), and nars.entity.Concept.startPlay().
{
         StringBuilder buffer = new StringBuilder();
         if (beliefs.size() > 0) {
             buffer.append("\n  Beliefs:\n");
             for (Sentence s : beliefs) {
                 buffer.append(s).append("\n");
             }
         }
         if (questions.size() > 0) {
             buffer.append("\n  Question:\n");
             for (Task t : questions) {
                 buffer.append(t).append("\n");
             }
         }
         return buffer.toString();
     }