opennars: nars.entity.Concept.buildTermLinks
void nars.entity.Concept.buildTermLinks (BudgetStruct taskBudget)
Recursively build TermLinks between a compound and its components.
called only from Memory.continuedProcess
Parameters
taskBudget The BudgetValue of the task
Definition at line 281 of file Concept.java.
References nars.entity.BudgetValue.aboveThreshold(), nars.entity.Concept.buildTermLinks(), nars.inference.BudgetFunctions.distributeAmongLinks(), nars.storage.Memory.getConcept(), nars.entity.Concept.insertTermLink(), and nars.entity.TermLink.TRANSFORM.
Referenced by nars.entity.Concept.buildTermLinks(), and nars.entity.Concept.linkToTask().
{
         Term t;
         Concept concept;
         TermLink termLink1, termLink2;
         if (termLinkTemplates.size() > 0) {
             BudgetValue subBudget = BudgetFunctions.distributeAmongLinks(taskBudget, termLinkTemplates.size());
             if (subBudget.aboveThreshold()) {
                 for (TermLink template : termLinkTemplates) {
                     if (template.getType() != TermLink.TRANSFORM) {
                         t = template.getTarget();
                         concept = memory.getConcept(t);
                         if (concept != null) {
                             termLink1 = new TermLink(t, template, subBudget);
                             insertTermLink(termLink1);   // this termLink to that
                             termLink2 = new TermLink(term, template, subBudget);
                             concept.insertTermLink(termLink2);   // that termLink to this
                             if (t instanceof CompoundTerm) {
                                 concept.buildTermLinks(subBudget);
                             }
                         }
                     }
                 }
             }
         }
     }