opennars: nars.entity.Concept.linkToTask
void nars.entity.Concept.linkToTask (Task task) private
Link to a new task from all relevant concepts for continued processing in the near future for unspecified time.
The only method that calls the TaskLink constructor.
Parameters
task The task to be linked
content The content of the task
Definition at line 181 of file Concept.java.
References nars.entity.BudgetValue.aboveThreshold(), nars.entity.Concept.buildTermLinks(), nars.inference.BudgetFunctions.distributeAmongLinks(), nars.entity.Item.getBudget(), nars.storage.Memory.getConcept(), and nars.entity.Concept.insertTaskLink().
Referenced by nars.entity.Concept.directProcess().
{
         BudgetValue taskBudget = task.getBudget();
         TaskLink taskLink = new TaskLink(task, null, taskBudget);   // link type: SELF
         insertTaskLink(taskLink);
         if (term instanceof CompoundTerm) {
             if (termLinkTemplates.size() > 0) {
                 BudgetValue subBudget = BudgetFunctions.distributeAmongLinks(taskBudget, termLinkTemplates.size());
                 if (subBudget.aboveThreshold()) {
                     Term componentTerm;
                     Concept componentConcept;
                     for (TermLink termLink : termLinkTemplates) {
 //                        if (!(task.isStructural() && (termLink.getType() == TermLink.TRANSFORM))) { // avoid circular transform
                         taskLink = new TaskLink(task, termLink, subBudget);
                         componentTerm = termLink.getTarget();
                         componentConcept = memory.getConcept(componentTerm);
                         if (componentConcept != null) {
                             componentConcept.insertTaskLink(taskLink);
                         }
 //                        }
                     }
                     buildTermLinks(taskBudget);  // recursively insert TermLink
                 }
             }
         }
     }