opennars: nars.entity.Concept.getBelief
Sentence nars.entity.Concept.getBelief (Task task)
Select a isBelief to interact with the given task in inference.
get the first qualified one
only called in RuleTables.reason
Parameters
task The selected task
Returns
The selected isBelief
Definition at line 385 of file Concept.java.
References nars.entity.Sentence.clone(), nars.storage.Memory.getNewStamp(), nars.storage.Memory.getRecorder(), nars.entity.Task.getSentence(), nars.entity.Sentence.getStamp(), nars.storage.Memory.getTime(), nars.entity.Stamp.make(), and nars.storage.Memory.setNewStamp().
Referenced by nars.inference.RuleTables.reason().
{
         Sentence taskSentence = task.getSentence();
         Sentence belief;
         for (int i = 0; i < beliefs.size(); i++) {
             belief = beliefs.get(i);
             memory.getRecorder().append(" * Selected Belief: " + belief + "\n");
             memory.setNewStamp(Stamp.make(taskSentence.getStamp(), belief.getStamp(), memory.getTime()));
             if (memory.getNewStamp() != null) {
                 Sentence belief2 = (Sentence) belief.clone();   // will this mess up priority adjustment?
                 return belief2;
             }
         }
         return null;
     }