opennars: nars.entity.Concept.evaluation
Sentence nars.entity.Concept.evaluation (Sentence query, Iterable< Sentence > list) private
Evaluate a query against beliefs (and desires in the future)
Parameters
query The question to be processed
list The list of beliefs to be used
Returns
The best candidate belief selected
Definition at line 245 of file Concept.java.
References nars.inference.LocalRules.solutionQuality().
Referenced by nars.entity.Concept.processJudgment(), and nars.entity.Concept.processQuestion().
{
         if (list == null) {
             return null;
         }
         float currentBest = 0;
         float beliefQuality;
         Sentence candidate = null;
         for (Sentence judg : list) {
             beliefQuality = LocalRules.solutionQuality(query, judg);
             if (beliefQuality > currentBest) {
                 currentBest = beliefQuality;
                 candidate = judg;
             }
         }
         return candidate;
     }