opennars: nars.entity.Concept.startPlay
void nars.entity.Concept.startPlay (EntityObserver entityObserver, boolean showLinks)
Start displaying contents and links, called from ConceptWindow, TermWindow or Memory.processTask only.
same design as for Bag and BagWindow; see Bag#addBagObserver(BagObserver, String)
Parameters
entityObserver TODO make it a real observer pattern (i.e. with a plurality of observers)
showLinks Whether to display the task links
Definition at line 443 of file Concept.java.
References nars.storage.Bag< Type extends Item >.addBagObserver(), nars.entity.EntityObserver.createBagObserver(), nars.entity.Concept.displayContent(), nars.entity.Concept.entityObserver, nars.entity.EntityObserver.post(), nars.entity.EntityObserver.startPlay(), and nars.entity.Concept.term.
{
         this.entityObserver = entityObserver;
         entityObserver.startPlay(this, showLinks);
         entityObserver.post(displayContent());
         if (showLinks) {
             taskLinks.addBagObserver(entityObserver.createBagObserver(), "Task Links in " + term);
             termLinks.addBagObserver(entityObserver.createBagObserver(), "Term Links in " + term);
         }
     }