opennars: nars.entity.TaskLink.toString
String nars.entity.TaskLink.toString ()
Definition at line 115 of file TaskLink.java.
References nars.entity.Task.getSentence(), nars.entity.Sentence.getStamp(), and nars.entity.TaskLink.getTargetTask().
{
         return super.toString() + " " + getTargetTask().getSentence().getStamp();
     }