opennars: nars.entity.TaskLink.novel
boolean nars.entity.TaskLink.novel (TermLink termLink, long currentTime)
To check whether a TaskLink should use a TermLink, return false if they interacted recently.
called in TermLinkBag only
Parameters
termLink The TermLink to be checked
currentTime The current time
Returns
Whether they are novel to each other
Definition at line 85 of file TaskLink.java.
References nars.entity.TaskLink.counter, nars.language.Term.equals(), nars.entity.Sentence.getContent(), nars.entity.Item.getKey(), nars.entity.Task.getSentence(), nars.entity.TermLink.getTarget(), and nars.storage.Memory.Parameters.TERM_LINK_RECORD_LENGTH.
Referenced by nars.storage.TermLinkBag.takeOut().
{
         Term bTerm = termLink.getTarget();
         if (bTerm.equals(targetTask.getSentence().getContent())) {
             return false;
         }
         String linkKey = termLink.getKey();
         int next = 0;
         int i;
         for (i = 0; i < counter; i++) {
             next = i % Memory.Parameters.TERM_LINK_RECORD_LENGTH;
             if (linkKey.equals(recordedLinks[next])) {
                 if (currentTime < recordingTime[next] + Memory.Parameters.TERM_LINK_RECORD_LENGTH) {
                     return false;
                 } else {
                     recordingTime[next] = currentTime;
                     return true;
                 }
             }
         }
         next = i % Memory.Parameters.TERM_LINK_RECORD_LENGTH;
         recordedLinks[next] = linkKey;       // add knowledge reference to recordedLinks
         recordingTime[next] = currentTime;
         if (counter < Memory.Parameters.TERM_LINK_RECORD_LENGTH) { // keep a constant length
             counter++;
         }
         return true;
     }