opennars: nars.language.Equivalence.make
static Equivalence nars.language.Equivalence.make (Term subject, Term predicate, Memory memory) static
Try to make a new compound from two components.
Called by the inference rules.
Parameters
subject The first component
predicate The second component
memory Reference to the memory
Returns
A compound generated or null
Definition at line 67 of file Equivalence.java.
References nars.language.CompoundTerm.argumentsToList(), nars.language.Term.compareTo(), nars.language.Equivalence.Equivalence(), nars.io.Symbols.EQUIVALENCE_RELATION, nars.language.Statement.invalidStatement(), nars.language.Statement.makeStatementName(), nars.language.Term.name, and nars.storage.Memory.nameToListedTerm().
Referenced by nars.inference.LocalRules.inferToSym(), nars.inference.CompositionalRules.introVarOuter(), nars.language.Statement.make(), and nars.language.Statement.makeSym().
                                                                                 {  // to be extended to check if subject is Conjunction
         if ((subject instanceof Implication) || (subject instanceof Equivalence)) {
             return null;
         }
         if ((predicate instanceof Implication) || (predicate instanceof Equivalence)) {
             return null;
         }
         if (invalidStatement(subject, predicate)) {
             return null;
         }
         if (subject.compareTo(predicate) > 0) {
             Term interm = subject;
             subject = predicate;
             predicate = interm;
         }
         String name = makeStatementName(subject, Symbols.EQUIVALENCE_RELATION, predicate);
         Term t = memory.nameToListedTerm(name);
         if (t != null) {
             return (Equivalence) t;
         }
         ArrayList<Term> argument = argumentsToList(subject, predicate);
         return new Equivalence(argument);
     }