opennars: nars.inference.StructuralRules.transformProductImage
static void nars.inference.StructuralRules.transformProductImage (Inheritance inh, CompoundTerm oldContent, short[] indices, Memory memory) static package
Equivalent transformation between products and images {<(*, S, M) –> P>, S@(*, S, M)} |- <S --> (/, P, _, M)> {<S --> (/, P, _, M)>, P@(/, P, _, M)} |- <(*, S, M) –> P> {<S --> (/, P, _, M)>, M@(/, P, _, M)} |- <M --> (/, P, S, _)>
Parameters
inh An Inheritance statement
oldContent The whole content
indices The indices of the TaskLink
memory Reference to the memory
Definition at line 357 of file StructuralRules.java.
References nars.language.CompoundTerm.cloneComponents(), nars.language.CompoundTerm.componentAt(), nars.language.Term.equals(), nars.storage.Memory.getCurrentTask(), nars.language.Statement.getPredicate(), nars.entity.Task.getSentence(), nars.language.Statement.getSubject(), nars.entity.Sentence.getTruth(), nars.entity.Sentence.isQuestion(), nars.language.Inheritance.make(), nars.language.ImageInt.make(), nars.language.ImageExt.make(), nars.language.CompoundTerm.make(), nars.storage.Memory.singlePremiseTask(), nars.inference.StructuralRules.transformPredicatePI(), and nars.inference.StructuralRules.transformSubjectPI().
Referenced by nars.inference.RuleTables.transformTask().
{
         Term subject = inh.getSubject();
         Term predicate = inh.getPredicate();
         if (inh.equals(oldContent)) {
             if (subject instanceof CompoundTerm) transformSubjectPI((CompoundTerm) subject, predicate, memory);
             if (predicate instanceof CompoundTerm) transformPredicatePI(subject, (CompoundTerm) predicate, memory);
         } else {
             short index = indices[indices.length - 1];
             short side = indices[indices.length - 2];
             CompoundTerm comp = (CompoundTerm) inh.componentAt(side);
             if ((comp instanceof Product)) {
                 if (side == 0) {
                     subject = comp.componentAt(index);
                     predicate = ImageExt.make((Product) comp, inh.getPredicate(), index, memory);
                 } else {
                     subject = ImageInt.make((Product) comp, inh.getSubject(), index, memory);
                     predicate = comp.componentAt(index);
                 }
             } else if ((comp instanceof ImageExt) && side == 1) {
                 if (index == ((ImageExt) comp).getRelationIndex()) {
                     subject = Product.make(comp, inh.getSubject(), index, memory);
                     predicate = comp.componentAt(index);
                 } else {
                     subject = comp.componentAt(index);
                     predicate = ImageExt.make((ImageExt) comp, inh.getSubject(), index, memory);
                 }
             } else {
                 if (comp instanceof ImageInt && side == 0) if (index != ((ImageInt) comp).getRelationIndex()) {
                     subject = ImageInt.make((ImageInt) comp, inh.getPredicate(), index, memory);
                     predicate = comp.componentAt(index);
                 } else {
                     subject = comp.componentAt(index);
                     predicate = Product.make(comp, inh.getPredicate(), index, memory);
                 }
                 else {
                     return;
                 }
             }
             Inheritance newInh = Inheritance.make(subject, predicate, memory);
             Term content = null;
             if (indices.length != 2) if (!(oldContent instanceof Statement) || 1 != indices[0]) {
                 ArrayList<Term> componentList;
                 Term condition = oldContent.componentAt(0);
                 if ((oldContent instanceof Implication || (oldContent instanceof Equivalence))) {
                     if (!(condition instanceof Conjunction)) {
                         componentList = oldContent.cloneComponents();
                         componentList.set(indices[0], newInh);
                         content = Statement.make((Statement) oldContent, componentList.get(0), componentList.get(1), memory);
                     } else {
                         componentList = ((CompoundTerm) condition).cloneComponents();
                         componentList.set(indices[1], newInh);
                         Term newCond = CompoundTerm.make((CompoundTerm) condition, componentList, memory);
                         content = Statement.make((Statement) oldContent, newCond, ((Statement) oldContent).getPredicate(), memory);
                     }
                 } else {
                     componentList = oldContent.cloneComponents();
                     componentList.set(indices[0], newInh);
                     if (oldContent instanceof Conjunction) {
                         content = CompoundTerm.make(oldContent, componentList, memory);
                     }
                 }
             } else {
                 content = Statement.make((Statement) oldContent, oldContent.componentAt(0), newInh, memory);
             }
             else {
                 content = newInh;
             }
             if (null != content) {
                 Sentence sentence = memory.getCurrentTask().getSentence();
                 TruthValue truth = sentence.getTruth();
                 BudgetValue budget;
                 budget = sentence.isQuestion() ? compoundBackward(content, memory) : compoundForward(truth, content, memory);
                 memory.singlePremiseTask(content, truth, budget);
             }
         }
     }