opennars: nars.inference.StructuralRules.switchOrder
static boolean nars.inference.StructuralRules.switchOrder (CompoundTerm compound, short index) static private
List the cases where the direction of inheritance is revised in conclusion.
Parameters
compound The compound term
index The location of focus in the compound
Returns
Whether the direction of inheritance should be revised
Definition at line 188 of file StructuralRules.java.
References nars.language.ImageExt.getRelationIndex(), and nars.language.ImageInt.getRelationIndex().
Referenced by nars.inference.StructuralRules.structuralCompose2(), and nars.inference.StructuralRules.structuralDecompose2().
{
         return (compound instanceof DifferenceExt || compound instanceof DifferenceInt) && index == 1
                 || compound instanceof ImageExt && index != ((ImageExt) compound)
                         .getRelationIndex() || compound instanceof ImageInt && index != ((ImageInt) compound)
                 .getRelationIndex();
     }