opennars: nars.inference.StructuralRules.contraposition
static void nars.inference.StructuralRules.contraposition (Statement statement, Memory memory) static package
{<A ==> B>, A@(–, A)} |- <(–, B) ==> (–, A)>
Parameters
statement The premise
memory Reference to the memory
Definition at line 622 of file StructuralRules.java.
References nars.inference.BudgetFunctions.compoundBackwardWeak(), nars.inference.TruthFunctions.contraposition(), nars.storage.Memory.getCurrentTask(), nars.language.Statement.getPredicate(), nars.entity.Task.getSentence(), nars.language.Statement.getSubject(), nars.entity.Sentence.getTruth(), nars.entity.Sentence.isQuestion(), nars.language.Negation.make(), nars.language.Statement.make(), and nars.storage.Memory.singlePremiseTask().
Referenced by nars.inference.RuleTables.componentAndStatement().
{
         Term subj = statement.getSubject();
         Term pred = statement.getPredicate();
         Task task = memory.getCurrentTask();
         Sentence sentence = task.getSentence();
         Term content = Statement.make(statement, Negation.make(pred, memory),
                 Negation.make(subj, memory), memory);
         TruthValue truth = sentence.getTruth();
         BudgetValue budget;
         if (sentence.isQuestion()) {
             if (content instanceof Implication) {
                 budget = BudgetFunctions.compoundBackwardWeak(content, memory);
             } else {
                 budget = compoundBackward(content, memory);
             }
         } else {
             if (content instanceof Implication) {
                 truth = TruthFunctions.contraposition(truth);
             }
             budget = compoundForward(truth, content, memory);
         }
         memory.singlePremiseTask(content, truth, budget);
     }