opennars: nars.inference.StructuralRules.structuralDecompose2
static void nars.inference.StructuralRules.structuralDecompose2 (Statement statement, Memory memory) static package
{<(S&T) –> (P&T)>, S@(S&T)} |- <S --> P>
Parameters
statement The premise
memory Reference to the memory
Definition at line 127 of file StructuralRules.java.
References nars.language.CompoundTerm.componentAt(), nars.language.Term.equals(), nars.storage.Memory.getCurrentTask(), nars.language.Statement.getPredicate(), nars.entity.Task.getSentence(), nars.language.Statement.getSubject(), nars.entity.Sentence.getTruth(), nars.entity.Sentence.isJudgment(), nars.entity.Sentence.isQuestion(), nars.language.Statement.make(), nars.storage.Memory.singlePremiseTask(), nars.language.CompoundTerm.size(), and nars.inference.StructuralRules.switchOrder().
Referenced by nars.inference.RuleTables.componentAndStatement().
{
         Term subj = statement.getSubject();
         Term pred = statement.getPredicate();
         if (subj.getClass() != pred.getClass()) {
             return;
         }
         CompoundTerm sub = (CompoundTerm) subj;
         CompoundTerm pre = (CompoundTerm) pred;
         if (sub.size() != pre.size()) {
             return;
         }
         int index = -1;
         Term t1, t2;
         for (int i = 0; i < sub.size(); i++) {
             t1 = sub.componentAt(i);
             t2 = pre.componentAt(i);
             if (!t1.equals(t2)) {
                 if (index < 0) {
                     index = i;
                 } else {
                     return;
                 }
             }
         }
         t1 = sub.componentAt(index);
         t2 = pre.componentAt(index);
         Term content;
         if (switchOrder(sub, (short) index)) {
             content = Statement.make(statement, t2, t1, memory);
         } else {
             content = Statement.make(statement, t1, t2, memory);
         }
         if (content == null) {
             return;
         }
         Task task = memory.getCurrentTask();
         Sentence sentence = task.getSentence();
         TruthValue truth = sentence.getTruth();
         BudgetValue budget;
         if (sentence.isQuestion()) {
             budget = compoundBackward(content, memory);
         } else {
             if (sub.size() > 1 && sentence.isJudgment()) {
                 return;
             }
             budget = compoundForward(truth, content, memory);
         }
         memory.singlePremiseTask(content, truth, budget);
     }