opennars: nars.inference.StructuralRules.transformPredicatePI
static void nars.inference.StructuralRules.transformPredicatePI (Term subject, CompoundTerm predicate, Memory memory) static private
Equivalent transformation between products and images when the predicate is a compound {<(*, S, M) –> P>, S@(*, S, M)} |- <S --> (/, P, _, M)> {<S --> (/, P, _, M)>, P@(/, P, _, M)} |- <(*, S, M) –> P> {<S --> (/, P, _, M)>, M@(/, P, _, M)} |- <M --> (/, P, S, _)>
Parameters
subject The subject term
predicate The predicate term
memory Reference to the memory
Definition at line 503 of file StructuralRules.java.
References nars.language.CompoundTerm.componentAt(), nars.storage.Memory.getCurrentTask(), nars.language.ImageExt.getRelationIndex(), nars.entity.Task.getSentence(), nars.entity.Sentence.getTruth(), nars.language.Inheritance.make(), nars.language.ImageInt.make(), nars.storage.Memory.singlePremiseTask(), and nars.language.CompoundTerm.size().
Referenced by nars.inference.StructuralRules.transformProductImage().
{
         TruthValue truth = memory.getCurrentTask().getSentence().getTruth();
         BudgetValue budget;
         Inheritance inheritance;
         Term newSubj, newPred;
         if (predicate instanceof Product) {
             Product product = (Product) predicate;
             for (short i = 0; i < product.size(); i++) {
                 newSubj = ImageInt.make(product, subject, i, memory);
                 newPred = product.componentAt(i);
                 inheritance = Inheritance.make(newSubj, newPred, memory);
                 if (truth == null) {
                     budget = compoundBackward(inheritance,
                             memory);
                 } else {
                     budget = compoundForward(truth,
                             inheritance, memory);
                 }
                 memory.singlePremiseTask(inheritance, truth, budget);
             }
         } else if (predicate instanceof ImageExt) {
             ImageExt image = (ImageExt) predicate;
             int relationIndex = image.getRelationIndex();
             for (short i = 0; i < image.size(); i++) {
                 if (i == relationIndex) {
                     newSubj = Product.make(image, subject, relationIndex,
                             memory);
                     newPred = image.componentAt(relationIndex);
                 } else {
                     newSubj = image.componentAt(i);
                     newPred = ImageExt.make(image, subject, i,
                             memory);
                 }
                 inheritance = Inheritance.make(newSubj, newPred, memory);
                 if (inheritance != null) { // jmv <<<<<
                     budget = truth == null ? compoundBackward(inheritance,
                             memory) : compoundForward(truth,
                             inheritance, memory);
                     memory.singlePremiseTask(inheritance, truth, budget);
                 }
             }
         }
     }