opennars: nars.inference.StructuralRules.transformSetRelation
static void nars.inference.StructuralRules.transformSetRelation (CompoundTerm compound, Statement statement, short side, Memory memory) static package
{<S --> {P}>} |- <S <-> {P}>
Parameters
compound The set compound
statement The premise
side The location of the indicated term in the premise
memory Reference to the memory
Definition at line 322 of file StructuralRules.java.
References nars.storage.Memory.getCurrentTask(), nars.language.Statement.getPredicate(), nars.entity.Task.getSentence(), nars.language.Statement.getSubject(), nars.entity.Sentence.getTruth(), nars.entity.Sentence.isQuestion(), nars.language.Similarity.make(), nars.language.Inheritance.make(), nars.storage.Memory.singlePremiseTask(), and nars.language.CompoundTerm.size().
Referenced by nars.inference.RuleTables.componentAndStatement().
{
         if (compound.size() <= 1 && (!(statement instanceof Inheritance) || (!(compound instanceof SetExt) || side != 0)
                         && (!(compound instanceof SetInt) || side != 1))) {
             Term sub = statement.getSubject();
             Term pre = statement.getPredicate();
             Term content;
             content = !(statement instanceof Inheritance) ? compound instanceof SetExt && side == 0
                     || compound instanceof SetInt && side == 1 ? Inheritance.make(pre, sub, memory) : Inheritance.make(sub, pre, memory) : Similarity.make(sub, pre, memory);
             Task task = memory.getCurrentTask();
             Sentence sentence = task.getSentence();
             TruthValue truth = sentence.getTruth();
             BudgetValue budget;
             budget = sentence.isQuestion() ? compoundBackward(content, memory) : compoundForward(truth, content, memory);
             memory.singlePremiseTask(content, truth, budget);
         }
     }