opennars: nars.inference.StructuralRules.transformSubjectPI
static void nars.inference.StructuralRules.transformSubjectPI (CompoundTerm subject, Term predicate, Memory memory) static private
Equivalent transformation between products and images when the subject is a compound {<(*, S, M) –> P>, S@(*, S, M)} |- <S --> (/, P, _, M)> {<S –> (/, P, _, M)>, P@(/, P, _, M)} |- <(*, S, M) –> P> {<S --> (/, P, _, M)>, M@(/, P, _, M)} |- <M --> (/, P, S, _)>
Parameters
subject The subject term
predicate The predicate term
memory Reference to the memory
Definition at line 448 of file StructuralRules.java.
References nars.language.CompoundTerm.componentAt(), nars.storage.Memory.getCurrentTask(), nars.language.ImageInt.getRelationIndex(), nars.entity.Task.getSentence(), nars.entity.Sentence.getTruth(), nars.language.Inheritance.make(), nars.language.ImageExt.make(), nars.storage.Memory.singlePremiseTask(), and nars.language.CompoundTerm.size().
Referenced by nars.inference.StructuralRules.transformProductImage().
{
         TruthValue truth = memory.getCurrentTask().getSentence().getTruth();
         BudgetValue budget;
         Inheritance inheritance;
         Term newSubj, newPred;
         if (subject instanceof Product) {
             Product product = (Product) subject;
             for (short i = 0; i < product.size(); i++) {
                 newSubj = product.componentAt(i);
                 newPred = ImageExt.make(product, predicate, i, memory);
                 inheritance = Inheritance.make(newSubj, newPred, memory);
                 budget = truth == null ? compoundBackward(inheritance,
                         memory) : compoundForward(truth,
                         inheritance, memory);
                 memory.singlePremiseTask(inheritance, truth, budget);
             }
         } else {
             if (!(subject instanceof ImageInt)) {
                 return;
             }
             ImageInt image = (ImageInt) subject;
             int relationIndex = image.getRelationIndex();
             for (short i = 0; i < image.size(); i++) {
                 if (i == relationIndex) {
                     newSubj = image.componentAt(relationIndex);
                     newPred = Product.make(image, predicate, relationIndex,
                             memory);
                 } else {
                     newSubj = ImageInt.make(image, predicate, i,
                             memory);
                     newPred = image.componentAt(i);
                 }
                 inheritance = Inheritance.make(newSubj, newPred, memory);
                 budget = truth == null ? compoundBackward(inheritance,
                         memory) : compoundForward(truth,
                         inheritance, memory);
                 memory.singlePremiseTask(inheritance, truth, budget);
             }
         }
     }