opennars: nars.inference.StructuralRules.structuralDecompose1
static void nars.inference.StructuralRules.structuralDecompose1 (CompoundTerm compound, short index, Statement statement, Memory memory) static package
{<(S&T) –> P>, S@(S&T)} |- <S --> P>
Parameters
compound The compound term
index The location of the indicated term in the compound
statement The premise
memory Reference to the memory
Definition at line 252 of file StructuralRules.java.
References nars.language.CompoundTerm.componentAt(), nars.inference.TruthFunctions.deduction(), nars.language.Term.equals(), nars.storage.Memory.getCurrentTask(), nars.language.Statement.getPredicate(), nars.entity.Task.getSentence(), nars.language.Statement.getSubject(), nars.entity.Sentence.getTruth(), nars.entity.Sentence.isJudgment(), nars.inference.TruthFunctions.negation(), and nars.inference.StructuralRules.structuralStatement().
Referenced by nars.inference.RuleTables.componentAndStatement().
{
         if (memory.getCurrentTask().getSentence().isJudgment()) {
             Term component = compound.componentAt(index);
             Task task = memory.getCurrentTask();
             Sentence sentence = task.getSentence();
             TruthValue truth = sentence.getTruth();
             TruthValue truthDed = TruthFunctions.deduction(truth, RELIANCE);
             TruthValue truthNDed = TruthFunctions.negation(TruthFunctions
                     .deduction(truth, RELIANCE));
             Term subj = statement.getSubject();
             Term pred = statement.getPredicate();
             if (!compound.equals(subj) && compound.equals(pred)
                     && !(compound instanceof IntersectionExt)) {
                 if (!(compound instanceof IntersectionInt)) {
                     structuralStatement(
                             component,
                             pred,
                             compound instanceof DifferenceExt && index == 0
                                     || !(compound instanceof DifferenceInt)
                                     ? index == 0 ? truthDed : truthNDed
                                     : truthDed, memory);
                 } else {
                     structuralStatement(subj, component, truthDed, memory);
                 }
             }
         }
     }