opennars: nars.inference.StructuralRules.structuralCompound
static void nars.inference.StructuralRules.structuralCompound (CompoundTerm compound, Term component, boolean compoundTask, Memory memory) static package
{(&&, A, B), A@(&&, A, B)} |- A {(||, A, B), A@(||, A, B)} |- A
Parameters
compound The premise
component The recognized component in the premise
compoundTask Whether the compound comes from the task
memory Reference to the memory
Definition at line 562 of file StructuralRules.java.
References nars.inference.TruthFunctions.deduction(), nars.inference.BudgetFunctions.forward(), nars.storage.Memory.getCurrentTask(), nars.entity.Task.getSentence(), nars.entity.Sentence.getTruth(), nars.language.Term.isConstant(), nars.entity.Sentence.isJudgment(), nars.entity.Sentence.isQuestion(), nars.entity.Task.isStructural(), and nars.storage.Memory.singlePremiseTask().
Referenced by nars.inference.RuleTables.compoundAndSelf().
{
         if (!component.isConstant()) {
             return;
         }
         Term content = compoundTask ? component : compound;
         Task task = memory.getCurrentTask();
         if (task.isStructural()) {
             return;
         }
         Sentence sentence = task.getSentence();
         TruthValue truth = sentence.getTruth();
         BudgetValue budget;
         if (sentence.isQuestion()) {
             budget = compoundBackward(content, memory);
         } else {
             if (sentence.isJudgment() == compoundTask == compound instanceof Conjunction) {
                 truth = TruthFunctions.deduction(truth, RELIANCE);
             } else {
                 return;
             }
             budget = BudgetFunctions.forward(truth, memory);
         }
         memory.singlePremiseTask(content, truth, budget);
     }