opennars: nars.inference.StructuralRules.structuralCompose2
static void nars.inference.StructuralRules.structuralCompose2 (CompoundTerm compound, short index, Statement statement, short side, Memory memory) static package
{<S --> P>, S@(S&T)} |- <(S&T) –> (P&T)> {<S --> P>, S@(M-S)} |- <(M-P) –> (M-S)>
Parameters
compound The compound term
index The location of the indicated term in the compound
statement The premise
side The location of the indicated term in the premise
memory Reference to the memory
Definition at line 64 of file StructuralRules.java.
References nars.language.CompoundTerm.cloneComponents(), nars.language.CompoundTerm.componentAt(), nars.inference.BudgetFunctions.compoundBackwardWeak(), nars.inference.TruthFunctions.deduction(), nars.language.Term.equals(), nars.storage.Memory.getCurrentTask(), nars.language.Statement.getPredicate(), nars.entity.Task.getSentence(), nars.language.Statement.getSubject(), nars.entity.Sentence.getTruth(), nars.entity.Sentence.isJudgment(), nars.entity.Sentence.isQuestion(), nars.language.Statement.make(), nars.storage.Memory.singlePremiseTask(), nars.language.CompoundTerm.size(), and nars.inference.StructuralRules.switchOrder().
Referenced by nars.inference.RuleTables.compoundAndStatement().
{
         if (compound.equals(statement.componentAt(side))) {
             return;
         }
         Term sub = statement.getSubject();
         Term pred = statement.getPredicate();
         ArrayList<Term> components = compound.cloneComponents();
         if ((side == 0 && components.contains(pred)) || (side == 1 && components.contains(sub))) {
             return;
         }
         if (side == 0) {
             if (!components.contains(sub)) {
                 if (components.contains(pred)) {
                     if (sub instanceof CompoundTerm) {
                         return;
                     } else {
                         components.set(index, sub);
                         sub = CompoundTerm.make(compound, components, memory);
                         pred = compound;
                     }
                 }
                 else {
                     if (pred instanceof CompoundTerm) {
                         return;
                     } else {
                         sub = compound;
                         components.set(index, pred);
                         pred = CompoundTerm.make(compound, components, memory);
                     }
                 }
             }
         }
         if (sub != null && pred != null) {
             Term content = switchOrder(compound, index) ? Statement.make(statement, pred, sub, memory) : Statement.make(statement, sub, pred, memory);
             if (content != null) {
                 Task task = memory.getCurrentTask();
                 Sentence sentence = task.getSentence();
                 TruthValue truth = sentence.getTruth();
                 BudgetValue budget;
                 if (sentence.isQuestion()) {
                     budget = BudgetFunctions.compoundBackwardWeak(content, memory);
                 } else {
                     if (compound.size() > 1) {
                         if (sentence.isJudgment()) {
                             truth = TruthFunctions.deduction(truth, RELIANCE);
                         } else {
                             return;
                         }
                     }
                     budget = compoundForward(truth, content, memory);
                 }
                 memory.singlePremiseTask(content, truth, budget);
             }
         }
     }