opennars: nars.storage.Bag.putIn
boolean nars.storage.Bag< Type extends Item >.putIn (Type newItem)
Add a new Item into the Bag.
Parameters
newItem The new Item
Returns
Whether the new Item is added into the Bag
Definition at line 154 of file Bag.java.
Referenced by nars.storage.Memory.getConcept(), nars.entity.Concept.insertTaskLink(), nars.entity.Concept.insertTermLink(), nars.storage.Memory.processNewTask(), and nars.storage.Bag< Concept >.putBack().
{
         String newKey = newItem.getKey();
         Type oldItem = nameTable.put(newKey, newItem);
         if (oldItem != null) {                  // merge duplications
             outOfBase(oldItem);
             newItem.merge(oldItem);
         }
         Type overflowItem = intoBase(newItem);  // put the (new or merged) item into itemTable
         if (overflowItem != null) {             // remove overflow
             String overflowKey = overflowItem.getKey();
             nameTable.remove(overflowKey);
             return (overflowItem != newItem);
         } else {
             return true;
         }
     }