opennars: nars.storage.Bag.get
Type nars.storage.Bag< Type extends Item >.get (String key)
Get an Item by key.
Parameters
key The key of the Item
Returns
The Item with the given key
Definition at line 145 of file Bag.java.
Referenced by nars.storage.Memory.getConcept(), nars.storage.Memory.nameToConcept(), and nars.storage.Memory.nameToListedTerm().
{
         return nameTable.get(key);
     }