opennars: nars.storage.Bag.putBack
boolean nars.storage.Bag< Type extends Item >.putBack (Type oldItem)
Put an item back into the itemTable.
The only place where the forgetting rate is applied
Parameters
oldItem The Item to put back
Returns
Whether the new Item is added into the Bag
Definition at line 178 of file Bag.java.
Referenced by nars.storage.Memory.activateConcept(), nars.entity.Concept.fire(), and nars.storage.Memory.processConcept().
{
         BudgetFunctions.forget(oldItem.getBudget(), forgetRate(), RELATIVE_THRESHOLD);
         return putIn(oldItem);
     }