opennars: nars.entity.TermLink.TermLink
nars.entity.TermLink.TermLink (Term t, TermLink template, BudgetValue v)
Constructor to make actual TermLink from a template.
called in Concept.buildTermLinks only
Parameters
t Target Term
template TermLink template previously prepared
v Budget value of the link
Definition at line 104 of file TermLink.java.
References nars.language.Term.getName(), nars.entity.TermLink.getTarget(), and nars.entity.TermLink.setKey().
{
         super(t.getName(), v);
         target = t;
         type = template.getType();
         if (template.getTarget().equals(t)) {
             type--;     // point to component
         }
         index = template.getIndices();
         setKey();
     }