opennars: nars.entity.TermLink.getIndex
short nars.entity.TermLink.getIndex (int i)
Get one index by level.
Parameters
i The index level
Returns
The index value
Definition at line 168 of file TermLink.java.
Referenced by nars.inference.RuleTables.indexToFigure(), nars.inference.RuleTables.reason(), and nars.inference.RuleTables.syllogisms().
{
         if ((index != null) && (i < index.length)) {
             return index[i];
         } else {
             return -1;
         }
     }