opennars: nars.language.Variable.hasSubstitute
static boolean nars.language.Variable.hasSubstitute (char type, Term term1, Term term2) static
Check if two terms can be unified.
Parameters
type The type of variable that can be substituted
term1 The first term to be unified
term2 The second term to be unified
Returns
Whether there is a substitution
Definition at line 195 of file Variable.java.
References nars.language.Variable.findSubstitute().
Referenced by nars.inference.SyllogisticRules.conditionalAna(), and nars.inference.SyllogisticRules.conditionalDedInd().
{
         return findSubstitute(type, term1, term2, new HashMap<Term, Term>(), new HashMap<Term, Term>());
     }