opennars: nars.language.Variable.containVar
static boolean nars.language.Variable.containVar (String n) static
Check whether a string represent a name of a term that contains a variable.
Parameters
n The string name to be checked
Returns
Whether the name contains a variable
Definition at line 98 of file Variable.java.
References nars.language.Variable.containVarDep(), nars.language.Variable.containVarIndep(), and nars.language.Variable.containVarQuery().
Referenced by nars.language.CompoundTerm.CompoundTerm(), nars.language.CompoundTerm.containVar(), and nars.io.StringParser.parseAtomicTerm().
{
         return containVarIndep(n) || containVarDep(n) || containVarQuery(n);
     }