opennars: nars.language.Variable.findSubstitute
static boolean nars.language.Variable.findSubstitute (char type, Term term1, Term term2, HashMap< Term, Term > map1, HashMap< Term, Term > map2) static private
To recursively find a substitution that can unify two Terms without changing them.
Parameters
type The type of Variable to be substituted
term1 The first Term to be unified
term2 The second Term to be unified
subs The substitution formed so far
Returns
The substitution that unifies the two Terms
Definition at line 145 of file Variable.java.
References nars.language.CompoundTerm.componentAt(), nars.language.Term.equals(), nars.language.Variable.getType(), and nars.language.CompoundTerm.size().
Referenced by nars.language.Variable.hasSubstitute(), and nars.language.Variable.unify().
{
         Term t;
         if ((term1 instanceof Variable) && ((Variable) term1).getType() == type) {
             t = map1.get((Variable) term1);
             if (t != null) {
                 return t.equals(term2);
             } else {
                 map1.put((Variable) term1, term2);
                 return true;
             }
         }
         if ((term2 instanceof Variable) && ((Variable) term2).getType() == type) {
             t = map2.get((Variable) term2);
             if (t != null) {
                 return t.equals(term1);
             } else {
                 map2.put((Variable) term2, term1);
                 return true;
             }
         }
         if ((term1 instanceof CompoundTerm) && term1.getClass().equals(term2.getClass())) {
             CompoundTerm cTerm1 = (CompoundTerm) term1;
             CompoundTerm cTerm2 = (CompoundTerm) term2;
             if (cTerm1.size() != (cTerm2).size()) {
                 return false;
             }
             for (int i = 0; i < cTerm1.size(); i++) {
                 Term t1 = cTerm1.componentAt(i);
                 Term t2 = cTerm2.componentAt(i);
                 boolean haveSub = findSubstitute(type, t1, t2, map1, map2);
                 if (!haveSub) {
                     return false;
                 }
             }
             return true;
         }
         if (!(term1 instanceof Variable) && !(term2 instanceof Variable) && term1.equals(term2)) {// for constant, also shortcut for variable and compound
             return true;
         }
         return false;
     }