opennars: nars.language.Inheritance.make
static Inheritance nars.language.Inheritance.make (Term subject, Term predicate, Memory memory) static
Try to make a new compound from two components.
Called by the inference rules.
Parameters
subject The first compoment
predicate The second compoment
memory Reference to the memory
Returns
A compound generated or null
Definition at line 68 of file Inheritance.java.
References nars.language.CompoundTerm.argumentsToList(), nars.language.Inheritance.Inheritance(), nars.io.Symbols.INHERITANCE_RELATION, nars.language.Statement.invalidStatement(), nars.language.Statement.makeStatementName(), nars.language.Term.name, and nars.storage.Memory.nameToListedTerm().
Referenced by nars.inference.CompositionalRules.introVarOuter(), nars.language.Instance.make(), nars.language.InstanceProperty.make(), nars.language.Property.make(), nars.language.Statement.make(), nars.inference.StructuralRules.transformPredicatePI(), nars.inference.StructuralRules.transformProductImage(), nars.inference.StructuralRules.transformSetRelation(), and nars.inference.StructuralRules.transformSubjectPI().
{
         if (invalidStatement(subject, predicate)) {
             return null;
         }
         String name = makeStatementName(subject, Symbols.INHERITANCE_RELATION, predicate);
         Term t = memory.nameToListedTerm(name);
         if (t != null) {
             return (Inheritance) t;
         }
         ArrayList<Term> argument = argumentsToList(subject, predicate);
         return new Inheritance(argument);
     }