opennars: nars.inference.UtilityFunctions.or
static float nars.inference.UtilityFunctions.or (float... arr) static
A function where the output is disjunctively determined by the inputs.
Parameters
arr The inputs, each in [0, 1]
Returns
The output that is no smaller than each input
Definition at line 48 of file UtilityFunctions.java.
Referenced by nars.inference.BudgetFunctions.activate(), nars.inference.TruthFunctions.comparison(), nars.entity.Concept.getQuality(), nars.entity.BudgetValue.incDurability(), nars.entity.BudgetValue.incPriority(), nars.entity.BudgetValue.incQuality(), nars.inference.BudgetFunctions.rankBelief(), nars.inference.TruthFunctions.resemblance(), nars.inference.BudgetFunctions.revise(), nars.inference.TruthFunctions.union(), and nars.inference.BudgetFunctions.update().
{
         float product = 1;
         for (float f : arr) {
             product *= (1 - f);
         }
         return 1 - product;
     }