opennars: nars.inference.CompositionalRules.decomposeStatement
static void nars.inference.CompositionalRules.decomposeStatement (CompoundTerm compound, Term component, boolean compoundTask, Memory memory) static package
{(||, S, P), P} |- S {(&&, S, P), P} |- S
Parameters
implication The implication term to be decomposed
componentCommon The part of the implication to be removed
compoundTask Whether the implication comes from the task
memory Reference to the memory
Definition at line 293 of file CompositionalRules.java.
References nars.inference.BudgetFunctions.compoundForward(), nars.storage.Memory.doublePremiseTask(), nars.storage.Memory.getCurrentBelief(), nars.storage.Memory.getCurrentTask(), nars.entity.Task.getSentence(), nars.entity.Sentence.getTruth(), nars.entity.Sentence.isQuestion(), nars.language.CompoundTerm.reduceComponents(), nars.inference.TruthFunctions.reduceConjunction(), and nars.inference.TruthFunctions.reduceDisjunction().
Referenced by nars.inference.RuleTables.compoundAndSelf().
{
         Task task = memory.getCurrentTask();
         Sentence sentence = task.getSentence();
         if (sentence.isQuestion()) {
             return;
         }
         Sentence belief = memory.getCurrentBelief();
         Term content = CompoundTerm.reduceComponents(compound, component,
                 memory);
         if (content == null) {
             return;
         }
         TruthValue v1, v2;
         if (compoundTask) {
             v1 = sentence.getTruth();
             v2 = belief.getTruth();
         } else {
             v1 = belief.getTruth();
             v2 = sentence.getTruth();
         }
         TruthValue truth = null;
         if (compound instanceof Conjunction) {
             if (sentence instanceof Sentence) {
                 truth = TruthFunctions.reduceConjunction(v1, v2);
             }
         } else if (compound instanceof Disjunction) {
             if (sentence instanceof Sentence) {
                 truth = TruthFunctions.reduceDisjunction(v1, v2);
             }
         } else {
             return;
         }
         BudgetValue budget = BudgetFunctions.compoundForward(truth, content,
                 memory);
         memory.doublePremiseTask(content, truth, budget);
     }