opennars: nars.inference.CompositionalRules.composeCompound
static void nars.inference.CompositionalRules.composeCompound (Statement taskContent, Statement beliefContent, int index, Memory memory) static package
{<S ==> M>,
<P ==> M>} |- {<(S|P) ==> M>, <(S&P) ==> M>, <(S-P) ==> M>, <(P-S) ==> M>}
Parameters
taskSentence The first premise
belief The second premise
index The location of the shared term
memory Reference to the memory
Definition at line 52 of file CompositionalRules.java.
References nars.language.CompoundTerm.componentAt(), nars.inference.CompositionalRules.decomposeCompound(), nars.storage.Memory.getCurrentBelief(), nars.storage.Memory.getCurrentTask(), nars.entity.Task.getSentence(), nars.entity.Sentence.getTruth(), nars.inference.TruthFunctions.intersection(), nars.inference.CompositionalRules.introVarOuter(), nars.entity.Sentence.isJudgment(), nars.entity.TruthValue.isNegative(), nars.language.DifferenceExt.make(), nars.language.DifferenceInt.make(), nars.language.IntersectionExt.make(), nars.language.Disjunction.make(), nars.language.IntersectionInt.make(), nars.language.Conjunction.make(), nars.inference.TruthFunctions.negation(), nars.inference.CompositionalRules.processComposed(), and nars.inference.TruthFunctions.union().
Referenced by nars.inference.RuleTables.asymmetricAsymmetric().
{
         if ((!memory.getCurrentTask().getSentence().isJudgment())
                 || (taskContent.getClass() != beliefContent.getClass())) {
             return;
         }
         Term componentT = taskContent.componentAt(1 - index);
         Term componentB = beliefContent.componentAt(1 - index);
         Term componentCommon = taskContent.componentAt(index);
         if ((componentT instanceof CompoundTerm)
                 && ((CompoundTerm) componentT).containAllComponents(componentB)) {
             decomposeCompound((CompoundTerm) componentT, componentB,
                     componentCommon, index, true, memory);
             return;
         } else if ((componentB instanceof CompoundTerm)
                 && ((CompoundTerm) componentB).containAllComponents(componentT)) {
             decomposeCompound((CompoundTerm) componentB, componentT,
                     componentCommon, index, false, memory);
             return;
         }
         TruthValue truthT = memory.getCurrentTask().getSentence().getTruth();
         TruthValue truthB = memory.getCurrentBelief().getTruth();
         TruthValue truthOr = TruthFunctions.union(truthT, truthB);
         TruthValue truthAnd = TruthFunctions.intersection(truthT, truthB);
         Term termOr = null;
         Term termAnd = null;
         if (index == 0) {
             if (taskContent instanceof Inheritance) {
                 termOr = IntersectionInt.make(componentT, componentB, memory);
                 if (truthB.isNegative()) {
                     if (!truthT.isNegative()) {
                         termAnd = DifferenceExt.make(componentT, componentB,
                                 memory);
                         truthAnd = TruthFunctions.intersection(truthT,
                                 TruthFunctions.negation(truthB));
                     }
                 } else if (truthT.isNegative()) {
                     termAnd = DifferenceExt
                             .make(componentB, componentT, memory);
                     truthAnd = TruthFunctions.intersection(truthB,
                             TruthFunctions.negation(truthT));
                 } else {
                     termAnd = IntersectionExt.make(componentT, componentB,
                             memory);
                 }
             } else if (taskContent instanceof Implication) {
                 termOr = Disjunction.make(componentT, componentB, memory);
                 termAnd = Conjunction.make(componentT, componentB, memory);
             }
             processComposed(taskContent, componentCommon, termOr, truthOr,
                     memory);
             processComposed(taskContent, componentCommon, termAnd, truthAnd,
                     memory);
         } else { // index == 1
             if (taskContent instanceof Inheritance) {
                 termOr = IntersectionExt.make(componentT, componentB, memory);
                 if (truthB.isNegative()) {
                     if (!truthT.isNegative()) {
                         termAnd = DifferenceInt.make(componentT, componentB,
                                 memory);
                         truthAnd = TruthFunctions.intersection(truthT,
                                 TruthFunctions.negation(truthB));
                     }
                 } else if (truthT.isNegative()) {
                     termAnd = DifferenceInt
                             .make(componentB, componentT, memory);
                     truthAnd = TruthFunctions.intersection(truthB,
                             TruthFunctions.negation(truthT));
                 } else {
                     termAnd = IntersectionInt.make(componentT, componentB,
                             memory);
                 }
             } else if (taskContent instanceof Implication) {
                 termOr = Conjunction.make(componentT, componentB, memory);
                 termAnd = Disjunction.make(componentT, componentB, memory);
             }
             processComposed(taskContent, termOr, componentCommon, truthOr,
                     memory);
             processComposed(taskContent, termAnd, componentCommon, truthAnd,
                     memory);
         }
         if (taskContent instanceof Inheritance) {
             introVarOuter(taskContent, beliefContent, index, memory);// introVarImage(taskContent,
                                                                         // beliefContent,
                                                                         // index,
                                                                         // memory);
         }
     }