opennars: nars.inference.CompositionalRules.introVarOuter
static void nars.inference.CompositionalRules.introVarOuter (Statement taskContent, Statement beliefContent, int index, Memory memory) static private
Introduce a dependent variable in an outer-layer conjunction.
Parameters
taskContent The first premise <M --> S>
beliefContent The second premise <M --> P>
index The location of the shared term: 0 for subject, 1 for predicate
memory Reference to the memory
Definition at line 345 of file CompositionalRules.java.
References nars.inference.TruthFunctions.comparison(), nars.inference.BudgetFunctions.compoundForward(), nars.storage.Memory.doublePremiseTask(), nars.storage.Memory.getCurrentBelief(), nars.storage.Memory.getCurrentTask(), nars.language.Statement.getPredicate(), nars.entity.Task.getSentence(), nars.language.Statement.getSubject(), nars.entity.Sentence.getTruth(), nars.inference.TruthFunctions.induction(), nars.inference.TruthFunctions.intersection(), nars.language.Implication.make(), nars.language.Equivalence.make(), nars.language.Inheritance.make(), and nars.language.Conjunction.make().
Referenced by nars.inference.CompositionalRules.composeCompound().
{
         TruthValue truthT = memory.getCurrentTask().getSentence().getTruth();
         TruthValue truthB = memory.getCurrentBelief().getTruth();
         Variable varInd = new Variable("$varInd1");
         Variable varInd2 = new Variable("$varInd2");
         Term term11, term12, term21, term22, commonTerm;
         HashMap<Term, Term> subs = new HashMap<Term, Term>();
         if (index == 0) {
             term11 = varInd;
             term21 = varInd;
             term12 = taskContent.getPredicate();
             term22 = beliefContent.getPredicate();
             if ((term12 instanceof ImageExt) && (term22 instanceof ImageExt)) {
                 commonTerm = ((ImageExt) term12).getTheOtherComponent();
                 if ((commonTerm == null) || !((ImageExt) term22).containTerm(commonTerm)) {
                     commonTerm = ((ImageExt) term22).getTheOtherComponent();
                     if ((commonTerm == null) || !((ImageExt) term12).containTerm(commonTerm)) {
                         commonTerm = null;
                     }
                 }
                 if (commonTerm != null) {
                     subs.put(commonTerm, varInd2);
                     ((ImageExt) term12).applySubstitute(subs);
                     ((ImageExt) term22).applySubstitute(subs);
                 }
             }
         } else {
             term11 = taskContent.getSubject();
             term21 = beliefContent.getSubject();
             term12 = varInd;
             term22 = varInd;
             if ((term11 instanceof ImageInt) && (term21 instanceof ImageInt)) {
                 commonTerm = ((ImageInt) term11).getTheOtherComponent();
                 if ((commonTerm == null) || !((ImageInt) term21).containTerm(commonTerm)) {
                     commonTerm = ((ImageInt) term21).getTheOtherComponent();
                     if ((commonTerm == null) || !((ImageExt) term11).containTerm(commonTerm)) {
                         commonTerm = null;
                     }
                 }
                 if (commonTerm != null) {
                     subs.put(commonTerm, varInd2);
                     ((ImageInt) term11).applySubstitute(subs);
                     ((ImageInt) term21).applySubstitute(subs);
                 }
             }
         }
         Statement state1 = Inheritance.make(term11, term12, memory);
         Statement state2 = Inheritance.make(term21, term22, memory);
         Term content = Implication.make(state1, state2, memory);
         TruthValue truth = TruthFunctions.induction(truthT, truthB);
         BudgetValue budget = BudgetFunctions.compoundForward(truth, content, memory);
         memory.doublePremiseTask(content, truth, budget);
         content = Implication.make(state2, state1, memory);
         truth = TruthFunctions.induction(truthB, truthT);
         budget = BudgetFunctions.compoundForward(truth, content, memory);
         memory.doublePremiseTask(content, truth, budget);
         content = Equivalence.make(state1, state2, memory);
         truth = TruthFunctions.comparison(truthT, truthB);
         budget = BudgetFunctions.compoundForward(truth, content, memory);
         memory.doublePremiseTask(content, truth, budget);
         Variable varDep = new Variable("#varDep");
         if (index == 0) {
             state1 = Inheritance.make(varDep, taskContent.getPredicate(), memory);
             state2 = Inheritance.make(varDep, beliefContent.getPredicate(), memory);
         } else {
             state1 = Inheritance.make(taskContent.getSubject(), varDep, memory);
             state2 = Inheritance.make(beliefContent.getSubject(), varDep, memory);
         }
         content = Conjunction.make(state1, state2, memory);
         truth = TruthFunctions.intersection(truthT, truthB);
         budget = BudgetFunctions.compoundForward(truth, content, memory);
         memory.doublePremiseTask(content, truth, budget, false);
     }