opennars: nars.inference.CompositionalRules.introVarInner
static void nars.inference.CompositionalRules.introVarInner (Statement premise1, Statement premise2, CompoundTerm oldCompound, Memory memory) static package
     Introduce a second independent variable into two terms with a common
component
Parameters
term1 The first term
term2 The second term
index The index of the terms in their statement {<M --> S>, <C ==> <M --> P>>} |- <(&&, <#x –> S>, C) ==> <#x –> P>> {<M --> S>, (&&, C, <M --> P>)} |- (&&, C, <<#x –> S> ==> <#x –> P>>)
taskContent The first premise directly used in internal induction, <M --> S>
beliefContent The componentCommon to be used as a premise in internal induction, <M --> P>
oldCompound The whole contentInd of the first premise, Implication or Conjunction
memory Reference to the memory
Definition at line 483 of file CompositionalRules.java.
References nars.language.CompoundTerm.applySubstitute(), nars.language.CompoundTerm.containComponent(), nars.storage.Memory.doublePremiseTask(), nars.language.Term.equals(), nars.inference.BudgetFunctions.forward(), nars.entity.Sentence.getContent(), nars.storage.Memory.getCurrentBelief(), nars.storage.Memory.getCurrentTask(), nars.language.Statement.getPredicate(), nars.entity.Task.getSentence(), nars.language.Statement.getSubject(), nars.entity.Sentence.getTruth(), nars.inference.TruthFunctions.induction(), nars.inference.TruthFunctions.intersection(), nars.entity.Sentence.isJudgment(), nars.language.Implication.make(), nars.language.Conjunction.make(), and nars.inference.CompositionalRules.secondCommonTerm().
Referenced by nars.inference.RuleTables.compoundAndStatement(), and nars.inference.RuleTables.detachmentWithVar().
{
         Task task = memory.getCurrentTask();
         Sentence taskSentence = task.getSentence();
         if (!taskSentence.isJudgment() || (premise1.getClass() != premise2.getClass()) || oldCompound.containComponent(premise1)) {
             return;
         }
         Term subject1 = premise1.getSubject();
         Term subject2 = premise2.getSubject();
         Term predicate1 = premise1.getPredicate();
         Term predicate2 = premise2.getPredicate();
 //        Statement stateInd1, stateInd2, stateDep1, stateDep2;
         Term commonTerm1, commonTerm2;
         if (subject1.equals(subject2)) {
             commonTerm1 = subject1;
             commonTerm2 = secondCommonTerm(predicate1, predicate2, 0);
 //            stateDep1 = Statement.make(premise1, varDep, predicate1, memory);
 //            stateDep2 = Statement.make(premise2, varDep, predicate2, memory);
 //            Term predicate1C = (Term) predicate1.clone();
 //            Term predicate2C = (Term) predicate2.clone();
 //            introVarSecond(predicate1C, predicate2C, 0);
 //            stateInd1 = Statement.make(premise1, varInd, predicate1C, memory);
 //            stateInd2 = Statement.make(premise2, varInd, predicate2C, memory);
         } else if (predicate1.equals(predicate2)) {
             commonTerm1 = predicate1;
             commonTerm2 = secondCommonTerm(subject1, subject2, 0);
 //            stateDep1 = Statement.make(premise1, subject1, varDep, memory);
 //            stateDep2 = Statement.make(premise2, subject2, varDep, memory);
 //            Term subject1C = (Term) subject1.clone();
 //            Term subject2C = (Term) subject2.clone();
 //            introVarSecond(subject1C, subject2C, 1);
 //            stateInd1 = Statement.make(premise1, subject1C, varInd, memory);
 //            stateInd2 = Statement.make(premise2, subject2C, varInd, memory);
         } else {
             return;
         }
 //        Term implication, contentInd, contentDep = null;
 //        if (oldCompound instanceof Implication) {
 //            implication = Statement.make((Statement) oldCompound, oldCompound.componentAt(0), stateInd2, memory);
 //            contentInd = Statement.make((Statement) oldCompound, stateInd1, implication, memory);
 //            if (oldCompound.equals(premise1)) {
 //                return;
 //            }
 //            contentDep = Conjunction.make(oldCompound, premise1, memory);
 //            if (contentDep == null || !(contentDep instanceof CompoundTerm)) {
 //                return;
 //            }
 //            HashMap<Term, Term> substitute = new HashMap<Term, Term>();
 //            substitute.put(memory.currentTerm, new Variable("#varDep"));
 //            ((CompoundTerm) contentDep).applySubstitute(substitute);
 //        } else if (oldCompound instanceof Conjunction) {
 //            implication = Implication.make(stateInd1, stateInd2, memory);
 //            HashMap<Term, Term> subs = new HashMap<Term, Term>();
 //            subs.put(premise2, implication);
 //            contentInd = (Term) oldCompound.clone();
 //            ((CompoundTerm) contentInd).applySubstitute(subs);
 //            contentDep = Conjunction.make(stateDep1, oldCompound, memory);
 //            subs.clear();
 //            subs.put(premise2, stateDep2);
 //            ((CompoundTerm) contentDep).applySubstitute(subs);
 //        } else {
 //            return;
 //        }
         Sentence belief = memory.getCurrentBelief();
         HashMap<Term, Term> substitute = new HashMap<Term, Term>();
         substitute.put(commonTerm1, new Variable("#varDep2"));
         CompoundTerm content = (CompoundTerm) Conjunction.make(premise1, oldCompound, memory);
         content.applySubstitute(substitute);
         TruthValue truth = TruthFunctions.intersection(taskSentence.getTruth(), belief.getTruth());
         BudgetValue budget = BudgetFunctions.forward(truth, memory);
         memory.doublePremiseTask(content, truth, budget, false);
         substitute.clear();
         substitute.put(commonTerm1, new Variable("$varInd1"));
         if (commonTerm2 != null) {
             substitute.put(commonTerm2, new Variable("$varInd2"));
         }
         content = Implication.make(premise1, oldCompound, memory);
         content.applySubstitute(substitute);
         if (premise1.equals(taskSentence.getContent())) {
             truth = TruthFunctions.induction(belief.getTruth(), taskSentence.getTruth());
         } else {
             truth = TruthFunctions.induction(taskSentence.getTruth(), belief.getTruth());
         }
         budget = BudgetFunctions.forward(truth, memory);
         memory.doublePremiseTask(content, truth, budget);
     }