opennars: nars.inference.CompositionalRules.processComposed
static void nars.inference.CompositionalRules.processComposed (Statement statement, Term subject, Term predicate, TruthValue truth, Memory memory) static private
Finish composing implication term.
Parameters
premise1 Type of the contentInd
subject Subject of contentInd
predicate Predicate of contentInd
truth TruthValue of the contentInd
memory Reference to the memory
Definition at line 155 of file CompositionalRules.java.
References nars.inference.BudgetFunctions.compoundForward(), nars.storage.Memory.doublePremiseTask(), nars.language.Term.equals(), nars.entity.Sentence.getContent(), nars.storage.Memory.getCurrentBelief(), and nars.language.Statement.make().
Referenced by nars.inference.CompositionalRules.composeCompound().
{
         if ((subject == null) || (predicate == null)) {
             return;
         }
         Term content = Statement.make(statement, subject, predicate, memory);
         if ((content == null) || content.equals(statement)
                 || content.equals(memory.getCurrentBelief().getContent())) {
             return;
         }
         BudgetValue budget = BudgetFunctions.compoundForward(truth, content,
                 memory);
         memory.doublePremiseTask(content, truth, budget);
     }