opennars: nars.inference.CompositionalRules.decomposeCompound
static void nars.inference.CompositionalRules.decomposeCompound (CompoundTerm compound, Term component, Term term1, int index, boolean compoundTask, Memory memory) static private
{<(S|P) ==> M>,
<P ==> M>} |- <S ==> M>
Parameters
implication The implication term to be decomposed
componentCommon The part of the implication to be removed
term1 The other term in the contentInd
index The location of the shared term: 0 for subject, 1 for predicate
compoundTask Whether the implication comes from the task
memory Reference to the memory
Definition at line 189 of file CompositionalRules.java.
References nars.language.CompoundTerm.componentAt(), nars.inference.BudgetFunctions.compoundForward(), nars.storage.Memory.doublePremiseTask(), nars.language.Term.equals(), nars.entity.Task.getContent(), nars.storage.Memory.getCurrentBelief(), nars.storage.Memory.getCurrentTask(), nars.entity.Task.getSentence(), nars.entity.Sentence.getTruth(), nars.language.CompoundTerm.reduceComponents(), nars.inference.TruthFunctions.reduceConjunction(), nars.inference.TruthFunctions.reduceConjunctionNeg(), and nars.inference.TruthFunctions.reduceDisjunction().
Referenced by nars.inference.CompositionalRules.composeCompound().
{
         if (compound instanceof Statement) {
             return;
         }
         Term term2 = CompoundTerm.reduceComponents(compound, component, memory);
         if (term2 == null) {
             return;
         }
         Task task = memory.getCurrentTask();
         Sentence sentence = task.getSentence();
         Sentence belief = memory.getCurrentBelief();
         Statement oldContent = (Statement) task.getContent();
         TruthValue v1, v2;
         if (compoundTask) {
             v1 = sentence.getTruth();
             v2 = belief.getTruth();
         } else {
             v1 = belief.getTruth();
             v2 = sentence.getTruth();
         }
         TruthValue truth = null;
         Term content;
         if (index == 0) {
             content = Statement.make(oldContent, term1, term2, memory);
             if (content == null) {
                 return;
             }
             if (oldContent instanceof Inheritance) {
                 if (compound instanceof IntersectionExt) {
                     truth = TruthFunctions.reduceConjunction(v1, v2);
                 } else if (compound instanceof IntersectionInt) {
                     truth = TruthFunctions.reduceDisjunction(v1, v2);
                 } else if ((compound instanceof SetInt)
                         && (component instanceof SetInt)) {
                     truth = TruthFunctions.reduceConjunction(v1, v2);
                 } else if ((compound instanceof SetExt)
                         && (component instanceof SetExt)) {
                     truth = TruthFunctions.reduceDisjunction(v1, v2);
                 } else if (compound instanceof DifferenceExt) {
                     if (compound.componentAt(0).equals(component)) {
                         truth = TruthFunctions.reduceDisjunction(v2, v1);
                     } else {
                         truth = TruthFunctions.reduceConjunctionNeg(v1, v2);
                     }
                 }
             } else if (oldContent instanceof Implication) {
                 if (compound instanceof Conjunction) {
                     truth = TruthFunctions.reduceConjunction(v1, v2);
                 } else if (compound instanceof Disjunction) {
                     truth = TruthFunctions.reduceDisjunction(v1, v2);
                 }
             }
         } else {
             content = Statement.make(oldContent, term2, term1, memory);
             if (content == null) {
                 return;
             }
             if (oldContent instanceof Inheritance) {
                 if (compound instanceof IntersectionInt) {
                     truth = TruthFunctions.reduceConjunction(v1, v2);
                 } else if (compound instanceof IntersectionExt) {
                     truth = TruthFunctions.reduceDisjunction(v1, v2);
                 } else if ((compound instanceof SetExt)
                         && (component instanceof SetExt)) {
                     truth = TruthFunctions.reduceConjunction(v1, v2);
                 } else if ((compound instanceof SetInt)
                         && (component instanceof SetInt)) {
                     truth = TruthFunctions.reduceDisjunction(v1, v2);
                 } else if (compound instanceof DifferenceInt) {
                     if (compound.componentAt(1).equals(component)) {
                         truth = TruthFunctions.reduceDisjunction(v2, v1);
                     } else {
                         truth = TruthFunctions.reduceConjunctionNeg(v1, v2);
                     }
                 }
             } else if (oldContent instanceof Implication) {
                 if (compound instanceof Disjunction) {
                     truth = TruthFunctions.reduceConjunction(v1, v2);
                 } else if (compound instanceof Conjunction) {
                     truth = TruthFunctions.reduceDisjunction(v1, v2);
                 }
             }
         }
         if (truth != null) {
             BudgetValue budget = BudgetFunctions.compoundForward(truth,
                     content, memory);
             memory.doublePremiseTask(content, truth, budget);
         }
     }