opennars: nars.inference.BudgetFunctions.rankBelief
static float nars.inference.BudgetFunctions.rankBelief (Sentence judg) static
Determine the rank of a judgment by its confidence and originality (stamp length)
Parameters
judg The judgment to be ranked
Returns
The rank of the judgment, according to truth value only
Definition at line 57 of file BudgetFunctions.java.
References nars.entity.TruthValue.getConfidence(), nars.entity.Sentence.getStamp(), nars.entity.Sentence.getTruth(), nars.entity.Stamp.length(), and nars.inference.UtilityFunctions.or().
Referenced by nars.entity.Concept.addToTable().
{
         float confidence = judg.getTruth().getConfidence();
         float originality = 1.0f / (judg.getStamp().length() + 1);
         return or(confidence, originality);
     }