opennars: nars.inference.BudgetFunctions.solutionEval
static BudgetValue nars.inference.BudgetFunctions.solutionEval (Sentence problem, Sentence solution, Task task, Memory memory) static package
Evaluate the quality of a belief as a solution to a problem, then reward the belief and de-prioritize the problem.
Parameters
problem The problem (question or goal) to be solved
solution The belief as solution
task The task to be immediatedly processed, or null for continued process
Returns
The budget for the new task which is the belief activated, if necessary
Definition at line 81 of file BudgetFunctions.java.
References nars.storage.Memory.getCurrentBeliefLink(), nars.storage.Memory.getCurrentTask(), nars.storage.Memory.getCurrentTaskLink(), nars.entity.Item.getDurability(), nars.entity.Item.getPriority(), nars.entity.Task.getSentence(), nars.entity.Sentence.getTruth(), nars.entity.Item.incPriority(), nars.entity.Sentence.isJudgment(), nars.entity.Item.setPriority(), nars.inference.LocalRules.solutionQuality(), and nars.inference.BudgetFunctions.truthToQuality().
Referenced by nars.inference.LocalRules.trySolution().
{
         BudgetValue budget = null;
         boolean feedbackToLinks = false;
         if (task == null) { // called in continued processing
             task = memory.getCurrentTask();
             feedbackToLinks = true;
         }
         boolean judgmentTask = task.getSentence().isJudgment();
         float quality = LocalRules.solutionQuality(problem, solution);
         if (judgmentTask) {
             task.incPriority(quality);
         } else {
             task.setPriority(Math.min(1 - quality, task.getPriority()));
             budget = new BudgetValue(quality, task.getDurability(),
                     truthToQuality(solution.getTruth()));
         }
         if (feedbackToLinks) {
             TaskLink tLink = memory.getCurrentTaskLink();
             tLink.setPriority(Math.min(1 - quality, tLink.getPriority()));
             TermLink bLink = memory.getCurrentBeliefLink();
             bLink.incPriority(quality);
         }
         return budget;
     }