opennars: nars.inference.BudgetFunctions.compoundBackwardWeak
static BudgetValue nars.inference.BudgetFunctions.compoundBackwardWeak (Term content, Memory memory) static
Backward inference with CompoundTerm conclusion, weaker case.
Parameters
content The content of the conclusion
memory Reference to the memory
Returns
The budget of the conclusion
Definition at line 318 of file BudgetFunctions.java.
References nars.inference.BudgetFunctions.budgetInference(), nars.language.Term.getComplexity(), and nars.inference.UtilityFunctions.w2c().
Referenced by nars.inference.StructuralRules.contraposition(), and nars.inference.StructuralRules.structuralCompose2().
{
         return budgetInference(w2c(1), content.getComplexity(), memory);
     }