opennars: nars.inference.BudgetFunctions.truthToQuality
static float nars.inference.BudgetFunctions.truthToQuality (TruthValue t) static
Determine the quality of a judgment by its truth value alone.
Mainly decided by confidence, though binary judgment is also preferred
Parameters
t The truth value of a judgment
Returns
The quality of the judgment, according to truth value only
Definition at line 43 of file BudgetFunctions.java.
References nars.inference.UtilityFunctions.aveGeo(), nars.entity.TruthValue.getConfidence(), and nars.entity.TruthValue.getFrequency().
Referenced by nars.inference.BudgetFunctions.backward(), nars.inference.BudgetFunctions.backwardWeak(), nars.inference.BudgetFunctions.compoundForward(), nars.inference.BudgetFunctions.forward(), nars.io.StringParser.parseBudget(), nars.inference.BudgetFunctions.revise(), nars.inference.BudgetFunctions.solutionEval(), and nars.inference.BudgetFunctions.update().
{
         float freq = t.getFrequency();
         float conf = t.getConfidence();
         return aveGeo(conf, Math.abs(freq - 0.5f) + freq * 0.5f);
     }