opennars: nars.inference.BudgetFunctions.compoundForward
static BudgetValue nars.inference.BudgetFunctions.compoundForward (TruthValue truth, Term content, Memory memory) static
Forward inference with CompoundTerm conclusion.
Parameters
truth The truth value of the conclusion
content The content of the conclusion
memory Reference to the memory
Returns
The budget of the conclusion
Definition at line 290 of file BudgetFunctions.java.
References nars.inference.BudgetFunctions.budgetInference(), nars.language.Term.getComplexity(), and nars.inference.BudgetFunctions.truthToQuality().
Referenced by nars.inference.CompositionalRules.decomposeCompound(), nars.inference.CompositionalRules.decomposeStatement(), nars.inference.SyllogisticRules.elimiVarDep(), nars.inference.CompositionalRules.introVarOuter(), and nars.inference.CompositionalRules.processComposed().
{
         return budgetInference(truthToQuality(truth), content.getComplexity(),
                 memory);
     }