opennars: nars.inference.BudgetFunctions.activate
static void nars.inference.BudgetFunctions.activate (Concept concept, BudgetStruct budget) static
Activate a concept by an incoming TaskLink.
Parameters
concept The concept
budget The budget for the new item
Definition at line 183 of file BudgetFunctions.java.
References nars.inference.UtilityFunctions.aveAri(), nars.entity.Item.getDurability(), nars.entity.Item.getPriority(), nars.entity.Concept.getQuality(), nars.inference.UtilityFunctions.or(), nars.entity.Item.setDurability(), nars.entity.Item.setPriority(), and nars.entity.Item.setQuality().
Referenced by nars.storage.Memory.activateConcept().
{
         float oldPri = concept.getPriority();
         float priority = or(oldPri, budget.getPriority());
         float durability = aveAri(concept.getDurability(),
                 budget.getDurability(), oldPri / priority);
         float quality = concept.getQuality();
         concept.setPriority(priority);
         concept.setDurability(durability);
         concept.setQuality(quality);
     }