opennars: nars.inference.BudgetFunctions.update
static BudgetValue nars.inference.BudgetFunctions.update (Task task, TruthValue bTruth) static package
Update a belief.
Parameters
task The task containing new belief
bTruth Truth value of the previous belief
Returns
Budget value of the updating task
Definition at line 150 of file BudgetFunctions.java.
References nars.entity.Item.getDurability(), nars.entity.TruthValue.getExpDifAbs(), nars.entity.Item.getPriority(), nars.entity.Task.getSentence(), nars.entity.Sentence.getTruth(), nars.inference.UtilityFunctions.or(), and nars.inference.BudgetFunctions.truthToQuality().
{
         TruthValue tTruth = task.getSentence().getTruth();
         float dif = tTruth.getExpDifAbs(bTruth);
         float priority = or(dif, task.getPriority());
         float durability = or(dif, task.getDurability());
         float quality = truthToQuality(bTruth);
         return new BudgetValue(priority, durability, quality);
     }