opennars: nars.inference.BudgetFunctions.budgetInference
static BudgetValue nars.inference.BudgetFunctions.budgetInference (float qual, int complexity, Memory memory) static private
Common processing for all inference step.
Parameters
qual Quality of the inference
complexity Syntactic complexity of the conclusion
memory Reference to the memory
Returns
Budget of the conclusion task
Definition at line 333 of file BudgetFunctions.java.
References nars.inference.UtilityFunctions.and(), nars.inference.UtilityFunctions.aveAri(), nars.storage.Memory.getCurrentBeliefLink(), nars.storage.Memory.getCurrentTask(), nars.storage.Memory.getCurrentTaskLink(), nars.entity.Item.getDurability(), nars.entity.Item.getPriority(), and nars.entity.Item.incPriority().
Referenced by nars.inference.BudgetFunctions.backward(), nars.inference.BudgetFunctions.backwardWeak(), nars.inference.BudgetFunctions.compoundBackward(), nars.inference.BudgetFunctions.compoundBackwardWeak(), nars.inference.BudgetFunctions.compoundForward(), and nars.inference.BudgetFunctions.forward().
{
         Item t = memory.getCurrentTaskLink();
         if (t == null)
             t = memory.getCurrentTask();
         float priority = t.getPriority();
         float durability = t.getDurability();
         float quality = (float) (qual / Math.sqrt(complexity));
         TermLink bLink = memory.getCurrentBeliefLink();
         if (bLink != null) {
             priority = aveAri(priority, bLink.getPriority());
             durability = aveAri(durability, bLink.getDurability());
             bLink.incPriority(quality);
         }
         return new BudgetValue(and(priority, quality),
                 and(durability, quality), quality);
     }