opennars: nars.inference.BudgetFunctions.revise
static BudgetValue nars.inference.BudgetFunctions.revise (TruthValue tTruth, TruthValue bTruth, TruthValue truth, boolean feedbackToLinks, Memory memory) static package
Evaluate the quality of a revision, then de-prioritize the premises.
Parameters
tTruth The truth value of the judgment in the task
bTruth The truth value of the belief
truth The truth value of the conclusion of revision
Returns
The budget for the new task
Definition at line 118 of file BudgetFunctions.java.
References nars.entity.Item.decDurability(), nars.entity.Item.decPriority(), nars.entity.TruthValue.getConfidence(), nars.storage.Memory.getCurrentBeliefLink(), nars.storage.Memory.getCurrentTask(), nars.storage.Memory.getCurrentTaskLink(), nars.entity.Item.getDurability(), nars.entity.TruthValue.getExpDifAbs(), nars.entity.Item.getPriority(), nars.inference.UtilityFunctions.or(), and nars.inference.BudgetFunctions.truthToQuality().
Referenced by nars.inference.LocalRules.revision().
{
         float difT = truth.getExpDifAbs(tTruth);
         Task task = memory.getCurrentTask();
         task.decPriority(1 - difT);
         task.decDurability(1 - difT);
         if (feedbackToLinks) {
             TaskLink tLink = memory.getCurrentTaskLink();
             tLink.decPriority(1 - difT);
             tLink.decDurability(1 - difT);
             TermLink bLink = memory.getCurrentBeliefLink();
             float difB = truth.getExpDifAbs(bTruth);
             bLink.decPriority(1 - difB);
             bLink.decDurability(1 - difB);
         }
         float dif = truth.getConfidence()
                 - Math.max(tTruth.getConfidence(), bTruth.getConfidence());
         float priority = or(dif, task.getPriority());
         float durability = or(dif, task.getDurability());
         float quality = truthToQuality(truth);
         return new BudgetValue(priority, durability, quality);
     }