opennars: nars.inference.BudgetFunctions.backward
static BudgetValue nars.inference.BudgetFunctions.backward (TruthValue truth, Memory memory) static
Backward inference result and adjustment, stronger case.
Parameters
truth The truth value of the belief deriving the conclusion
memory Reference to the memory
Returns
The budget value of the conclusion
Definition at line 261 of file BudgetFunctions.java.
References nars.inference.BudgetFunctions.budgetInference(), and nars.inference.BudgetFunctions.truthToQuality().
Referenced by nars.inference.SyllogisticRules.abdIndCom(), nars.inference.SyllogisticRules.analogy(), nars.inference.SyllogisticRules.detachment(), nars.inference.SyllogisticRules.elimiVarDep(), and nars.inference.SyllogisticRules.resemblance().
{
         return budgetInference(truthToQuality(truth), 1, memory);
     }