opennars: nars.entity.Sentence.equals
boolean nars.entity.Sentence.equals (Object that)
To check whether two sentences are equal.
Parameters
that The other sentence
Returns
Whether the two sentences have the same content
Definition at line 83 of file Sentence.java.
References nars.language.Term.equals(), nars.entity.TruthValue.equals(), nars.entity.Stamp.equals(), nars.entity.Sentence.getContent(), nars.entity.Sentence.getPunctuation(), nars.entity.Sentence.getStamp(), nars.entity.Sentence.getTruth(), and nars.entity.Sentence.Sentence().
{
         if (that instanceof Sentence) {
             Sentence t = (Sentence) that;
             return content.equals(t.getContent()) && punctuation == t.getPunctuation() && truth.equals(t.getTruth()) && stamp.equals(t.getStamp());
         }
         return false;
     }