opennars: nars.entity.Sentence.toKey
String nars.entity.Sentence.toKey ()
Get a String representation of the sentence for key of Task and TaskLink.
Returns
The String
Definition at line 233 of file Sentence.java.
References nars.language.Term.toString(), and nars.entity.TruthValue.toStringBrief().
Referenced by nars.entity.Task.Task(), and nars.entity.Sentence.toStringBrief().
{
         StringBuffer s = new StringBuffer();
         s.append(content.toString());
         s.append(punctuation + " ");
         if (truth != null) {
             s.append(truth.toStringBrief());
         }
         return s.toString();
     }