opennars: nars.entity.Sentence.clone
Object nars.entity.Sentence.clone ()
Clone the Sentence.
Returns
The clone
Definition at line 122 of file Sentence.java.
References nars.language.Term.clone(), nars.entity.Stamp.clone(), nars.entity.Sentence.punctuation, nars.entity.Sentence.revisible, and nars.entity.Sentence.Sentence().
Referenced by nars.inference.RuleTables.detachmentWithVar(), nars.entity.Concept.getBelief(), and nars.inference.LocalRules.match().
{
         if (truth == null) {
             return new Sentence((Term) content.clone(), punctuation, null, (Stamp) stamp.clone());
         }
         return new Sentence((Term) content.clone(), punctuation, new TruthValue(truth), (Stamp) stamp.clone(), revisible);
     }