opennars: nars.entity.Sentence.toString
String nars.entity.Sentence.toString ()
Get a String representation of the sentence.
Returns
The String
Definition at line 210 of file Sentence.java.
References nars.entity.TruthValue.toString(), nars.language.Term.toString(), and nars.entity.Stamp.toString().
{
         StringBuffer s = new StringBuffer();
         s.append(content.toString());
         s.append(punctuation + " ");
         if (truth != null) {
             s.append(truth.toString());
         }
         s.append(stamp.toString());
         return s.toString();
     }