opennars: nars.entity.BudgetValue.incPriority
void nars.entity.BudgetValue.incPriority (float v)
Increase priority value by a percentage of the remaining range.
Parameters
v The increasing percent
Definition at line 100 of file BudgetValue.java.
References nars.inference.UtilityFunctions.or().
Referenced by nars.entity.Item.incPriority(), and nars.inference.BudgetFunctions.merge().
{
         priority= UtilityFunctions.or(priority, v);
     }