opennars: nars.entity.BudgetValue.summary
float nars.entity.BudgetValue.summary ()
To summarize a BudgetValue into a single number in [0, 1].
Returns
The summary value
Definition at line 188 of file BudgetValue.java.
References nars.inference.UtilityFunctions.aveGeo().
Referenced by nars.entity.BudgetValue.aboveThreshold(), nars.storage.Memory.activatedTask(), and nars.storage.Memory.derivedTask().
{
         return UtilityFunctions.aveGeo(priority, durability, quality);
     }