opennars: nars.language.InstanceProperty.make
static Statement nars.language.InstanceProperty.make (Term subject, Term predicate, Memory memory) static
Try to make a new compound from two components.
Called by the inference rules.
A {-] B becomes {A} –> [B]
Parameters
subject The first component
predicate The second component
memory Reference to the memory
Returns
A compound generated or null
Definition at line 46 of file InstanceProperty.java.
References nars.language.SetExt.make(), nars.language.SetInt.make(), and nars.language.Inheritance.make().
Referenced by nars.language.Statement.make().
{
         return Inheritance.make(SetExt.make(subject, memory),
                 SetInt.make(predicate, memory), memory);
     }