package com.googlecode.opennars.parser.loan.Loan.Absyn; // Java Package generated by the BNF Converter.

public abstract class Budget implements java.io.Serializable {
  public abstract <R,A> R accept(Budget.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(com.googlecode.opennars.parser.loan.Loan.Absyn.BudgetE p, A arg);
    public R visit(com.googlecode.opennars.parser.loan.Loan.Absyn.BudgetP p, A arg);
    public R visit(com.googlecode.opennars.parser.loan.Loan.Absyn.BudgetPD p, A arg);

  }

}
