package com.googlecode.opennars.parser.loan.Loan.Absyn; // Java Package generated by the BNF Converter.

public class DocBR extends Document {
  public final BaseRule baserule_;
  public final ListSentence listsentence_;

  public DocBR(BaseRule p1, ListSentence p2) { baserule_ = p1; listsentence_ = p2; }

  public <R,A> R accept(com.googlecode.opennars.parser.loan.Loan.Absyn.Document.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.googlecode.opennars.parser.loan.Loan.Absyn.DocBR) {
      com.googlecode.opennars.parser.loan.Loan.Absyn.DocBR x = (com.googlecode.opennars.parser.loan.Loan.Absyn.DocBR)o;
      return this.baserule_.equals(x.baserule_) && this.listsentence_.equals(x.listsentence_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.baserule_.hashCode())+this.listsentence_.hashCode();
  }


}
