package com.googlecode.opennars.parser.loan.Loan.Absyn; // Java Package generated by the BNF Converter.

public class StmImpConc extends Stm {
  public final Stm stm_1, stm_2;

  public StmImpConc(Stm p1, Stm p2) { stm_1 = p1; stm_2 = p2; }

  public <R,A> R accept(com.googlecode.opennars.parser.loan.Loan.Absyn.Stm.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.googlecode.opennars.parser.loan.Loan.Absyn.StmImpConc) {
      com.googlecode.opennars.parser.loan.Loan.Absyn.StmImpConc x = (com.googlecode.opennars.parser.loan.Loan.Absyn.StmImpConc)o;
      return this.stm_1.equals(x.stm_1) && this.stm_2.equals(x.stm_2);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.stm_1.hashCode())+this.stm_2.hashCode();
  }


}
