package com.googlecode.opennars.parser.loan.Loan.Absyn; // Java Package generated by the BNF Converter.

public class TrmLit extends Term {
  public final Literal literal_;

  public TrmLit(Literal p1) { literal_ = p1; }

  public <R,A> R accept(com.googlecode.opennars.parser.loan.Loan.Absyn.Term.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.googlecode.opennars.parser.loan.Loan.Absyn.TrmLit) {
      com.googlecode.opennars.parser.loan.Loan.Absyn.TrmLit x = (com.googlecode.opennars.parser.loan.Loan.Absyn.TrmLit)o;
      return this.literal_.equals(x.literal_);
    }
    return false;
  }

  public int hashCode() {
    return this.literal_.hashCode();
  }


}
