package com.googlecode.opennars.parser.loan.Loan.Absyn; // Java Package generated by the BNF Converter.

public class TrmProd extends Term {
  public final ListTerm listterm_;

  public TrmProd(ListTerm p1) { listterm_ = p1; }

  public <R,A> R accept(com.googlecode.opennars.parser.loan.Loan.Absyn.Term.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.googlecode.opennars.parser.loan.Loan.Absyn.TrmProd) {
      com.googlecode.opennars.parser.loan.Loan.Absyn.TrmProd x = (com.googlecode.opennars.parser.loan.Loan.Absyn.TrmProd)o;
      return this.listterm_.equals(x.listterm_);
    }
    return false;
  }

  public int hashCode() {
    return this.listterm_.hashCode();
  }


}
