opennars: nars.language.CompoundTerm.prepareComponentLinks
void nars.language.CompoundTerm.prepareComponentLinks (ArrayList< TermLink > componentLinks, short type, CompoundTerm term) private
Collect TermLink templates into a list, go down one level except in special cases.
Parameters
componentLinks The list of TermLink templates built so far
type The type of TermLink to be built
term The CompoundTerm for which the links are built
Definition at line 588 of file CompoundTerm.java.
References nars.language.CompoundTerm.componentAt(), nars.entity.TermLink.COMPOUND_CONDITION, nars.language.CompoundTerm.CompoundTerm(), nars.language.Term.isConstant(), nars.language.CompoundTerm.size(), and nars.entity.TermLink.TRANSFORM.
{
         Term t1, t2, t3;                    // components at different levels
         for (int i = 0; i < term.size(); i++) {     // first level components
             t1 = term.componentAt(i);
             if (t1.isConstant()) {
                 componentLinks.add(new TermLink(t1, type, i));
             }
             if ((t1 instanceof Conjunction) && ((this instanceof Equivalence) || ((this instanceof Implication) && (i == 0)))) {
                 ((CompoundTerm) t1).prepareComponentLinks(componentLinks, TermLink.COMPOUND_CONDITION, (CompoundTerm) t1);
             } else if (t1 instanceof CompoundTerm) {
                 for (int j = 0; j < ((CompoundTerm) t1).size(); j++) {  // second level components
                     t2 = ((CompoundTerm) t1).componentAt(j);
                     if (t2.isConstant()) {
                         if ((t1 instanceof Product) || (t1 instanceof ImageExt) || (t1 instanceof ImageInt)) {
                             if (type == TermLink.COMPOUND_CONDITION) {
                                 componentLinks.add(new TermLink(t2, TermLink.TRANSFORM, 0, i, j));
                             } else {
                                 componentLinks.add(new TermLink(t2, TermLink.TRANSFORM, i, j));
                             }
                         } else {
                             componentLinks.add(new TermLink(t2, type, i, j));
                         }
                     }
                     if ((t2 instanceof Product) || (t2 instanceof ImageExt) || (t2 instanceof ImageInt)) {
                         for (int k = 0; k < ((CompoundTerm) t2).size(); k++) {
                             t3 = ((CompoundTerm) t2).componentAt(k);
                             if (t3.isConstant()) {                           // third level
                                 if (type == TermLink.COMPOUND_CONDITION) {
                                     componentLinks.add(new TermLink(t3, TermLink.TRANSFORM, 0, i, j, k));
                                 } else {
                                     componentLinks.add(new TermLink(t3, TermLink.TRANSFORM, i, j, k));
                                 }
                             }
                         }
                     }
                 }
             }
         }
     }