opennars: nars.language.CompoundTerm.makeImageName
static String nars.language.CompoundTerm.makeImageName (String op, List< Term > arg, int relationIndex) static protected
default method to make the oldName of an image term from given fields
Parameters
op the term operator
arg the list of components
relationIndex the location of the place holder
Returns
the oldName of the term
Definition at line 285 of file CompoundTerm.java.
References nars.io.Symbols.ARGUMENT_SEPARATOR, nars.io.Symbols.COMPOUND_TERM_CLOSER, nars.io.Symbols.COMPOUND_TERM_OPENER, nars.io.Symbols.IMAGE_PLACE_HOLDER, and nars.language.Term.name.
Referenced by nars.language.ImageExt.make(), nars.language.ImageInt.make(), nars.language.ImageExt.makeName(), and nars.language.ImageInt.makeName().
{
         StringBuffer name = new StringBuffer();
         name.append(Symbols.COMPOUND_TERM_OPENER);
         name.append(op);
         name.append(Symbols.ARGUMENT_SEPARATOR);
         name.append(arg.get(relationIndex).getName());
         for (int i = 0; i < arg.size(); i++) {
             name.append(Symbols.ARGUMENT_SEPARATOR);
             if (i == relationIndex) {
                 name.append(Symbols.IMAGE_PLACE_HOLDER);
             } else {
                 name.append(arg.get(i).getName());
             }
         }
         name.append(Symbols.COMPOUND_TERM_CLOSER);
         return name.toString();
     }