opennars: nars.language.CompoundTerm.make
static Term nars.language.CompoundTerm.make (String op, ArrayList< Term > arg, Memory memory) static
Try to make a compound term from an operator and a list of components.
Called from StringParser
Parameters
op Term operator
arg Component list
memory Reference to the memory
Returns
A compound term or null
Definition at line 149 of file CompoundTerm.java.
References nars.io.Symbols.CONJUNCTION_OPERATOR, nars.io.Symbols.DIFFERENCE_EXT_OPERATOR, nars.io.Symbols.DIFFERENCE_INT_OPERATOR, nars.io.Symbols.DISJUNCTION_OPERATOR, nars.io.Symbols.IMAGE_EXT_OPERATOR, nars.io.Symbols.IMAGE_INT_OPERATOR, nars.io.Symbols.INTERSECTION_EXT_OPERATOR, nars.io.Symbols.INTERSECTION_INT_OPERATOR, nars.language.SetExt.make(), nars.language.Negation.make(), nars.language.SetInt.make(), nars.language.DifferenceInt.make(), nars.language.DifferenceExt.make(), nars.language.Disjunction.make(), nars.language.IntersectionInt.make(), nars.language.Product.make(), nars.language.IntersectionExt.make(), nars.language.ImageExt.make(), nars.language.ImageInt.make(), nars.language.Conjunction.make(), nars.io.Symbols.NEGATION_OPERATOR, nars.io.Symbols.PRODUCT_OPERATOR, nars.io.Symbols.SET_EXT_OPENER, and nars.io.Symbols.SET_INT_OPENER.
{
         if (op.length() == 1) {
             if (op.charAt(0) == Symbols.SET_EXT_OPENER) {
                 return SetExt.make(arg, memory);
             }
             if (op.charAt(0) == Symbols.SET_INT_OPENER) {
                 return SetInt.make(arg, memory);
             }
             if (op.equals(Symbols.INTERSECTION_EXT_OPERATOR)) {
                 return IntersectionExt.make(arg, memory);
             }
             if (op.equals(Symbols.INTERSECTION_INT_OPERATOR)) {
                 return IntersectionInt.make(arg, memory);
             }
             if (op.equals(Symbols.DIFFERENCE_EXT_OPERATOR)) {
                 return DifferenceExt.make(arg, memory);
             }
             if (op.equals(Symbols.DIFFERENCE_INT_OPERATOR)) {
                 return DifferenceInt.make(arg, memory);
             }
             if (op.equals(Symbols.PRODUCT_OPERATOR)) {
                 return Product.make(arg, memory);
             }
             if (op.equals(Symbols.IMAGE_EXT_OPERATOR)) {
                 return ImageExt.make(arg, memory);
             }
             if (op.equals(Symbols.IMAGE_INT_OPERATOR)) {
                 return ImageInt.make(arg, memory);
             }
         }
         if (op.length() == 2) {
             if (op.equals(Symbols.NEGATION_OPERATOR)) {
                 return Negation.make(arg, memory);
             }
             if (op.equals(Symbols.DISJUNCTION_OPERATOR)) {
                 return Disjunction.make(arg, memory);
             }
             if (op.equals(Symbols.CONJUNCTION_OPERATOR)) {
                 return Conjunction.make(arg, memory);
             }
         }
         return null;
     }