opennars: nars.language.CompoundTerm.renameVariables
void nars.language.CompoundTerm.renameVariables (HashMap< Variable, Variable > map)
Rename the variables in the compound.
Parameters
map The substitution established so far
Definition at line 517 of file CompoundTerm.java.
References nars.language.CompoundTerm.componentAt(), nars.language.CompoundTerm.CompoundTerm(), nars.language.CompoundTerm.containVar(), nars.language.Term.equals(), nars.language.Term.getName(), and nars.language.CompoundTerm.makeName().
{
         if (containVar()) {
             for (int i = 0; i < components.size(); i++) {
                 Term term = componentAt(i);
                 if (term instanceof Variable) {
                     Variable var;
                     if (term.getName().length() == 1) { // anonymous variable from input
                         var = new Variable(term.getName().charAt(0) + "" + (map.size() + 1));
                     } else {
                         var = (Variable) map.get((Variable) term);
                         if (var == null) {
                             var = new Variable(term.getName().charAt(0) + "" + (map.size() + 1));
                         }
                     }
                     if (!term.equals(var)) {
                         components.set(i, var);
                     }
                     map.put((Variable) term, var);
                 } else if (term instanceof CompoundTerm) {
                     ((CompoundTerm) term).renameVariables(map);
                     ((CompoundTerm) term).setName(((CompoundTerm) term).makeName());
                 }
             }
         }
     }