opennars: nars.language.CompoundTerm.cloneComponents
ArrayList<Term> nars.language.CompoundTerm.cloneComponents ()
Clone the component list.
Returns
The cloned component list
Definition at line 372 of file CompoundTerm.java.
References nars.language.CompoundTerm.cloneList().
Referenced by nars.language.CompoundTerm.addComponents(), nars.language.Disjunction.make(), nars.language.IntersectionInt.make(), nars.language.IntersectionExt.make(), nars.language.Product.make(), nars.language.DifferenceInt.make(), nars.language.DifferenceExt.make(), nars.language.ImageExt.make(), nars.language.ImageInt.make(), nars.language.Conjunction.make(), nars.language.CompoundTerm.reduceComponents(), nars.language.CompoundTerm.setComponent(), nars.inference.StructuralRules.structuralCompose2(), and nars.inference.StructuralRules.transformProductImage().
{
         return cloneList(components);
     }