opennars: nars.language.CompoundTerm.setComponent
static Term nars.language.CompoundTerm.setComponent (CompoundTerm compound, int index, Term t, Memory memory) static
Try to replace a component in a compound at a given index by another one.
Parameters
compound The compound
index The location of replacement
t The new component
memory Reference to the memory
Returns
The new compound
Definition at line 476 of file CompoundTerm.java.
References nars.language.CompoundTerm.cloneComponents(), nars.language.CompoundTerm.CompoundTerm(), and nars.language.CompoundTerm.make().
Referenced by nars.inference.SyllogisticRules.conditionalAna(), and nars.inference.SyllogisticRules.conditionalDedInd().
{
         ArrayList<Term> list = compound.cloneComponents();
         list.remove(index);
         if (t != null) {
             if (compound.getClass() != t.getClass()) {
                 list.add(index, t);
             } else {
                 List<Term> list2 = ((CompoundTerm) t).cloneComponents();
                 for (int i = 0; i < list2.size(); i++) {
                     list.add(index + i, list2.get(i));
                 }
             }
         }
         return make(compound, list, memory);
     }