opennars: nars.language.CompoundTerm.reduceComponents
static Term nars.language.CompoundTerm.reduceComponents (CompoundTerm t1, Term t2, Memory memory) static
Try to remove a component from a compound.
Parameters
t1 The compound
t2 The component
memory Reference to the memory
Returns
The new compound
Definition at line 457 of file CompoundTerm.java.
References nars.language.CompoundTerm.cloneComponents(), nars.language.CompoundTerm.getComponents(), and nars.language.CompoundTerm.make().
Referenced by nars.inference.SyllogisticRules.conditionalAbd(), nars.inference.CompositionalRules.decomposeCompound(), nars.inference.CompositionalRules.decomposeStatement(), and nars.inference.SyllogisticRules.elimiVarDep().
{
         boolean success;
         ArrayList<Term> list = t1.cloneComponents();
         if (t1.getClass() == t2.getClass()) {
             success = list.removeAll(((CompoundTerm) t2).getComponents());
         } else {
             success = list.remove(t2);
         }
         return (success ? make(t1, list, memory) : null);
     }