opennars: nars.language.CompoundTerm.makeCompoundName
static String nars.language.CompoundTerm.makeCompoundName (String op, Iterable< Term > arg) static protected
default method to make the oldName of a compound term from given fields
Parameters
op the term operator
arg the list of components
Returns
the oldName of the term
Definition at line 244 of file CompoundTerm.java.
References nars.io.Symbols.ARGUMENT_SEPARATOR, nars.io.Symbols.COMPOUND_TERM_CLOSER, nars.io.Symbols.COMPOUND_TERM_OPENER, nars.language.CompoundTerm.CompoundTerm(), nars.language.CompoundTerm.makeName(), and nars.language.Term.name.
Referenced by nars.language.DifferenceExt.make(), nars.language.DifferenceInt.make(), nars.language.Product.make(), nars.language.Negation.make(), nars.language.Conjunction.make(), nars.language.Disjunction.make(), nars.language.IntersectionExt.make(), nars.language.IntersectionInt.make(), and nars.language.CompoundTerm.makeName().
{
         StringBuffer name = new StringBuffer();
         name.append(Symbols.COMPOUND_TERM_OPENER);
         name.append(op);
         for (Term t : arg) {
             name.append(Symbols.ARGUMENT_SEPARATOR);
             if (t instanceof CompoundTerm) {
                 ((CompoundTerm) t).setName(((CompoundTerm) t).makeName());
             }
             name.append(t.getName());
         }
         name.append(Symbols.COMPOUND_TERM_CLOSER);
         return name.toString();
     }