opennars: nars.language.CompoundTerm.applySubstitute
void nars.language.CompoundTerm.applySubstitute (HashMap< Term, Term > subs)
Recursively apply a substitute to the current CompoundTerm.
Parameters
subs
Definition at line 547 of file CompoundTerm.java.
References nars.language.Term.clone(), nars.language.CompoundTerm.componentAt(), nars.language.CompoundTerm.components, nars.language.CompoundTerm.CompoundTerm(), nars.language.CompoundTerm.isCommutative(), nars.language.CompoundTerm.makeName(), nars.language.Term.name, and nars.language.CompoundTerm.size().
Referenced by nars.inference.CompositionalRules.introVarInner().
{
         Term t1, t2;
         for (int i = 0; i < size(); i++) {
             t1 = componentAt(i);
 //            if (t1 instanceof Variable) {
             t2 = subs.get(t1);
             if (t2 != null) {
                 components.set(i, (Term) t2.clone());
 //                }
             } else if (t1 instanceof CompoundTerm) {
                 ((CompoundTerm) t1).applySubstitute(subs);
             }
         }
         if (this.isCommutative()) {         // re-order
             TreeSet<Term> s = new TreeSet<Term>(components);
             components = new ArrayList<Term>(s);
         }
         name = makeName();
     }